# Solve a Matrix Equation Algebraically 

In [1]:
using Pkg 
#Pkg.add("SciPy")
using SciPy
using PyCall
np = pyimport("numpy")
using LinearAlgebra
using SymPy
#Pkg.add("Conda")  # Si no tienes Conda instalado
using Conda
Conda.add("ipython")

┌ Info: Running `conda install -y ipython` in root environment
└ @ Conda /Users/jorgea22/.julia/packages/Conda/zReqD/src/Conda.jl:181


Channels:
 - conda-forge
Platform: osx-arm64
Solving environment: ...working... done

# All requested packages already installed.





==> WARNING: A newer version of conda exists. <==
    current version: 24.9.2
    latest version: 25.1.1

Please update conda by running

    $ conda update -n base -c conda-forge conda




In [6]:
using PyCall
html_display = pyimport("IPython.core.display").display_html
html_display("<style>.output_area pre { font-size: 25pt; }</style>", raw=true)

In [8]:
A = [1 2 3; 4 5 6; 7 8 9]
b = [1, 2, 3]
x1 = np.linalg.solve(A,b) # Solución con numpy
# y = scipy.linalg.solve(A,b) # No pude correr con scipy por problemas de compatibilidad
z1 = A\b # Versión alternativa con LinearAlgebra
F = lu(A) # Factorización LU
y1 = F\b


3-element Vector{Float64}:
 -0.23333333333333334
  0.46666666666666673
  0.09999999999999994

In [10]:
# Definir variables simbólicas
@syms c d e 

# Matriz de coeficientes
A2 = Sym[[c d]; [1 -e]]  

# Definir el vector columna como lista de listas
b1 = Sym[2 ; 0] 

# Resolver el sistema A2 * x = b1
solucion = A2.solve(b1)

2×1 Matrix{Sym{PyObject}}:
 2*e/(c*e + d)
   2/(c*e + d)

In [11]:
DET = det(A2)

-c*e - d

In [13]:
A2inv = inv(A2)

2×2 Matrix{Sym{PyObject}}:
 e/(c*e + d)   d/(c*e + d)
 1/(c*e + d)  -c/(c*e + d)

In [14]:
A2.LUsolve(b1)

2×1 Matrix{Sym{PyObject}}:
 2*e/(c*e + d)
   2/(c*e + d)

In [15]:
A2inv = A2.inv()

2×2 Matrix{Sym{PyObject}}:
 e/(c*e + d)   d/(c*e + d)
 1/(c*e + d)  -c/(c*e + d)

In [16]:
solucion1 = A2inv*b1

2-element Vector{Sym{PyObject}}:
 2*e/(c*e + d)
   2/(c*e + d)

In [17]:
A3 = SymPy.sympy.MatrixSymbol('A', 4, 4).as_explicit()

[A_00  A_01  A_02  A_03]
[                      ]
[A_10  A_11  A_12  A_13]
[                      ]
[A_20  A_21  A_22  A_23]
[                      ]
[A_30  A_31  A_32  A_33]

In [18]:
A3.det()

A_00*A_11*A_22*A_33 - A_00*A_11*A_23*A_32 - A_00*A_12*A_21*A_33 + A_00*A_12*A_ >

> 23*A_31 + A_00*A_13*A_21*A_32 - A_00*A_13*A_22*A_31 - A_01*A_10*A_22*A_33 +  >

> A_01*A_10*A_23*A_32 + A_01*A_12*A_20*A_33 - A_01*A_12*A_23*A_30 - A_01*A_13* >

> A_20*A_32 + A_01*A_13*A_22*A_30 + A_02*A_10*A_21*A_33 - A_02*A_10*A_23*A_31  >

> - A_02*A_11*A_20*A_33 + A_02*A_11*A_23*A_30 + A_02*A_13*A_20*A_31 - A_02*A_1 >

> 3*A_21*A_30 - A_03*A_10*A_21*A_32 + A_03*A_10*A_22*A_31 + A_03*A_11*A_20*A_3 >

> 2 - A_03*A_11*A_22*A_30 - A_03*A_12*A_20*A_31 + A_03*A_12*A_21*A_30

In [19]:
cos(A3)

   /[A_00  A_01  A_02  A_03]\
   |[                      ]|
   |[A_10  A_11  A_12  A_13]|
cos|[                      ]|
   |[A_20  A_21  A_22  A_23]|
   |[                      ]|
   \[A_30  A_31  A_32  A_33]/

In [29]:
H = Sym[1+2im 1; 1 -2im+1]

2×2 Matrix{Sym}:
 1 + 2*I        1
       1  1 - 2*I

In [32]:
h = im*H
exp(h)

2×2 Matrix{Sym{PyObject}}:
 sqrt(3)*I*(-sqrt(3)*I + 2*I)*exp(sqrt(3) + I)/6 + (-2*I - sqrt(3)*I)*(sqrt(3)*I + 2*I)*exp(-sqrt(3) + I)/(6 + 4*sqrt(3))  …  (sqrt(3)*I + 2*I)*exp(-sqrt(3) + I)/(-4*sqrt(3) - 6) + (1/2 + sqrt(3)/3)*(-sqrt(3)*I + 2*I)*exp(sqrt(3) + I)
                                      (-2*I - sqrt(3)*I)*exp(-sqrt(3) + I)/(6 + 4*sqrt(3)) + sqrt(3)*I*exp(sqrt(3) + I)/6                                          exp(-sqrt(3) + I)/(-4*sqrt(3) - 6) + (1/2 + sqrt(3)/3)*exp(sqrt(3) + I)

In [28]:
h.exp()

2×2 Matrix{Sym{PyObject}}:
 sqrt(3)*I*(-sqrt(3)*I + 2*I)*exp(sqrt(3) + I)/6 + (-2*I - sqrt(3)*I)*(sqrt(3)*I + 2*I)*exp(-sqrt(3) + I)/(6 + 4*sqrt(3))  …  (sqrt(3)*I + 2*I)*exp(-sqrt(3) + I)/(-4*sqrt(3) - 6) + (1/2 + sqrt(3)/3)*(-sqrt(3)*I + 2*I)*exp(sqrt(3) + I)
                                      (-2*I - sqrt(3)*I)*exp(-sqrt(3) + I)/(6 + 4*sqrt(3)) + sqrt(3)*I*exp(sqrt(3) + I)/6                                          exp(-sqrt(3) + I)/(-4*sqrt(3) - 6) + (1/2 + sqrt(3)/3)*exp(sqrt(3) + I)

In [ ]:
n= 1000000000
C = rand(n)

1000000000-element Vector{Float64}:
 0.09712601249562702
 0.2050806522402413
 0.6326569040705634
 0.0031377311245045503
 0.5029177895266732
 0.3945233796909655
 0.8221233561099034
 0.8507511987822733
 0.6211103736037116
 0.2750513083346916
 ⋮
 0.7526141002204112
 0.1261431941731308
 0.6057706732613551
 0.22446754847371198
 0.1444073660483549
 0.828156296320269
 0.5122056501927433
 0.1230782435749126
 0.9311387481396703

In [101]:
 # x^2 + y ^2 = 1, buscamos contar los valores y que estén dentro de \sqrt{1-x^2} 
C1 = rand(n)

1000000000-element Vector{Float64}:
 0.4384075424843916
 0.6684868826500161
 0.8691746988945964
 0.41032609813002974
 0.6618665921896795
 0.39695255189578715
 0.5877173685764325
 0.8512477919893058
 0.23324860900599143
 0.61313123751229
 ⋮
 0.8072267497490532
 0.4764143463940389
 0.06966745054655088
 0.8541219974669104
 0.7635387277720437
 0.06359359377398388
 0.4467885552270744
 0.8419790998905152
 0.9376153241864698

In [102]:
D = 0
for i in 1:length(C1)
   if C[i] <= sqrt(1-(C1[i])^2)
        D = D + 1
   end
end

In [103]:
D/length(C1)*4

3.141558064

In [104]:
pi

π = 3.1415926535897...

In [105]:
f = x -> x^2

#11 (generic function with 1 method)

In [106]:
f(5)

25

In [107]:
f = x -> cos(x)

#13 (generic function with 1 method)

In [108]:
f(5)

0.28366218546322625

In [109]:
f(x) = x -> x^2 

ErrorException: cannot define function f; it already has a value

In [2]:
@doc LinearAlgebra

Linear algebra module. Provides array arithmetic, matrix factorizations and other linear algebra related functionality.


In [19]:
# Definición de las matrices de Pauli
sigmax = [0 1.0; 1 0]
sigmay = [0 -1.0im; im 0]  # im representa la unidad imaginaria √(-1)
sigmaz = [1.0 0; 0 -1]

2×2 Matrix{Float64}:
 1.0   0.0
 0.0  -1.0

In [28]:
kron(sigmaz,sigmaz,I(2))

8×8 Matrix{Float64}:
 1.0  0.0   0.0   0.0   0.0   0.0   0.0   0.0
 0.0  1.0   0.0   0.0   0.0   0.0   0.0   0.0
 0.0  0.0  -1.0   0.0   0.0   0.0  -0.0   0.0
 0.0  0.0   0.0  -1.0   0.0   0.0   0.0  -0.0
 0.0  0.0   0.0   0.0  -1.0   0.0  -0.0   0.0
 0.0  0.0   0.0   0.0   0.0  -1.0   0.0  -0.0
 0.0  0.0  -0.0   0.0  -0.0   0.0   1.0   0.0
 0.0  0.0   0.0  -0.0   0.0  -0.0   0.0   1.0

In [23]:
kron([sigmaz,sigmaz,I(2)]...)

8×8 Matrix{Float64}:
 1.0  0.0   0.0   0.0   0.0   0.0   0.0   0.0
 0.0  1.0   0.0   0.0   0.0   0.0   0.0   0.0
 0.0  0.0  -1.0   0.0   0.0   0.0  -0.0   0.0
 0.0  0.0   0.0  -1.0   0.0   0.0   0.0  -0.0
 0.0  0.0   0.0   0.0  -1.0   0.0  -0.0   0.0
 0.0  0.0   0.0   0.0   0.0  -1.0   0.0  -0.0
 0.0  0.0  -0.0   0.0  -0.0   0.0   1.0   0.0
 0.0  0.0   0.0  -0.0   0.0  -0.0   0.0   1.0

In [65]:
sigmas = Dict(1=>sigmax, 2=>sigmay, 3=>sigmaz)
function Sigma(indice, pos, totalparticulas)
    id = I(2) #[1.0 0; 0 1.0]
    mat = sigmas[indice]
    list = []
    for i in 1:totalparticulas 
        if i == pos 
            append!(list,[mat])
        else 
            append!(list,[id])
        end
        println("$list")
    end
    return kron(list...)
end

Sigma (generic function with 1 method)

In [66]:
Sigma(2,2,4)

Any[Bool[1 0; 0 1]]
Any[Bool[1 0; 0 1], ComplexF64[0.0 + 0.0im -0.0 - 1.0im; 0.0 + 1.0im 0.0 + 0.0im]]
Any[Bool[1 0; 0 1], ComplexF64[0.0 + 0.0im -0.0 - 1.0im; 0.0 + 1.0im 0.0 + 0.0im], Bool[1 0; 0 1]]
Any[Bool[1 0; 0 1], ComplexF64[0.0 + 0.0im -0.0 - 1.0im; 0.0 + 1.0im 0.0 + 0.0im], Bool[1 0; 0 1], Bool[1 0; 0 1]]


16×16 Matrix{ComplexF64}:
 0.0+0.0im  0.0+0.0im  0.0+0.0im  …   0.0+0.0im   0.0+0.0im   0.0+0.0im
 0.0+0.0im  0.0+0.0im  0.0+0.0im      0.0+0.0im   0.0+0.0im   0.0+0.0im
 0.0+0.0im  0.0+0.0im  0.0+0.0im      0.0+0.0im   0.0+0.0im   0.0+0.0im
 0.0+0.0im  0.0+0.0im  0.0+0.0im      0.0+0.0im   0.0+0.0im   0.0+0.0im
 0.0+1.0im  0.0+0.0im  0.0+0.0im      0.0+0.0im   0.0+0.0im   0.0+0.0im
 0.0+0.0im  0.0+1.0im  0.0+0.0im  …   0.0+0.0im   0.0+0.0im   0.0+0.0im
 0.0+0.0im  0.0+0.0im  0.0+1.0im      0.0+0.0im   0.0+0.0im   0.0+0.0im
 0.0+0.0im  0.0+0.0im  0.0+0.0im      0.0+0.0im   0.0+0.0im   0.0+0.0im
 0.0+0.0im  0.0+0.0im  0.0+0.0im      0.0+0.0im   0.0+0.0im   0.0+0.0im
 0.0+0.0im  0.0+0.0im  0.0+0.0im     -0.0-1.0im   0.0+0.0im   0.0+0.0im
 0.0+0.0im  0.0+0.0im  0.0+0.0im  …   0.0+0.0im  -0.0-1.0im   0.0+0.0im
 0.0+0.0im  0.0+0.0im  0.0+0.0im      0.0+0.0im   0.0+0.0im  -0.0-1.0im
 0.0+0.0im  0.0+0.0im  0.0+0.0im      0.0+0.0im   0.0+0.0im   0.0+0.0im
 0.0+0.0im  0.0+0.0im  0.0+0.0im      

In [60]:
i = Matrix(I,2,2)
list1 = []

Any[]

4-element Vector{Any}:
  true
 false
 false
  true