# Solve a Matrix Equation Algebraically 

In [3]:
using Pkg 
using SciPy
using PyCall
np = pyimport("numpy")
using LinearAlgebra
using SymPy

In [4]:
using PyCall
html_display = pyimport("IPython.core.display").display_html
html_display("<style>.output_area pre { font-size: 25pt; }</style>", raw=true)

In [5]:
A = [1 2 3; 4 5 6; 7 8 9]
b = [1, 2, 3]
x1 = np.linalg.solve(A,b) # Solución con numpy
# y = scipy.linalg.solve(A,b) # No pude correr con scipy por problemas de compatibilidad
z1 = A\b # Versión alternativa con LinearAlgebra
F = lu(A) # Factorización LU
y1 = F\b


3-element Vector{Float64}:
 -0.23333333333333334
  0.46666666666666673
  0.09999999999999994

In [6]:
# Definir variables simbólicas
@syms c d e 

# Matriz de coeficientes
A2 = Sym[[c d]; [1 -e]]  

# Definir el vector columna como lista de listas
b1 = Sym[2 ; 0] 

# Resolver el sistema A2 * x = b1
solucion = A2.solve(b1)

2×1 Matrix{Sym{PyObject}}:
 2*e/(c*e + d)
   2/(c*e + d)

In [7]:
DET = det(A2)

-c*e - d

In [8]:
A2inv = inv(A2)

2×2 Matrix{Sym{PyObject}}:
 e/(c*e + d)   d/(c*e + d)
 1/(c*e + d)  -c/(c*e + d)

In [9]:
A2.LUsolve(b1)

2×1 Matrix{Sym{PyObject}}:
 2*e/(c*e + d)
   2/(c*e + d)

In [10]:
A2inv = A2.inv()

2×2 Matrix{Sym{PyObject}}:
 e/(c*e + d)   d/(c*e + d)
 1/(c*e + d)  -c/(c*e + d)

In [11]:
solucion1 = A2inv*b1

2-element Vector{Sym{PyObject}}:
 2*e/(c*e + d)
   2/(c*e + d)

In [12]:
A3 = SymPy.sympy.MatrixSymbol('A', 4, 4).as_explicit()

[A_00  A_01  A_02  A_03]
[                      ]
[A_10  A_11  A_12  A_13]
[                      ]
[A_20  A_21  A_22  A_23]
[                      ]
[A_30  A_31  A_32  A_33]

In [13]:
A3.det()

A_00*A_11*A_22*A_33 - A_00*A_11*A_23*A_32 - A_00*A_12*A_21*A_33 + A_00*A_12*A_ >

> 23*A_31 + A_00*A_13*A_21*A_32 - A_00*A_13*A_22*A_31 - A_01*A_10*A_22*A_33 +  >

> A_01*A_10*A_23*A_32 + A_01*A_12*A_20*A_33 - A_01*A_12*A_23*A_30 - A_01*A_13* >

> A_20*A_32 + A_01*A_13*A_22*A_30 + A_02*A_10*A_21*A_33 - A_02*A_10*A_23*A_31  >

> - A_02*A_11*A_20*A_33 + A_02*A_11*A_23*A_30 + A_02*A_13*A_20*A_31 - A_02*A_1 >

> 3*A_21*A_30 - A_03*A_10*A_21*A_32 + A_03*A_10*A_22*A_31 + A_03*A_11*A_20*A_3 >

> 2 - A_03*A_11*A_22*A_30 - A_03*A_12*A_20*A_31 + A_03*A_12*A_21*A_30

In [14]:
cos(A3)

   /[A_00  A_01  A_02  A_03]\
   |[                      ]|
   |[A_10  A_11  A_12  A_13]|
cos|[                      ]|
   |[A_20  A_21  A_22  A_23]|
   |[                      ]|
   \[A_30  A_31  A_32  A_33]/

In [15]:
H = Sym[1+2im 1; 1 -2im+1]

2×2 Matrix{Sym}:
 1 + 2*I        1
       1  1 - 2*I

In [16]:
h = im*H
exp(h)

2×2 Matrix{Sym{PyObject}}:
 sqrt(3)*I*(-sqrt(3)*I + 2*I)*exp(sqrt(3) + I)/6 + (-2*I - sqrt(3)*I)*(sqrt(3)*I + 2*I)*exp(-sqrt(3) + I)/(6 + 4*sqrt(3))  …  (sqrt(3)*I + 2*I)*exp(-sqrt(3) + I)/(-4*sqrt(3) - 6) + (1/2 + sqrt(3)/3)*(-sqrt(3)*I + 2*I)*exp(sqrt(3) + I)
                                      (-2*I - sqrt(3)*I)*exp(-sqrt(3) + I)/(6 + 4*sqrt(3)) + sqrt(3)*I*exp(sqrt(3) + I)/6                                          exp(-sqrt(3) + I)/(-4*sqrt(3) - 6) + (1/2 + sqrt(3)/3)*exp(sqrt(3) + I)

In [17]:
h.exp()

2×2 Matrix{Sym{PyObject}}:
 sqrt(3)*I*(-sqrt(3)*I + 2*I)*exp(sqrt(3) + I)/6 + (-2*I - sqrt(3)*I)*(sqrt(3)*I + 2*I)*exp(-sqrt(3) + I)/(6 + 4*sqrt(3))  …  (sqrt(3)*I + 2*I)*exp(-sqrt(3) + I)/(-4*sqrt(3) - 6) + (1/2 + sqrt(3)/3)*(-sqrt(3)*I + 2*I)*exp(sqrt(3) + I)
                                      (-2*I - sqrt(3)*I)*exp(-sqrt(3) + I)/(6 + 4*sqrt(3)) + sqrt(3)*I*exp(sqrt(3) + I)/6                                          exp(-sqrt(3) + I)/(-4*sqrt(3) - 6) + (1/2 + sqrt(3)/3)*exp(sqrt(3) + I)

In [18]:
n= 1000000000
C = rand(n)

1000000000-element Vector{Float64}:
 0.8916865176836555
 0.1758258505639102
 0.17021495318104507
 0.4445277735985995
 0.2757433660331182
 0.26761437902280705
 0.2181586903036239
 0.8133846525639146
 0.7062346356997973
 0.6759965260329802
 ⋮
 0.9701672200539285
 0.24852529842062143
 0.8853884912792059
 0.7505158059995067
 0.09963743778833156
 0.10509311221278217
 0.00796658270504591
 0.02289324726396036
 0.1627999560847163

In [19]:
 # x^2 + y ^2 = 1, buscamos contar los valores y que estén dentro de \sqrt{1-x^2} 
C1 = rand(n)

1000000000-element Vector{Float64}:
 0.9139665206250541
 0.2326070536637127
 0.6024936517120543
 0.015656113375882685
 0.4913267309472583
 0.06264925261974796
 0.8854889320233821
 0.6618196455228653
 0.47189141045119387
 0.8521171819632642
 ⋮
 0.29221175266105304
 0.4911022662058653
 0.7504632801102415
 0.8400368051037864
 0.6037363564877023
 0.862029224027484
 0.957940247724077
 0.8693112835733929
 0.5685612215304465

In [20]:
D = 0
for i in 1:length(C1)
   if C[i] <= sqrt(1-(C1[i])^2)
        D = D + 1
   end
end

In [21]:
D/length(C1)*4

3.141551096

In [22]:
pi

π = 3.1415926535897...

In [23]:
f = x -> x^2

#11 (generic function with 1 method)

In [24]:
f(5)

25

In [25]:
f = x -> cos(x)

#13 (generic function with 1 method)

In [26]:
f(5)

0.28366218546322625

In [27]:
f(x) = x -> x^2 

ErrorException: cannot define function f; it already has a value

In [2]:
@doc LinearAlgebra

Linear algebra module. Provides array arithmetic, matrix factorizations and other linear algebra related functionality.


In [28]:
# Definición de las matrices de Pauli
sigmax = [0 1.0; 1 0]
sigmay = [0 -1.0im; im 0]  # im representa la unidad imaginaria √(-1)
sigmaz = [1.0 0; 0 -1]

2×2 Matrix{Float64}:
 1.0   0.0
 0.0  -1.0

In [29]:
kron(sigmaz,sigmaz,I(2))

8×8 Matrix{Float64}:
 1.0  0.0   0.0   0.0   0.0   0.0   0.0   0.0
 0.0  1.0   0.0   0.0   0.0   0.0   0.0   0.0
 0.0  0.0  -1.0   0.0   0.0   0.0  -0.0   0.0
 0.0  0.0   0.0  -1.0   0.0   0.0   0.0  -0.0
 0.0  0.0   0.0   0.0  -1.0   0.0  -0.0   0.0
 0.0  0.0   0.0   0.0   0.0  -1.0   0.0  -0.0
 0.0  0.0  -0.0   0.0  -0.0   0.0   1.0   0.0
 0.0  0.0   0.0  -0.0   0.0  -0.0   0.0   1.0

In [30]:
kron([sigmaz,sigmaz,I(2)]...)

8×8 Matrix{Float64}:
 1.0  0.0   0.0   0.0   0.0   0.0   0.0   0.0
 0.0  1.0   0.0   0.0   0.0   0.0   0.0   0.0
 0.0  0.0  -1.0   0.0   0.0   0.0  -0.0   0.0
 0.0  0.0   0.0  -1.0   0.0   0.0   0.0  -0.0
 0.0  0.0   0.0   0.0  -1.0   0.0  -0.0   0.0
 0.0  0.0   0.0   0.0   0.0  -1.0   0.0  -0.0
 0.0  0.0  -0.0   0.0  -0.0   0.0   1.0   0.0
 0.0  0.0   0.0  -0.0   0.0  -0.0   0.0   1.0

In [34]:
sigmas = Dict(1=>sigmax, 2=>sigmay, 3=>sigmaz)
function Sigma(indice, pos, totalparticulas)
    id = I(2) #[1.0 0; 0 1.0]
    mat = sigmas[indice]
    list = []
    for i in 1:totalparticulas 
        if i == pos 
            append!(list,[mat])
        else 
            append!(list,[id])
        end
        #println("$list")
    end
    return kron(list...)
end

Sigma (generic function with 1 method)

In [46]:
Sigma(3,1,4)

16×16 Matrix{Float64}:
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  …   0.0   0.0   0.0   0.0   0.0   0.0
 0.0  1.0  0.0  0.0  0.0  0.0  0.0      0.0   0.0   0.0   0.0   0.0   0.0
 0.0  0.0  1.0  0.0  0.0  0.0  0.0      0.0   0.0   0.0   0.0   0.0   0.0
 0.0  0.0  0.0  1.0  0.0  0.0  0.0      0.0   0.0   0.0   0.0   0.0   0.0
 0.0  0.0  0.0  0.0  1.0  0.0  0.0      0.0   0.0   0.0   0.0   0.0   0.0
 0.0  0.0  0.0  0.0  0.0  1.0  0.0  …   0.0   0.0   0.0   0.0   0.0   0.0
 0.0  0.0  0.0  0.0  0.0  0.0  1.0      0.0   0.0   0.0   0.0   0.0   0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0      0.0   0.0   0.0   0.0   0.0   0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0      0.0   0.0   0.0   0.0   0.0   0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0      0.0   0.0   0.0   0.0   0.0   0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  -1.0   0.0   0.0   0.0   0.0   0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0      0.0  -1.0   0.0   0.0   0.0   0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0      0.0   0.0  -1.0   0.0   0.0   0.0
 0.0  0.0  0.0 

In [37]:
i = Matrix(I,2,2) # Notación diferente para la matriz identidad sin necesidad de utilizar booleanos

2×2 Matrix{Bool}:
 1  0
 0  1

In [ ]:
# Para la cadena abierta con 4 partículas tenemos 

$ H = -J\sum_{\langle i, j \rangle} \sigma_i \sigma_j $

En un campo externo se escribe 

$ H = - J \sum_{i=1}^{3}\sigma_i \sigma_{i+1} -h \sum_{i=1}^4 S_i  $ 

Para nuestro problema que son 4 partículas tendremos 

$ H = -J(\sigma_1^z \sigma_2^z + \sigma_2^z \sigma_3^z + \sigma_3^z \sigma_4^z) - h (\sigma_1^x + \sigma_2^x + \sigma_3^x + \sigma_4^x) $

In [47]:
H = (Sigma(3,1,4) + Sigma(3,2,4) + Sigma(3,3,4))

16×16 Matrix{Float64}:
 3.0  0.0  0.0  0.0  0.0  0.0   0.0  …   0.0   0.0   0.0   0.0   0.0   0.0
 0.0  3.0  0.0  0.0  0.0  0.0   0.0      0.0   0.0   0.0   0.0   0.0   0.0
 0.0  0.0  1.0  0.0  0.0  0.0   0.0      0.0   0.0   0.0   0.0   0.0   0.0
 0.0  0.0  0.0  1.0  0.0  0.0   0.0      0.0   0.0   0.0   0.0   0.0   0.0
 0.0  0.0  0.0  0.0  1.0  0.0   0.0      0.0   0.0   0.0   0.0   0.0   0.0
 0.0  0.0  0.0  0.0  0.0  1.0   0.0  …   0.0   0.0   0.0   0.0   0.0   0.0
 0.0  0.0  0.0  0.0  0.0  0.0  -1.0      0.0   0.0   0.0   0.0   0.0   0.0
 0.0  0.0  0.0  0.0  0.0  0.0   0.0      0.0   0.0   0.0   0.0   0.0   0.0
 0.0  0.0  0.0  0.0  0.0  0.0   0.0      0.0   0.0   0.0   0.0   0.0   0.0
 0.0  0.0  0.0  0.0  0.0  0.0   0.0      0.0   0.0   0.0   0.0   0.0   0.0
 0.0  0.0  0.0  0.0  0.0  0.0   0.0  …  -1.0   0.0   0.0   0.0   0.0   0.0
 0.0  0.0  0.0  0.0  0.0  0.0   0.0      0.0  -1.0   0.0   0.0   0.0   0.0
 0.0  0.0  0.0  0.0  0.0  0.0   0.0      0.0   0.0  -1.0   0.0   0.0   0.0
 0

In [55]:
function Ising(totalparticulas)
    H = 0
    for i in 1:(totalparticulas-1)
        H = H .+ J*(Sigma(3,i,totalparticulas)*Sigma(3,i+1,totalparticulas))
    end
    for j in 1:totalparticulas
        H = H .+ h*Sigma(1,j,totalparticulas)
    end
    return H 
end

Ising (generic function with 1 method)

In [57]:
J = 1
h = 0
Ising(4)

16×16 Matrix{Float64}:
 3.0  0.0   0.0  0.0   0.0   0.0   0.0  …   0.0   0.0  0.0   0.0  0.0  0.0
 0.0  1.0   0.0  0.0   0.0   0.0   0.0      0.0   0.0  0.0   0.0  0.0  0.0
 0.0  0.0  -1.0  0.0   0.0   0.0   0.0      0.0   0.0  0.0   0.0  0.0  0.0
 0.0  0.0   0.0  1.0   0.0   0.0   0.0      0.0   0.0  0.0   0.0  0.0  0.0
 0.0  0.0   0.0  0.0  -1.0   0.0   0.0      0.0   0.0  0.0   0.0  0.0  0.0
 0.0  0.0   0.0  0.0   0.0  -3.0   0.0  …   0.0   0.0  0.0   0.0  0.0  0.0
 0.0  0.0   0.0  0.0   0.0   0.0  -1.0      0.0   0.0  0.0   0.0  0.0  0.0
 0.0  0.0   0.0  0.0   0.0   0.0   0.0      0.0   0.0  0.0   0.0  0.0  0.0
 0.0  0.0   0.0  0.0   0.0   0.0   0.0      0.0   0.0  0.0   0.0  0.0  0.0
 0.0  0.0   0.0  0.0   0.0   0.0   0.0      0.0   0.0  0.0   0.0  0.0  0.0
 0.0  0.0   0.0  0.0   0.0   0.0   0.0  …  -3.0   0.0  0.0   0.0  0.0  0.0
 0.0  0.0   0.0  0.0   0.0   0.0   0.0      0.0  -1.0  0.0   0.0  0.0  0.0
 0.0  0.0   0.0  0.0   0.0   0.0   0.0      0.0   0.0  1.0   0.0  0.0  0.0
 0

In [58]:
ishermitian(Ising(4))

true

In [67]:
size(Ising(4))

(16, 16)

In [75]:
typeof(eigen(Ising(4)))

Eigen{Float64, Float64, Matrix{Float64}, Vector{Float64}}

In [81]:
Al= eigen(Ising(4))

Eigen{Float64, Float64, Matrix{Float64}, Vector{Float64}}
values:
16-element Vector{Float64}:
 -3.0
 -3.0
 -1.0
 -1.0
 -1.0
 -1.0
 -1.0
 -1.0
  1.0
  1.0
  1.0
  1.0
  1.0
  1.0
  3.0
  3.0
vectors:
16×16 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     1.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  1.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  1.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.

In [89]:
Al.vectors

16×16 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     1.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  1.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  1.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

In [77]:
lambda, V = eigen(Ising(4))

Eigen{Float64, Float64, Matrix{Float64}, Vector{Float64}}
values:
16-element Vector{Float64}:
 -3.0
 -3.0
 -1.0
 -1.0
 -1.0
 -1.0
 -1.0
 -1.0
  1.0
  1.0
  1.0
  1.0
  1.0
  1.0
  3.0
  3.0
vectors:
16×16 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     1.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  1.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  1.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.

In [91]:
V[:,1]

16-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0
 1.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

16-element Vector{Float64}:
 -3.0
 -3.0
 -1.0
 -1.0
 -1.0
 -1.0
 -1.0
 -1.0
  1.0
  1.0
  1.0
  1.0
  1.0
  1.0
  3.0
  3.0