In [1]:
using Plots
using LinearAlgebra
using LaTeXStrings
using HDF5

In [2]:
list = [1:3  for _ in 1:k]

UndefVarError: UndefVarError: `k` not defined in `Main`
Suggestion: check for spelling errors or missing imports.

In [3]:
N = 3 # number of qubits
d = 2^N # dimension of the Hilbert space

sigmax = [0 1; 1 0]
sigmay = [0 -im; im 0]
sigmaz = [1 0; 0 -1]
id= [1 0; 0 1] # Matriz identidad


Sigma = Dict(0 => id, 1 => sigmax, 2 => sigmay, 3 => sigmaz) #Diccionario para llamar a las matrices de Pauli
Sigma[1]

2×2 Matrix{Int64}:
 0  1
 1  0

### a |> f = f(a)

In [4]:
#particles= 10
#k=3
#list=[1:3 for _ in 1:k]
#test_visual_list = []
#for place in 1:particles-k+1
#    for i in Base.product(list...)
#        total_list=zeros(particles)
#        total_list[place:place+k-1]= i|>collect
#        print(total_list)
#        push!(test_visual_list,total_list)
#        print("\n")
#    end
#end

In [5]:
# Usarlo para la suma 
N = particles
C = test_visual_list
x = rand(length(test_visual_list))*2 .-1
# A = reduce(kron, [Sigma[C[1][i]] for i in eachindex(C[1])])


UndefVarError: UndefVarError: `particles` not defined in `Main`
Suggestion: check for spelling errors or missing imports.

In [6]:
H = zeros(ComplexF64,2^N,2^N)
for k in 1:length(test_visual_list)
    H += x[k]*reduce(kron, [Sigma[C[k][i]] for i in eachindex(C[1])])
end
H 

UndefVarError: UndefVarError: `test_visual_list` not defined in `Main`
Suggestion: check for spelling errors or missing imports.

In [7]:
H = zeros(ComplexF64,2^N,2^N)
for k in 1:length(test_visual_list)
    H += x[k]*kron([Sigma[C[k][i]] for i in eachindex(C[1])]...)
end
H 

# Hay que guardar las A's
# Buscar el mejor formato para guardar matrices en Julia 

UndefVarError: UndefVarError: `test_visual_list` not defined in `Main`
Suggestion: check for spelling errors or missing imports.

$\{A_i\}$ deben ser operadores fijos lo que varían son 1000 datos distintos del conjunto de $\{c_i\}$ y tomar la mitad inferior de $\{\ket{\psi_n\}}$ ¿Qué tanto podemos reducir los estados y que nos siga dando una buena aproximación? 

### Almacenar todos los operadores locales A 

In [8]:
#particles=3
#k=3
#list=[0:3 for _ in 1:k]
#test_visual_list2 = []
#for place in 1:particles-k+1
#for i in Base.product(list...)
#    total_list=zeros(particles)
#    total_list[place:place+k-1]= i|>collect
#    print(total_list)
#    push!(test_visual_list,total_list)
#    print("\n")
#end
#end

In [9]:
particles=3
k=2
list=[0:3 for _ in 1:k]
test_visual_list = []
place= 2
for i in Base.product(list...)
    total_list=zeros(particles)
    total_list[place:place+k-1]= i|>collect
    if sum(total_list) != 0
        ##print(total_list)
        push!(test_visual_list,total_list)
    end
   # print("\n")
end
test_visual_list

15-element Vector{Any}:
 [0.0, 1.0, 0.0]
 [0.0, 2.0, 0.0]
 [0.0, 3.0, 0.0]
 [0.0, 0.0, 1.0]
 [0.0, 1.0, 1.0]
 [0.0, 2.0, 1.0]
 [0.0, 3.0, 1.0]
 [0.0, 0.0, 2.0]
 [0.0, 1.0, 2.0]
 [0.0, 2.0, 2.0]
 [0.0, 3.0, 2.0]
 [0.0, 0.0, 3.0]
 [0.0, 1.0, 3.0]
 [0.0, 2.0, 3.0]
 [0.0, 3.0, 3.0]

In [10]:
sum(test_visual_list[6])

3.0

In [11]:
particles = 3 
place = 1

k=2
list=[0:3 for _ in 1:k]
test_visual_list = []

for i in Base.product(list...)
    total_list=zeros(particles)
    total_list[place:place+k-1]= i|>collect
    if sum(total_list) != 0
        ##print(total_list)
        push!(test_visual_list,total_list)
    end
   # print("\n")
end

ArrayA1 = []
for i in 1:length(test_visual_list)
    if test_visual_list[i][place] != test_visual_list[i][place+1] && sum(test_visual_list[i]) != 0
        push!(ArrayA1,test_visual_list[i])
    end
end
ArrayA1

12-element Vector{Any}:
 [1.0, 0.0, 0.0]
 [2.0, 0.0, 0.0]
 [3.0, 0.0, 0.0]
 [0.0, 1.0, 0.0]
 [2.0, 1.0, 0.0]
 [3.0, 1.0, 0.0]
 [0.0, 2.0, 0.0]
 [1.0, 2.0, 0.0]
 [3.0, 2.0, 0.0]
 [0.0, 3.0, 0.0]
 [1.0, 3.0, 0.0]
 [2.0, 3.0, 0.0]

In [12]:
particles = 3 
place = 2

k=2
list=[0:3 for _ in 1:k]
test_visual_list = []

for i in Base.product(list...)
    total_list=zeros(particles)
    total_list[place:place+k-1]= i|>collect
    if sum(total_list) != 0
        ##print(total_list)
        push!(test_visual_list,total_list)
    end
   # print("\n")
end

ArrayA2 = []
for i in 1:length(test_visual_list)
    if test_visual_list[i][place] != test_visual_list[i][place+1] && sum(test_visual_list[i]) != 0
        push!(ArrayA2,test_visual_list[i])
    end
end
ArrayA2

12-element Vector{Any}:
 [0.0, 1.0, 0.0]
 [0.0, 2.0, 0.0]
 [0.0, 3.0, 0.0]
 [0.0, 0.0, 1.0]
 [0.0, 2.0, 1.0]
 [0.0, 3.0, 1.0]
 [0.0, 0.0, 2.0]
 [0.0, 1.0, 2.0]
 [0.0, 3.0, 2.0]
 [0.0, 0.0, 3.0]
 [0.0, 1.0, 3.0]
 [0.0, 2.0, 3.0]

In [13]:
ArrayA1

12-element Vector{Any}:
 [1.0, 0.0, 0.0]
 [2.0, 0.0, 0.0]
 [3.0, 0.0, 0.0]
 [0.0, 1.0, 0.0]
 [2.0, 1.0, 0.0]
 [3.0, 1.0, 0.0]
 [0.0, 2.0, 0.0]
 [1.0, 2.0, 0.0]
 [3.0, 2.0, 0.0]
 [0.0, 3.0, 0.0]
 [1.0, 3.0, 0.0]
 [2.0, 3.0, 0.0]

In [14]:
ArrayA2

xaleat = rand(length(ArrayA1))*2 .-1
xaleat2 = rand(length(ArrayA2))*2 .-1

12-element Vector{Float64}:
 -0.15294918135333102
  0.7580049812599243
  0.6656247806699016
 -0.5205218025234692
  0.5171823677063134
 -0.3092476932033743
  0.26836122404575047
  0.9701208063433182
 -0.4563226814989152
  0.4288948575198239
  0.6755616720861084
 -0.2271566609118818

In [15]:

xaleat = rand(length(ArrayA1))*2 .-1
xaleat2 = rand(length(ArrayA2))*2 .-1

A1= zeros(2^particles,2^particles)

for k in 1:length(ArrayA1)
    A1 += xaleat[k]*kron([Sigma[ArrayA1[k][i]] for i in eachindex(ArrayA1[1])]...)
end

A2= zeros(2^particles,2^particles)

for k in 1:length(ArrayA2)
    A2 += xaleat2[k]*kron([Sigma[ArrayA2[k][i]] for i in eachindex(ArrayA2[1])]...)
end

In [16]:
A1

8×8 Matrix{ComplexF64}:
 0.00889397+0.0im              0.0+0.0im       …          0.0+0.0im
        0.0+0.0im       0.00889397+0.0im                  0.0+0.362124im
   0.445932-0.077689im         0.0+0.0im                  0.0+0.0im
        0.0+0.0im         0.445932-0.077689im        0.225309+0.119429im
   0.655774-1.59452im          0.0+0.0im                  0.0+0.0im
        0.0+0.0im         0.655774-1.59452im   …       1.3398+1.31907im
        0.0-0.362124im         0.0+0.0im                  0.0+0.0im
        0.0+0.0im              0.0-0.362124im     -0.00889397+0.0im

In [17]:
A2

8×8 Matrix{ComplexF64}:
  1.32674+0.0im        0.572144+1.50572im   …       0.0+0.0im
 0.572144-1.50572im   -0.558445+0.0im               0.0+0.0im
 0.234514-0.791285im        0.0-0.74392im           0.0+0.0im
      0.0-0.834808im   -1.16818-0.949266im          0.0+0.0im
      0.0+0.0im             0.0+0.0im               0.0+0.834808im
      0.0+0.0im             0.0+0.0im       …  -1.16818+0.949266im
      0.0+0.0im             0.0+0.0im          0.280237+0.090099im
      0.0+0.0im             0.0+0.0im          -1.32674+0.0im

Ya tengo dos operadores locales para el caso de 3 partículas, será un problema generalizar, porque lo tendré que hacer a mano pues no veo una forma buena de hacer los Arrays, tal vez deba ver cómo hacerlo en diccionario...

$H = \sum_i C_i A_i$, aquí es donde queremos generar 1000 pares de elementos C1 y C2 para formar distintos Hamiltonianos y almacenarlos 

Necesito los promedios también de A1 y A2 con los vectores propios de H, haremos una prueba para un sólo valor 

In [18]:
c = rand(1000,2)*2 .-1 # sería conveniente generar una matriz de n x 2 

1000×2 Matrix{Float64}:
  0.676098   0.759102
 -0.643229   0.280716
  0.877233   0.540661
  0.896947   0.0820346
 -0.63203   -0.294144
 -0.851135  -0.51647
 -0.396544   0.777265
  0.301915   0.0263606
  0.121041   0.14346
 -0.386411  -0.904112
  ⋮         
 -0.124542  -0.224885
  0.486317   0.326533
  0.126994   0.541365
 -0.455271  -0.0609267
 -0.688468  -0.0440453
 -0.680228   0.754334
  0.459964  -0.318538
  0.498536   0.350377
 -0.732888  -0.891761

In [19]:
Hnew = c[1,1]A1 + c[1,2]A2 # Recordemos quiero almacenar ai y ci, ai son promedios de los operadores y ci son simplemente números aleatorios uniformes entre [-1.1]
vecs = eigen(Hnew).vectors
advecs = adjoint(vecs)

# NADA MÁS QUEREMOS USAR LA PRIMER MITAD DE LOS VALORES ESPERADOS 
# ¿Cómo entrenar la red? 
# ¿Cuál es el formato que espera para los datos de entrada y salida? El resto se tiene que automatizar 
# Que reciba los valores esperados, pero para entrenarlo, la idea es que tome varios conjuntos de valores esperados y para cada uno de ellos valorar la red para definir 
# la función que va a minimizar. 
# Lux   (y SciML)
# SimpleChains 

8×8 adjoint(::Matrix{ComplexF64}) with eltype ComplexF64:
  0.0164962-0.183288im   -0.334253+0.0140452im  …   0.408897+0.0im
  -0.127478+0.356742im      0.3415+0.0256728im      0.577139-0.0im
 -0.0251187-0.177203im   -0.572344+0.0556344im       0.11178+0.0im
 -0.0667245-0.231122im    0.227302+0.0634726im      0.525853-0.0im
   0.401617-0.251491im   0.0300369-0.0295346im      0.302991-0.0im
   0.161499+0.300914im   -0.527296-0.0493252im  …   0.215599-0.0im
  -0.217251-0.276096im  -0.0859395-0.0517174im     -0.190819+0.0im
   0.491412+0.163181im    0.146435+0.265851im      -0.189735+0.0im

In [20]:
ExpVal1 = zeros(ComplexF64,size(vecs)[1])
for i in 1:size(vecs)[1]
    ExpVal1[i] = transpose(advecs[i,:])*A1*vecs[:,i]
end

ExpVal2 = zeros(ComplexF64,size(vecs)[1])  # ExpVal2[1] = a21 = \bra{\phi1_}A_2\ket{\phi_1}
for i in 1:size(vecs)[1]
    ExpVal2[i] = transpose(advecs[i,:])*A2*vecs[:,i]
end
ExpVal1

8-element Vector{ComplexF64}:
   -2.845294537021639 - 6.938893903907228e-17im
     -1.6548561070912 + 0.0im
 -0.46645693586646253 + 1.3877787807814457e-17im
 -0.04916129864028071 - 6.938893903907228e-18im
   0.9287907579335735 - 8.326672684688674e-17im
   1.2894328534349495 + 0.0im
   0.6594533891517109 - 1.249000902703301e-16im
    2.138091878099343 + 3.469446951953614e-17im

In [21]:
c1 = Tuple(c[1,:])
dic = Dict()



Dict{Any, Any}()

In [22]:
c[1,:]

2-element Vector{Float64}:
 0.6760975875880799
 0.75910180348015

In [23]:
dic[c1] = [ExpVal1,ExpVal2]

2-element Vector{Vector{ComplexF64}}:
 [-2.845294537021639 - 6.938893903907228e-17im, -1.6548561070912 + 0.0im, -0.46645693586646253 + 1.3877787807814457e-17im, -0.04916129864028071 - 6.938893903907228e-18im, 0.9287907579335735 - 8.326672684688674e-17im, 1.2894328534349495 + 0.0im, 0.6594533891517109 - 1.249000902703301e-16im, 2.138091878099343 + 3.469446951953614e-17im]
 [-2.3939685679539817 + 1.3877787807814457e-17im, -0.9127596385547132 + 1.3877787807814457e-17im, -1.5376651167782758 + 0.0im, -0.3392532466208072 - 3.469446951953614e-17im, 0.0238884983010082 + 4.85722573273506e-17im, 0.6328857318628871 - 3.469446951953614e-18im, 1.8442875941916177 - 3.8163916471489756e-17im, 2.682584745552269 - 2.7755575615628914e-17im]

In [24]:
dic[c1][1] #ExpVal1 

8-element Vector{ComplexF64}:
   -2.845294537021639 - 6.938893903907228e-17im
     -1.6548561070912 + 0.0im
 -0.46645693586646253 + 1.3877787807814457e-17im
 -0.04916129864028071 - 6.938893903907228e-18im
   0.9287907579335735 - 8.326672684688674e-17im
   1.2894328534349495 + 0.0im
   0.6594533891517109 - 1.249000902703301e-16im
    2.138091878099343 + 3.469446951953614e-17im

In [25]:
dic[c1][2] # ExpVal2

8-element Vector{ComplexF64}:
 -2.3939685679539817 + 1.3877787807814457e-17im
 -0.9127596385547132 + 1.3877787807814457e-17im
 -1.5376651167782758 + 0.0im
 -0.3392532466208072 - 3.469446951953614e-17im
  0.0238884983010082 + 4.85722573273506e-17im
  0.6328857318628871 - 3.469446951953614e-18im
  1.8442875941916177 - 3.8163916471489756e-17im
   2.682584745552269 - 2.7755575615628914e-17im

In [26]:
c1

(0.6760975875880799, 0.75910180348015)

In [27]:
dic[c1]

2-element Vector{Vector{ComplexF64}}:
 [-2.845294537021639 - 6.938893903907228e-17im, -1.6548561070912 + 0.0im, -0.46645693586646253 + 1.3877787807814457e-17im, -0.04916129864028071 - 6.938893903907228e-18im, 0.9287907579335735 - 8.326672684688674e-17im, 1.2894328534349495 + 0.0im, 0.6594533891517109 - 1.249000902703301e-16im, 2.138091878099343 + 3.469446951953614e-17im]
 [-2.3939685679539817 + 1.3877787807814457e-17im, -0.9127596385547132 + 1.3877787807814457e-17im, -1.5376651167782758 + 0.0im, -0.3392532466208072 - 3.469446951953614e-17im, 0.0238884983010082 + 4.85722573273506e-17im, 0.6328857318628871 - 3.469446951953614e-18im, 1.8442875941916177 - 3.8163916471489756e-17im, 2.682584745552269 - 2.7755575615628914e-17im]

In [28]:
dic2 = Dict()

Dict{Any, Any}()

In [29]:
dic2[1] = c1

(0.6760975875880799, 0.75910180348015)

In [30]:
dic2[1]

(0.6760975875880799, 0.75910180348015)

In [31]:
dic2

Dict{Any, Any} with 1 entry:
  1 => (0.676098, 0.759102)

In [32]:
dic[dic2[1]]

2-element Vector{Vector{ComplexF64}}:
 [-2.845294537021639 - 6.938893903907228e-17im, -1.6548561070912 + 0.0im, -0.46645693586646253 + 1.3877787807814457e-17im, -0.04916129864028071 - 6.938893903907228e-18im, 0.9287907579335735 - 8.326672684688674e-17im, 1.2894328534349495 + 0.0im, 0.6594533891517109 - 1.249000902703301e-16im, 2.138091878099343 + 3.469446951953614e-17im]
 [-2.3939685679539817 + 1.3877787807814457e-17im, -0.9127596385547132 + 1.3877787807814457e-17im, -1.5376651167782758 + 0.0im, -0.3392532466208072 - 3.469446951953614e-17im, 0.0238884983010082 + 4.85722573273506e-17im, 0.6328857318628871 - 3.469446951953614e-18im, 1.8442875941916177 - 3.8163916471489756e-17im, 2.682584745552269 - 2.7755575615628914e-17im]

In [33]:
dic3 = Dict()
for i in 1:10
    dic3[i] = 2*i
end
dic3

Dict{Any, Any} with 10 entries:
  5  => 10
  4  => 8
  6  => 12
  7  => 14
  2  => 4
  10 => 20
  9  => 18
  8  => 16
  3  => 6
  1  => 2

In [34]:
dic3[7]

14

(-0.6432288508007027, 0.2807160469792338)

In [50]:
xaleatMat1 = rand(1000,length(ArrayA1)).*2 .-1
xaleatMat2 = rand(1000,length(ArrayA2)).*2 .-1

APrueba = zeros(2^particles,2^particles)
APrueba2 = ones(2^particles,2^particles)

dicPrueba = Dict()
dicPrueba[1] = APrueba
dicPrueba[2] = APrueba2
dicPrueba[1][:,:]
xaleatMat1[1,:]

12-element Vector{Float64}:
 -0.29071010566727495
  0.13959886037809732
  0.5900678335396834
  0.4198864047693911
  0.7577212794464256
  0.47955869369264725
  0.007198013798468628
 -0.053673726624980045
  0.9307270021976481
  0.2804566700969069
  0.6483573039274431
 -0.03654290497645629

In [137]:
# Construcción de las 1000 tuplas con dos constantes aleatorias para c1 y c2 para A1 y A2 respectivamente
Cdic = Dict()
for k in 1:1000
    Cdic[k] = Tuple(c[k,:])
end
Cdic[k]

# Construcción de los 1000 operadores locales (Aleatorios)

xaleatMat1 = rand(1000,length(ArrayA1)).*2 .-1
xaleatMat2 = rand(1000,length(ArrayA2)).*2 .-1

dicA1Total = Dict()

for i in 1:1000
    A1P = zeros(2^particles,2^particles)
    for k in 1:length(ArrayA1)
        A1P += xaleatMat1[i,k]*kron([Sigma[ArrayA1[k][i]] for i in eachindex(ArrayA1[1])]...)
    end
    dicA1Total[i] = A1P
end

dicA2Total = Dict()

for i in 1:1000
    A2P = zeros(2^particles,2^particles)
    for k in 1:length(ArrayA2)
        A2P += xaleatMat2[i,k]*kron([Sigma[ArrayA2[k][i]] for i in eachindex(ArrayA2[1])]...)
    end
    dicA2Total[i] = A2P
end

Cdic[k] # Cdic[k][1] y Cdic[k][2]

Hdic = Dict()

for i in 1:1000
    Hdic[i] = c[i,1]*dicA1Total[i] + c[i,2]*dicA2Total[i]
end

In [133]:
ExpVal1Dic = Dict()
ExpVal2Dic = Dict()

for k in 1:1000
    Hnew = Hdic[k]
    vecs = eigen(Hnew).vectors
    advecs = adjoint(vecs)

    ExpVal1 = zeros(ComplexF64,size(vecs)[1])
    for i in 1:size(vecs)[1]
        ExpVal1[i] = transpose(advecs[i,:])*A1*vecs[:,i]
    end

    ExpVal2 = zeros(ComplexF64,size(vecs)[1])  # ExpVal2[1] = a21 = \bra{\phi1_}A_2\ket{\phi_1}
    for i in 1:size(vecs)[1]
        ExpVal2[i] = transpose(advecs[i,:])*A2*vecs[:,i]
    end
    ExpVal1Dic[k] = ExpVal1
    ExpVal2Dic[k] = ExpVal2
end
