In [8]:
using Plots
using LinearAlgebra
using LaTeXStrings

In [9]:
list = [1:3  for _ in 1:k]

3-element Vector{UnitRange{Int64}}:
 1:3
 1:3
 1:3

In [10]:
N = 3 # number of qubits
d = 2^N # dimension of the Hilbert space

sigmax = [0 1; 1 0]
sigmay = [0 -im; im 0]
sigmaz = [1 0; 0 -1]
id= I(2)


Sigma = Dict(0 => id, 1 => sigmax, 2 => sigmay, 3 => sigmaz) #Diccionario para llamar a las matrices de Pauli
Sigma[1]

2×2 Matrix{Int64}:
 0  1
 1  0

### a |> f = f(a)

In [11]:
particles= 10
k=3
list=[1:3 for _ in 1:k]
test_visual_list = []
for place in 1:particles-k+1
    for i in Base.product(list...)
        total_list=zeros(particles)
        total_list[place:place+k-1]= i|>collect
        print(total_list)
        push!(test_visual_list,total_list)
        print("\n")
    end
end

[1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[2.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[3.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[1.0, 2.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[2.0, 2.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[3.0, 2.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[1.0, 3.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[2.0, 3.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[3.0, 3.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[1.0, 1.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[2.0, 1.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[3.0, 1.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[1.0, 2.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[2.0, 2.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[3.0, 2.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[1.0, 3.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[2.0, 3.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[3.0, 3.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[1.0, 1.0, 3.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[2.0, 1.0, 3.0, 0.0, 0.0, 0.0, 

In [12]:
# Usarlo para la suma 
N = particles
C = test_visual_list
x = rand(length(test_visual_list))*2 .-1
# A = reduce(kron, [Sigma[C[1][i]] for i in eachindex(C[1])])


216-element Vector{Float64}:
  0.00414372891272774
 -0.04896960863500355
 -0.7564843017957474
  0.5417814334729032
 -0.44721250405118296
 -0.21571955539269205
 -0.4371248531299117
  0.019881219478304013
  0.7217541982822655
 -0.7941698363398955
  ⋮
 -0.45104924891892173
  0.08240141078583485
 -0.9272694731897149
  0.3127114355554972
  0.6140150861390572
  0.2266352029138612
 -0.2887067439085558
 -0.1797921264483453
  0.8033039163176694

In [13]:
H = zeros(ComplexF64,2^N,2^N)
for k in 1:length(test_visual_list)
    H += x[k]*reduce(kron, [Sigma[C[k][i]] for i in eachindex(C[1])])
end
H 

1024×1024 Matrix{ComplexF64}:
  -0.373454+0.0im         0.816588-0.859364im  …         0.0+0.0im
   0.816588+0.859364im    -1.98006+0.0im                 0.0+0.0im
  -0.403586-0.200474im     -0.6149-1.31248im             0.0+0.0im
   0.271499-0.464438im     1.45095-0.653745im            0.0+0.0im
  -0.477978-0.883933im     1.05102-0.763666im            0.0+0.0im
   0.603619-0.605237im   0.0994359-0.524349im  …         0.0+0.0im
   -1.39264+1.22864im      1.95029-1.84608im             0.0+0.0im
    1.00787-0.849094im    0.737491+0.438416im            0.0+0.0im
 -0.0873412+2.36896im          0.0+0.0im                 0.0+0.0im
        0.0+0.0im       -0.0873412+2.36896im             0.0+0.0im
           ⋮                                   ⋱  
        0.0+0.0im              0.0+0.0im       …  -0.0873412-2.36896im
        0.0+0.0im              0.0+0.0im             1.00787+0.849094im
        0.0+0.0im              0.0+0.0im             1.39264+1.22864im
        0.0+0.0im              0.0+

In [14]:
H = zeros(ComplexF64,2^N,2^N)
for k in 1:length(test_visual_list)
    H += x[k]*kron([Sigma[C[k][i]] for i in eachindex(C[1])]...)
end
H 

# Hay que guardar las A's
# Buscar el mejor formato para guardar matrices en Julia 

1024×1024 Matrix{ComplexF64}:
  -0.373454+0.0im         0.816588-0.859364im  …         0.0+0.0im
   0.816588+0.859364im    -1.98006+0.0im                 0.0+0.0im
  -0.403586-0.200474im     -0.6149-1.31248im             0.0+0.0im
   0.271499-0.464438im     1.45095-0.653745im            0.0+0.0im
  -0.477978-0.883933im     1.05102-0.763666im            0.0+0.0im
   0.603619-0.605237im   0.0994359-0.524349im  …         0.0+0.0im
   -1.39264+1.22864im      1.95029-1.84608im             0.0+0.0im
    1.00787-0.849094im    0.737491+0.438416im            0.0+0.0im
 -0.0873412+2.36896im          0.0+0.0im                 0.0+0.0im
        0.0+0.0im       -0.0873412+2.36896im             0.0+0.0im
           ⋮                                   ⋱  
        0.0+0.0im              0.0+0.0im       …  -0.0873412-2.36896im
        0.0+0.0im              0.0+0.0im             1.00787+0.849094im
        0.0+0.0im              0.0+0.0im             1.39264+1.22864im
        0.0+0.0im              0.0+

$\{A_i\}$ deben ser operadores fijos lo que varían son 1000 datos distintos del conjunto de $\{c_i\}$ y tomar la mitad inferior de $\{\ket{\psi_n\}}$ ¿Qué tanto podemos reducir los estados y que nos siga dando una buena aproximación? 