In [1]:
using Plots
using LinearAlgebra
using LaTeXStrings
using HDF5

No supervisado

Familias de Hamiltonianos y se generen valores esperados
y si se usa clustering y se agrupa con los datos e identificar los que se parecen 
y si se puede identificar las familias de Hamiltonianos

normalización de batches 
y dropout (Para eliminar aleatoriamente)

In [2]:
k=3
list = [1:3  for _ in 1:k]

3-element Vector{UnitRange{Int64}}:
 1:3
 1:3
 1:3

In [3]:
N = 3 # number of qubits
d = 2^N # dimension of the Hilbert space

sigmax = [0 1; 1 0]
sigmay = [0 -im; im 0]
sigmaz = [1 0; 0 -1]
id= [1 0; 0 1] # Matriz identidad


Sigma = Dict(0 => id, 1 => sigmax, 2 => sigmay, 3 => sigmaz) #Diccionario para llamar a las matrices de Pauli
Sigma[1]

2×2 Matrix{Int64}:
 0  1
 1  0

### a |> f = f(a)

In [4]:
#particles= 10
#k=3
#list=[1:3 for _ in 1:k]
#test_visual_list = []
#for place in 1:particles-k+1
#    for i in Base.product(list...)
#        total_list=zeros(particles)
#        total_list[place:place+k-1]= i|>collect
#        print(total_list)
#        push!(test_visual_list,total_list)
#        print("\n")
#    end
#end

In [5]:
# Usarlo para la suma 
N = particles
C = test_visual_list
x = rand(length(test_visual_list))*2 .-1
# A = reduce(kron, [Sigma[C[1][i]] for i in eachindex(C[1])])


UndefVarError: UndefVarError: `particles` not defined in `Main`
Suggestion: check for spelling errors or missing imports.

In [6]:
H = zeros(ComplexF64,2^N,2^N)
for k in 1:length(test_visual_list)
    H += x[k]*reduce(kron, [Sigma[C[k][i]] for i in eachindex(C[1])])
end
H 

UndefVarError: UndefVarError: `test_visual_list` not defined in `Main`
Suggestion: check for spelling errors or missing imports.

In [7]:
H = zeros(ComplexF64,2^N,2^N)
for k in 1:length(test_visual_list)
    H += x[k]*kron([Sigma[C[k][i]] for i in eachindex(C[1])]...)
end
H 

# Hay que guardar las A's
# Buscar el mejor formato para guardar matrices en Julia 

UndefVarError: UndefVarError: `test_visual_list` not defined in `Main`
Suggestion: check for spelling errors or missing imports.

$\{A_i\}$ deben ser operadores fijos lo que varían son 1000 datos distintos del conjunto de $\{c_i\}$ y tomar la mitad inferior de $\{\ket{\psi_n\}}$ ¿Qué tanto podemos reducir los estados y que nos siga dando una buena aproximación? 

### Almacenar todos los operadores locales A 

In [8]:
#particles=3
#k=3
#list=[0:3 for _ in 1:k]
#test_visual_list2 = []
#for place in 1:particles-k+1
#for i in Base.product(list...)
#    total_list=zeros(particles)
#    total_list[place:place+k-1]= i|>collect
#    print(total_list)
#    push!(test_visual_list,total_list)
#    print("\n")
#end
#end

In [9]:
particles=3
k=2
list=[0:3 for _ in 1:k]
test_visual_list = []
place= 2
for i in Base.product(list...)
    total_list=zeros(particles)
    total_list[place:place+k-1]= i|>collect
    if sum(total_list) != 0
        ##print(total_list)
        push!(test_visual_list,total_list)
    end
   # print("\n")
end
test_visual_list

15-element Vector{Any}:
 [0.0, 1.0, 0.0]
 [0.0, 2.0, 0.0]
 [0.0, 3.0, 0.0]
 [0.0, 0.0, 1.0]
 [0.0, 1.0, 1.0]
 [0.0, 2.0, 1.0]
 [0.0, 3.0, 1.0]
 [0.0, 0.0, 2.0]
 [0.0, 1.0, 2.0]
 [0.0, 2.0, 2.0]
 [0.0, 3.0, 2.0]
 [0.0, 0.0, 3.0]
 [0.0, 1.0, 3.0]
 [0.0, 2.0, 3.0]
 [0.0, 3.0, 3.0]

In [10]:
sum(test_visual_list[6])

3.0

In [11]:
particles = 3 
place = 1

k=2
list=[0:3 for _ in 1:k]
test_visual_list = []

for i in Base.product(list...)
    total_list=zeros(particles)
    total_list[place:place+k-1]= i|>collect
    if sum(total_list) != 0
        ##print(total_list)
        push!(test_visual_list,total_list)
    end
   # print("\n")
end

ArrayA1 = []
for i in 1:length(test_visual_list)
    if test_visual_list[i][place] != test_visual_list[i][place+1] && sum(test_visual_list[i]) != 0
        push!(ArrayA1,test_visual_list[i])
    end
end
ArrayA1

12-element Vector{Any}:
 [1.0, 0.0, 0.0]
 [2.0, 0.0, 0.0]
 [3.0, 0.0, 0.0]
 [0.0, 1.0, 0.0]
 [2.0, 1.0, 0.0]
 [3.0, 1.0, 0.0]
 [0.0, 2.0, 0.0]
 [1.0, 2.0, 0.0]
 [3.0, 2.0, 0.0]
 [0.0, 3.0, 0.0]
 [1.0, 3.0, 0.0]
 [2.0, 3.0, 0.0]

In [12]:
particles = 3 
place = 2

k=2
list=[0:3 for _ in 1:k]
test_visual_list = []

for i in Base.product(list...)
    total_list=zeros(particles)
    total_list[place:place+k-1]= i|>collect
    if sum(total_list) != 0
        ##print(total_list)
        push!(test_visual_list,total_list)
    end
   # print("\n")
end

ArrayA2 = []
for i in 1:length(test_visual_list)
    if test_visual_list[i][place] != test_visual_list[i][place+1] && sum(test_visual_list[i]) != 0
        push!(ArrayA2,test_visual_list[i])
    end
end
ArrayA2

12-element Vector{Any}:
 [0.0, 1.0, 0.0]
 [0.0, 2.0, 0.0]
 [0.0, 3.0, 0.0]
 [0.0, 0.0, 1.0]
 [0.0, 2.0, 1.0]
 [0.0, 3.0, 1.0]
 [0.0, 0.0, 2.0]
 [0.0, 1.0, 2.0]
 [0.0, 3.0, 2.0]
 [0.0, 0.0, 3.0]
 [0.0, 1.0, 3.0]
 [0.0, 2.0, 3.0]

In [13]:
ArrayA1

12-element Vector{Any}:
 [1.0, 0.0, 0.0]
 [2.0, 0.0, 0.0]
 [3.0, 0.0, 0.0]
 [0.0, 1.0, 0.0]
 [2.0, 1.0, 0.0]
 [3.0, 1.0, 0.0]
 [0.0, 2.0, 0.0]
 [1.0, 2.0, 0.0]
 [3.0, 2.0, 0.0]
 [0.0, 3.0, 0.0]
 [1.0, 3.0, 0.0]
 [2.0, 3.0, 0.0]

In [14]:
ArrayA2

xaleat = rand(length(ArrayA1))*2 .-1
xaleat2 = rand(length(ArrayA2))*2 .-1

12-element Vector{Float64}:
 -0.6278167348552297
 -0.9505527652468115
  0.7342073393504651
 -0.29669263172778204
 -0.6156978289797739
  0.21748179173538462
 -0.8123273735880077
  0.7833507172687502
  0.8972831821121596
  0.5602363586697345
  0.9250090982949004
 -0.5336742876982936

In [15]:

xaleat = rand(length(ArrayA1))*2 .-1
xaleat2 = rand(length(ArrayA2))*2 .-1

A1= zeros(2^particles,2^particles)

for k in 1:length(ArrayA1)
    A1 += xaleat[k]*kron([Sigma[ArrayA1[k][i]] for i in eachindex(ArrayA1[1])]...)
end

A2= zeros(2^particles,2^particles)

for k in 1:length(ArrayA2)
    A2 += xaleat2[k]*kron([Sigma[ArrayA2[k][i]] for i in eachindex(ArrayA2[1])]...)
end

In [16]:
A1

8×8 Matrix{ComplexF64}:
 -0.403747+0.0im             0.0+0.0im       …        0.0+0.0im
       0.0+0.0im       -0.403747+0.0im                0.0-0.132072im
  0.180354+0.178482im        0.0+0.0im                0.0+0.0im
       0.0+0.0im        0.180354+0.178482im      0.689805-0.67131im
  0.873035+1.09781im         0.0+0.0im                0.0+0.0im
       0.0+0.0im        0.873035+1.09781im   …  -0.583302-0.813574im
       0.0+0.132072im        0.0+0.0im                0.0+0.0im
       0.0+0.0im             0.0+0.132072im      0.403747+0.0im

In [17]:
A2

8×8 Matrix{ComplexF64}:
 0.338688+0.0im       -1.52055+1.69724im   …        0.0+0.0im
 -1.52055-1.69724im    -1.2476+0.0im                0.0+0.0im
 0.518318+0.417231im       0.0-1.04327im            0.0+0.0im
      0.0+0.531777im   1.27747+0.382587im           0.0+0.0im
      0.0+0.0im            0.0+0.0im                0.0-0.531777im
      0.0+0.0im            0.0+0.0im       …    1.27747-0.382587im
      0.0+0.0im            0.0+0.0im           0.428638-0.187043im
      0.0+0.0im            0.0+0.0im          -0.338688+0.0im

Ya tengo dos operadores locales para el caso de 3 partículas, será un problema generalizar, porque lo tendré que hacer a mano pues no veo una forma buena de hacer los Arrays, tal vez deba ver cómo hacerlo en diccionario...

$H = \sum_i C_i A_i$, aquí es donde queremos generar 1000 pares de elementos C1 y C2 para formar distintos Hamiltonianos y almacenarlos 

Necesito los promedios también de A1 y A2 con los vectores propios de H, haremos una prueba para un sólo valor 

In [18]:
c = rand(1000,2)*2 .-1 # sería conveniente generar una matriz de n x 2 

1000×2 Matrix{Float64}:
  0.702941   -0.0811975
  0.226521   -0.900449
  0.900058    0.615457
  0.526728    0.734495
 -0.240935   -0.115632
  0.648733   -0.561084
  0.0682775   0.483745
  0.0647125   0.320942
 -0.494282    0.800219
 -0.680715   -0.661018
  ⋮          
  0.157262   -0.0512525
 -0.155957    0.297345
 -0.955586   -0.725207
  0.659857   -0.224709
 -0.0277248  -0.0878034
 -0.24964    -0.29693
 -0.118488    0.944915
 -0.423976   -0.410764
 -0.266744   -0.371982

In [19]:
Hnew = c[1,1]A1 + c[1,2]A2 # Recordemos quiero almacenar ai y ci, ai son promedios de los operadores y ci son simplemente números aleatorios uniformes entre [-1.1]
vecs = eigen(Hnew).vectors
advecs = adjoint(vecs)

# NADA MÁS QUEREMOS USAR LA PRIMER MITAD DE LOS VALORES ESPERADOS 
# ¿Cómo entrenar la red? 
# ¿Cuál es el formato que espera para los datos de entrada y salida? El resto se tiene que automatizar 
# Que reciba los valores esperados, pero para entrenarlo, la idea es que tome varios conjuntos de valores esperados y para cada uno de ellos valorar la red para definir 
# la función que va a minimizar. 
# Lux   (y SciML)
# SimpleChains 

8×8 adjoint(::Matrix{ComplexF64}) with eltype ComplexF64:
  -0.309196-0.267404im      0.233905+0.00709078im  …  -0.180543+0.0im
   0.116248+0.117142im      0.370109+0.0536418im      -0.351826+0.0im
  -0.380979-0.533859im      0.352202-0.0413191im       0.236636-0.0im
   0.197868+0.320751im      0.672238-0.0271136im       0.363234-0.0im
   0.058921+0.00363816im   -0.045786+0.0256266im      -0.112963+0.0im
 -0.0459305+0.0679404im   -0.0236179-0.00996117im  …    0.71988-0.0im
  -0.385396+0.00465571im     0.16668-0.176223im       -0.247704+0.0im
  -0.208152-0.177158im     -0.405135+0.0246085im       0.251677+0.0im

In [20]:
ExpVal1 = zeros(ComplexF64,size(vecs)[1])
for i in 1:size(vecs)[1]
    ExpVal1[i] = transpose(advecs[i,:])*A1*vecs[:,i]
end

ExpVal2 = zeros(ComplexF64,size(vecs)[1])  # ExpVal2[1] = a21 = \bra{\phi1_}A_2\ket{\phi_1}
for i in 1:size(vecs)[1]
    ExpVal2[i] = transpose(advecs[i,:])*A2*vecs[:,i]
end
ExpVal1

8-element Vector{ComplexF64}:
  -2.475298921082622 - 1.3877787807814457e-17im
 -2.4460237744076934 + 5.551115123125783e-17im
 -0.5711637227666514 + 3.469446951953614e-18im
 -0.5760597829672653 - 1.0408340855860843e-17im
  1.2000091243898978 - 3.0791341698588326e-17im
  1.2151923647292129 - 3.209238430557093e-17im
  1.8495963440981267 + 8.326672684688674e-17im
  1.8037483680069948 + 5.551115123125783e-17im

In [21]:
c1 = Tuple(c[1,:])
dic = Dict()



Dict{Any, Any}()

In [22]:
c[1,:]

2-element Vector{Float64}:
  0.7029407006359798
 -0.08119753444801514

In [23]:
dic[c1] = [ExpVal1,ExpVal2]

2-element Vector{Vector{ComplexF64}}:
 [-2.475298921082622 - 1.3877787807814457e-17im, -2.4460237744076934 + 5.551115123125783e-17im, -0.5711637227666514 + 3.469446951953614e-18im, -0.5760597829672653 - 1.0408340855860843e-17im, 1.2000091243898978 - 3.0791341698588326e-17im, 1.2151923647292129 - 3.209238430557093e-17im, 1.8495963440981267 + 8.326672684688674e-17im, 1.8037483680069948 + 5.551115123125783e-17im]
 [1.234127037256566 + 4.163336342344337e-17im, -0.30495541827930644 + 8.326672684688674e-17im, 1.3521994210856594 + 0.0im, -2.5353419565909587 + 1.3877787807814457e-16im, 1.3410596472710359 + 3.469446951953614e-17im, -0.48661173085304954 + 3.122502256758253e-17im, 1.5886029336329748 + 1.3877787807814457e-17im, -2.1890799335229234 - 1.3877787807814457e-16im]

In [24]:
dic[c1][1] #ExpVal1 

8-element Vector{ComplexF64}:
  -2.475298921082622 - 1.3877787807814457e-17im
 -2.4460237744076934 + 5.551115123125783e-17im
 -0.5711637227666514 + 3.469446951953614e-18im
 -0.5760597829672653 - 1.0408340855860843e-17im
  1.2000091243898978 - 3.0791341698588326e-17im
  1.2151923647292129 - 3.209238430557093e-17im
  1.8495963440981267 + 8.326672684688674e-17im
  1.8037483680069948 + 5.551115123125783e-17im

In [25]:
dic[c1][2] # ExpVal2

8-element Vector{ComplexF64}:
    1.234127037256566 + 4.163336342344337e-17im
 -0.30495541827930644 + 8.326672684688674e-17im
   1.3521994210856594 + 0.0im
  -2.5353419565909587 + 1.3877787807814457e-16im
   1.3410596472710359 + 3.469446951953614e-17im
 -0.48661173085304954 + 3.122502256758253e-17im
   1.5886029336329748 + 1.3877787807814457e-17im
  -2.1890799335229234 - 1.3877787807814457e-16im

In [26]:
c1

(0.7029407006359798, -0.08119753444801514)

In [27]:
dic[c1]

2-element Vector{Vector{ComplexF64}}:
 [-2.475298921082622 - 1.3877787807814457e-17im, -2.4460237744076934 + 5.551115123125783e-17im, -0.5711637227666514 + 3.469446951953614e-18im, -0.5760597829672653 - 1.0408340855860843e-17im, 1.2000091243898978 - 3.0791341698588326e-17im, 1.2151923647292129 - 3.209238430557093e-17im, 1.8495963440981267 + 8.326672684688674e-17im, 1.8037483680069948 + 5.551115123125783e-17im]
 [1.234127037256566 + 4.163336342344337e-17im, -0.30495541827930644 + 8.326672684688674e-17im, 1.3521994210856594 + 0.0im, -2.5353419565909587 + 1.3877787807814457e-16im, 1.3410596472710359 + 3.469446951953614e-17im, -0.48661173085304954 + 3.122502256758253e-17im, 1.5886029336329748 + 1.3877787807814457e-17im, -2.1890799335229234 - 1.3877787807814457e-16im]

In [28]:
dic2 = Dict()

Dict{Any, Any}()

In [29]:
dic2[1] = c1

(0.7029407006359798, -0.08119753444801514)

In [30]:
dic2[1]

(0.7029407006359798, -0.08119753444801514)

In [31]:
dic2

Dict{Any, Any} with 1 entry:
  1 => (0.702941, -0.0811975)

In [32]:
dic[dic2[1]]

2-element Vector{Vector{ComplexF64}}:
 [-2.475298921082622 - 1.3877787807814457e-17im, -2.4460237744076934 + 5.551115123125783e-17im, -0.5711637227666514 + 3.469446951953614e-18im, -0.5760597829672653 - 1.0408340855860843e-17im, 1.2000091243898978 - 3.0791341698588326e-17im, 1.2151923647292129 - 3.209238430557093e-17im, 1.8495963440981267 + 8.326672684688674e-17im, 1.8037483680069948 + 5.551115123125783e-17im]
 [1.234127037256566 + 4.163336342344337e-17im, -0.30495541827930644 + 8.326672684688674e-17im, 1.3521994210856594 + 0.0im, -2.5353419565909587 + 1.3877787807814457e-16im, 1.3410596472710359 + 3.469446951953614e-17im, -0.48661173085304954 + 3.122502256758253e-17im, 1.5886029336329748 + 1.3877787807814457e-17im, -2.1890799335229234 - 1.3877787807814457e-16im]

In [33]:
dic3 = Dict()
for i in 1:10
    dic3[i] = 2*i
end
dic3

Dict{Any, Any} with 10 entries:
  5  => 10
  4  => 8
  6  => 12
  7  => 14
  2  => 4
  10 => 20
  9  => 18
  8  => 16
  3  => 6
  1  => 2

In [34]:
dic3[7]

14

In [36]:
xaleatMat1 = rand(1000,length(ArrayA1)).*2 .-1
xaleatMat2 = rand(1000,length(ArrayA2)).*2 .-1

APrueba = zeros(2^particles,2^particles)
APrueba2 = ones(2^particles,2^particles)

dicPrueba = Dict()
dicPrueba[1] = APrueba
dicPrueba[2] = APrueba2
dicPrueba[1][:,:]
xaleatMat1[1,:]

12-element Vector{Float64}:
 -0.8563663292143644
  0.2790937473471846
 -0.8045060665709756
  0.06459042710646457
 -0.7912503351130944
 -0.9298393439797537
 -0.811192568792273
  0.8313169619449947
  0.5119287485476958
 -0.6635976819789138
 -0.302504840175855
  0.7660425190221705

In [37]:
# Construcción de las 1000 tuplas con dos constantes aleatorias para c1 y c2 para A1 y A2 respectivamente
Cdic = Dict()
for k in 1:1000
    Cdic[k] = Tuple(c[k,:])
end
Cdic[k]

# Construcción de los 1000 operadores locales (Aleatorios)

xaleatMat1 = rand(1000,length(ArrayA1)).*2 .-1
xaleatMat2 = rand(1000,length(ArrayA2)).*2 .-1

dicA1Total = Dict()

for i in 1:1000
    A1P = zeros(2^particles,2^particles)
    for k in 1:length(ArrayA1)
        A1P += xaleatMat1[i,k]*kron([Sigma[ArrayA1[k][i]] for i in eachindex(ArrayA1[1])]...)
    end
    dicA1Total[i] = A1P
end

dicA2Total = Dict()

for i in 1:1000
    A2P = zeros(2^particles,2^particles)
    for k in 1:length(ArrayA2)
        A2P += xaleatMat2[i,k]*kron([Sigma[ArrayA2[k][i]] for i in eachindex(ArrayA2[1])]...)
    end
    dicA2Total[i] = A2P
end

Cdic[k] # Cdic[k][1] y Cdic[k][2]

Hdic = Dict()

for i in 1:1000
    Hdic[i] = c[i,1]*dicA1Total[i] + c[i,2]*dicA2Total[i]
end
Hdic[152]

8×8 Matrix{ComplexF64}:
 -0.0125168+0.0im          0.225474+0.337571im   …        0.0+0.0im
   0.225474-0.337571im     -1.18234+0.0im                 0.0-0.0826616im
  0.0242451-0.100395im          0.0-0.30585im             0.0+0.0im
        0.0-0.356349im      1.50363-1.2635im          -0.4553+0.235967im
 -0.0393076-0.567271im          0.0+0.0im                 0.0+0.356349im
        0.0+0.0im        -0.0393076-0.567271im   …    1.36516+1.8485im
        0.0+0.0826616im         0.0+0.0im           -0.694698+1.40864im
        0.0+0.0im               0.0+0.0826616im     0.0125168+0.0im

In [38]:
# Tengo 1000 Hamiltonianos que serán los que supervisaran la red con respecto a los 1000 operadores A1 y A2, pero recordemos que sólo 
# nos interesa la mitad de los estados propios, entonces tendremos algo de la siguiente dimensión 

# 1000 x 1 x (2^N)/2 x 
# 1 x 2^N es un vector (1x8) en este ejemplo, pero queremos sólo tomar la primer mitad de valores esperados
# 1 x 4 

In [39]:
ExpVal1Dic = Dict()
ExpVal2Dic = Dict()

for k in 1:1000
    Hnew = Hdic[k]
    vecs = eigen(Hnew).vectors
    advecs = adjoint(vecs)

    ExpVal1 = zeros(ComplexF64, Int((size(vecs)[1])/2))
    for i in 1:Int((size(vecs)[1])/2)
        ExpVal1[i] = transpose(advecs[i,:])*A1*vecs[:,i]
    end

    ExpVal2 = zeros(ComplexF64,Int((size(vecs)[1])/2))  # ExpVal2[1] = a21 = \bra{\phi1_}A_2\ket{\phi_1}
    for i in 1:Int((size(vecs)[1])/2)
        ExpVal2[i] = transpose(advecs[i,:])*A2*vecs[:,i]
    end
    ExpVal1Dic[k] = ExpVal1
    ExpVal2Dic[k] = ExpVal2
end
ExpVal1Dic[1]
ExpVal2Dic[1]


4-element Vector{ComplexF64}:
   0.306804537998998 - 2.7755575615628914e-17im
  1.3761327653996478 - 2.7755575615628914e-17im
  0.5730750199448611 - 1.1102230246251565e-16im
 -0.5734169680709922 + 1.1102230246251565e-16im

In [40]:
ExpVals = Dict(k => (ExpVal1Dic[k], ExpVal2Dic[k]) for k in keys(ExpVal1Dic))

Dict{Int64, Tuple{Vector{ComplexF64}, Vector{ComplexF64}}} with 1000 entries:
  719 => ([0.306957-1.04083e-17im, 0.131352-3.46945e-18im, -0.624333+0.0im, 0.5…
  699 => ([-0.549115+1.04083e-17im, 0.102765-3.1225e-17im, -0.653398+6.93889e-1…
  831 => ([-0.446225+5.55112e-17im, 0.535345-6.93889e-18im, -0.854368-1.38778e-…
  319 => ([1.11294+1.38778e-17im, 1.16825-1.73472e-18im, 1.27867+5.55112e-17im,…
  687 => ([-1.14761-6.93889e-17im, -1.14492-5.55112e-17im, 0.397496+2.08167e-17…
  185 => ([-0.464362+1.38778e-17im, -0.0574175-2.08167e-17im, 0.42664+0.0im, -1…
  823 => ([-0.0205961+4.16334e-17im, 0.689578+7.28584e-17im, -0.235565-6.245e-1…
  420 => ([0.880854-3.46945e-17im, 0.999804-1.73472e-18im, -0.372101-6.93889e-1…
  525 => ([-0.671141-5.55112e-17im, 0.0806298+4.51028e-17im, 0.968732+0.0im, -0…
  365 => ([-0.994415+1.9082e-17im, -0.125695-2.08167e-17im, 0.598856+3.81639e-1…
  638 => ([0.964968-6.93889e-18im, -1.35244+6.245e-17im, 1.11708-5.55112e-17im,…
  263 => ([-0.491062+3.46945e-1

Se presenta en el diccionario ExpVals 

$\bra{\varphi_k} A_1\ket{\varphi_k}$ y despues $\bra{\varphi_k} A_2\ket{\varphi_k}$

$k = 1,2,3,4$

In [41]:

ExpVals  # (4x1, 4x1) x 1000  Se presenta primero A1 y luego A2

Dict{Int64, Tuple{Vector{ComplexF64}, Vector{ComplexF64}}} with 1000 entries:
  719 => ([0.306957-1.04083e-17im, 0.131352-3.46945e-18im, -0.624333+0.0im, 0.5…
  699 => ([-0.549115+1.04083e-17im, 0.102765-3.1225e-17im, -0.653398+6.93889e-1…
  831 => ([-0.446225+5.55112e-17im, 0.535345-6.93889e-18im, -0.854368-1.38778e-…
  319 => ([1.11294+1.38778e-17im, 1.16825-1.73472e-18im, 1.27867+5.55112e-17im,…
  687 => ([-1.14761-6.93889e-17im, -1.14492-5.55112e-17im, 0.397496+2.08167e-17…
  185 => ([-0.464362+1.38778e-17im, -0.0574175-2.08167e-17im, 0.42664+0.0im, -1…
  823 => ([-0.0205961+4.16334e-17im, 0.689578+7.28584e-17im, -0.235565-6.245e-1…
  420 => ([0.880854-3.46945e-17im, 0.999804-1.73472e-18im, -0.372101-6.93889e-1…
  525 => ([-0.671141-5.55112e-17im, 0.0806298+4.51028e-17im, 0.968732+0.0im, -0…
  365 => ([-0.994415+1.9082e-17im, -0.125695-2.08167e-17im, 0.598856+3.81639e-1…
  638 => ([0.964968-6.93889e-18im, -1.35244+6.245e-17im, 1.11708-5.55112e-17im,…
  263 => ([-0.491062+3.46945e-1

In [42]:
ExpVals[1][2] # ExpVal1

4-element Vector{ComplexF64}:
   0.306804537998998 - 2.7755575615628914e-17im
  1.3761327653996478 - 2.7755575615628914e-17im
  0.5730750199448611 - 1.1102230246251565e-16im
 -0.5734169680709922 + 1.1102230246251565e-16im

In [43]:
Hdic # (8x8) x 1000 son matrices 8x8 y 1000 matrices de esas 

Dict{Any, Any} with 1000 entries:
  719 => ComplexF64[-0.477366+0.0im -0.202274-0.280303im … 0.0-0.0277238im 0.0+…
  699 => ComplexF64[-0.664818+0.0im -0.741395-0.455627im … 0.0+0.040621im 0.0+0…
  831 => ComplexF64[-0.816351+0.0im -1.02921+0.463824im … 0.0+0.132454im 0.0+0.…
  319 => ComplexF64[1.5288+0.0im 0.0171748-0.12897im … 0.0+0.821126im 0.0+0.0im…
  687 => ComplexF64[-0.0709126-0.0im 0.011696-0.00415633im … -0.0+0.0565741im -…
  185 => ComplexF64[-0.136952+0.0im -0.401095-0.424048im … 0.0-0.472243im 0.0+0…
  823 => ComplexF64[-0.150054-0.0im -0.648058+0.804511im … -0.0-0.223933im -0.0…
  420 => ComplexF64[0.530778+0.0im -0.205523+0.18802im … 0.0+0.0102053im 0.0+0.…
  525 => ComplexF64[-0.053993+0.0im -0.0142616-0.51498im … 0.0+0.00289267im 0.0…
  365 => ComplexF64[0.538158+0.0im -0.656596+0.344093im … 0.0+1.38641im 0.0+0.0…
  638 => ComplexF64[-0.0834308+0.0im 0.116516+0.233668im … 0.0-0.00835572im 0.0…
  263 => ComplexF64[-0.555747+0.0im -0.23831-0.117419im … 0.0+1.12584im 0.0

In [44]:
ABD = collect(Hdic)

1000-element Vector{Pair{Any, Any}}:
 719 => ComplexF64[-0.4773664053462691 + 0.0im -0.2022737692294646 - 0.28030348827896373im … 0.0 - 0.027723806983742966im 0.0 + 0.0im; -0.2022737692294646 + 0.28030348827896373im -0.21105539221300706 + 0.0im … 0.0 + 0.0im 0.0 - 0.027723806983742966im; … ; 0.0 + 0.027723806983742966im 0.0 + 0.0im … 0.21105539221300706 + 0.0im 0.6200334107103069 + 0.1823230710261175im; 0.0 + 0.0im 0.0 + 0.027723806983742966im … 0.6200334107103069 - 0.1823230710261175im 0.4773664053462691 + 0.0im]
 699 => ComplexF64[-0.6648175513065251 + 0.0im -0.7413945262439549 - 0.45562650469282673im … 0.0 + 0.04062101064946968im 0.0 + 0.0im; -0.7413945262439549 + 0.45562650469282673im -0.6053651350531148 + 0.0im … 0.0 + 0.0im 0.0 + 0.04062101064946968im; … ; 0.0 - 0.04062101064946968im 0.0 + 0.0im … 0.6053651350531148 + 0.0im 0.4937582301876017 + 0.500717892117951im; 0.0 + 0.0im 0.0 - 0.04062101064946968im … 0.4937582301876017 - 0.500717892117951im 0.6648175513065251 + 0.0im]
 831 

## Acomodando los datos de forma conveniente para meterlos a la red neuronal
 

In [79]:
c = rand(2,1000)*2 .-1 # sería conveniente generar una matriz de n x 2 


2×1000 Matrix{Float64}:
 -0.250518  -0.617583   0.663949  0.637328  …  -0.456418  0.184208  0.733827
  0.79612    0.096935  -0.727507  0.382224     -0.980367  0.286178  0.699374

In [ ]:
xaleatMat1 = rand(1000,length(ArrayA1)).*2 .-1
xaleatMat2 = rand(1000,length(ArrayA2)).*2 .-1

In [89]:
A1P_list = []  # Un arreglo vacío para almacenar matrices
A2P_list = []

for i in 1:1000
    A1P = zeros(2^particles, 2^particles)
    for k in 1:length(ArrayA1)
        A1P += xaleatMat1[i, k] * kron([Sigma[ArrayA1[k][j]] for j in eachindex(ArrayA1[1])]...)
    end
    push!(A1P_list, A1P)  # Guardar la matriz en el arreglo
end

for i in 1:1000
    A2P = zeros(2^particles,2^particles)
    for k in 1:length(ArrayA2)
        A2P += xaleatMat2[i,k]*kron([Sigma[ArrayA2[k][i]] for i in eachindex(ArrayA2[1])]...)
    end
    push!(A2P_list, A2P)  # Guardar la matriz en el arreglo
end

8×8 Matrix{ComplexF64}:
 -1.01511+0.0im         0.535575+1.936im     …       0.0+0.0im
 0.535575-1.936im      0.0707852+0.0im               0.0+0.0im
 0.435362-0.31369im          0.0+0.275588im          0.0+0.0im
      0.0-0.0729558im    1.10541-0.495316im          0.0+0.0im
      0.0+0.0im              0.0+0.0im               0.0+0.0729558im
      0.0+0.0im              0.0+0.0im       …   1.10541+0.495316im
      0.0+0.0im              0.0+0.0im          -1.43805+0.00774819im
      0.0+0.0im              0.0+0.0im           1.01511+0.0im

In [ ]:
# Fijamos A1 y A2, no necesitaremos mucho, porque con cada A1 y A2 fijos podemos generar al menos 1000 Hamiltonianos distintos
# Recordemos que dependen únicamente de los coeficientes c1 y c2, que son aleatorios
A111 = A1P_list[1] 
A222 = A2P_list[1]


8×8 Matrix{ComplexF64}:
 -1.01511+0.0im         0.535575+1.936im     …       0.0+0.0im
 0.535575-1.936im      0.0707852+0.0im               0.0+0.0im
 0.435362-0.31369im          0.0+0.275588im          0.0+0.0im
      0.0-0.0729558im    1.10541-0.495316im          0.0+0.0im
      0.0+0.0im              0.0+0.0im               0.0+0.0729558im
      0.0+0.0im              0.0+0.0im       …   1.10541+0.495316im
      0.0+0.0im              0.0+0.0im          -1.43805+0.00774819im
      0.0+0.0im              0.0+0.0im           1.01511+0.0im

In [ ]:
# Formamos el Hamiltoniano con los primeros valores de c 
H12 = c[1,1]*A111 + c[2,1]*A222

8×8 Matrix{ComplexF64}:
 -0.906527+0.0im          0.426382+1.54129im   …        0.0+0.0im
  0.426382-1.54129im    -0.0420233+0.0im                0.0+0.148703im
  0.579348-0.370741im          0.0+0.219401im           0.0+0.0im
       0.0-0.0580816im     1.11279-0.515337im     -0.257039-0.152857im
  -0.16133-0.182026im          0.0+0.0im                0.0+0.0580816im
       0.0+0.0im          -0.16133-0.182026im  …    0.82262+0.426552im
       0.0-0.148703im          0.0+0.0im           -1.14486+0.00616849im
       0.0+0.0im               0.0-0.148703im      0.906527+0.0im

In [ ]:
# Tomamos los vectores propios 
vor  = eigen(H12).vectors
adjvor = adjoint(vor)

8-element Vector{ComplexF64}:
 -0.04401503962357482 + 0.5413410696775872im
   -0.422859359129555 - 0.12932056495421748im
 -0.03565787790628209 - 0.16300289892747735im
  0.15906626836620244 - 0.08160649461735148im
 -0.38797554429962805 + 0.33921466131749867im
 -0.18878450674363415 - 0.3660115653252706im
 -0.02968201783675059 - 0.07832703996485797im
  0.08639292039487942 + 0.0im

In [144]:
n = 1000
mat = Matrix{Float64}(undef, 8, n)  # Matriz vacía 8x1000 (no inicializada)
mat1a1 = zeros(2)
for k in 1 : n

    # Formamos el Hamiltoniano
    H12 = c[1,k]*A111 + c[2,k]*A222

    # Tomamos los vectores propios 

    vor  = eigen(H12).vectors
    adjvor = adjoint(vor)

    vor[:,1] # Este es el primer vector propio, los vectores propios con eigen se colocan en columnas 
    adjvor[1,:] # Este es el primer vector propio para la adjunta (Recordemos es un vector izquierdo [Fila])

    # Calculamos el valor esperado de la primera mitad de vectores propios

    ExpValA = zeros(ComplexF64, Int((size(vor)[1])/2))
    for i in 1:Int((size(vecs)[1])/2)
        ExpValA[i] = transpose(adjvor[i,:])*A111*vor[:,i]
    end

    ExpValB = zeros(ComplexF64,Int((size(vor)[1])/2))  # ExpVal2[1] = a21 = \bra{\phi1_}A_2\ket{\phi_1}
    for i in 1:Int((size(vecs)[1])/2)
        ExpValB[i] = transpose(adjvor[i,:])*A222*vor[:,i]
    end

    ValsA = real(ExpValA) # Nos interesa únicamente la parte real, la parte imaginaria suele ser error 
    ValsB = real(ExpValB)
    mat1a1[1] = ValsA[1]
    mat1a1[2] = ValsA[2]

    
    ValsCompleto = vcat(ValsA, ValsB) # Por último nuestro vector tendrá la forma de 8x1, para poder agregarlo al batch 
    mat[:,k]
end 

In [145]:
ValsCompleto = vcat(ValsA, ValsB)
mat1a1

2-element Vector{Float64}:
 -0.9508738818800113
 -1.4026541519250995

In [146]:
t1 = (c[:,1], mat1a1)

([-0.2505178151654952, 0.7961199701103854], [-0.9508738818800113, -1.4026541519250995])