In [1]:
using Plots
using LinearAlgebra
using LaTeXStrings

In [2]:
list = [1:3  for _ in 1:k]

UndefVarError: UndefVarError: `k` not defined in `Main`
Suggestion: check for spelling errors or missing imports.

In [3]:
N = 3 # number of qubits
d = 2^N # dimension of the Hilbert space

sigmax = [0 1; 1 0]
sigmay = [0 -im; im 0]
sigmaz = [1 0; 0 -1]
id= I(2)


Sigma = Dict(0 => id, 1 => sigmax, 2 => sigmay, 3 => sigmaz) #Diccionario para llamar a las matrices de Pauli
Sigma[1]

2×2 Matrix{Int64}:
 0  1
 1  0

### a |> f = f(a)

In [4]:
particles= 10
k=3
list=[1:3 for _ in 1:k]
test_visual_list = []
for place in 1:particles-k+1
    for i in Base.product(list...)
        total_list=zeros(particles)
        total_list[place:place+k-1]= i|>collect
        print(total_list)
        push!(test_visual_list,total_list)
        print("\n")
    end
end

[1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[2.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[3.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[1.0, 2.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[2.0, 2.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[3.0, 2.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[1.0, 3.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[2.0, 3.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[3.0, 3.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[1.0, 1.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[2.0, 1.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[3.0, 1.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[1.0, 2.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[2.0, 2.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[3.0, 2.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[1.0, 3.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[2.0, 3.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[3.0, 3.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[1.0, 1.0, 3.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[2.0, 1.0, 3.0, 0.0, 0.0, 0.0, 

In [5]:
# Usarlo para la suma 
N = particles
C = test_visual_list
x = rand(length(test_visual_list))*2 .-1
# A = reduce(kron, [Sigma[C[1][i]] for i in eachindex(C[1])])


216-element Vector{Float64}:
 -0.10992228074771604
 -0.7316048235231523
  0.6277835648172656
  0.2705829343091444
  0.03153758787103911
  0.6408925962946268
  0.2838069207367431
  0.7589322792290667
  0.025411063600895067
 -0.16269363457143826
  ⋮
  0.04565761728862272
  0.624643364368896
 -0.7218590458436762
  0.45692257822807525
  0.03604306036001259
  0.6044686251426725
 -0.7598571308609985
  0.2562085237392313
  0.8055210612100028

In [ ]:
H = zeros(ComplexF64,2^N,2^N)
for k in 1:length(test_visual_list)
    H += x[k]*reduce(kron, [Sigma[C[k][i]] for i in eachindex(C[1])])
end
H 

  0.284790 seconds (978.91 k allocations: 84.514 MiB, 2.58% gc time, 94.92% compilation time)
  0.229414 seconds (856.48 k allocations: 97.143 MiB, 3.00% gc time, 92.66% compilation time)
  0.010616 seconds (61 allocations: 34.668 MiB, 40.79% gc time)
  0.042897 seconds (98.79 k allocations: 58.298 MiB, 6.63% gc time, 78.49% compilation time)
  0.043265 seconds (29.22 k allocations: 54.758 MiB, 19.96% gc time, 33.97% compilation time)
  0.023784 seconds (64 allocations: 53.335 MiB, 54.12% gc time)
  0.091588 seconds (61 allocations: 34.668 MiB, 94.84% gc time)
  0.009196 seconds (64 allocations: 53.335 MiB, 13.53% gc time)
  0.004009 seconds (61 allocations: 34.668 MiB)
  0.010496 seconds (64 allocations: 53.335 MiB, 32.50% gc time)
  0.007548 seconds (64 allocations: 53.335 MiB, 10.62% gc time)
  0.023104 seconds (64 allocations: 53.335 MiB, 62.95% gc time)
  0.093283 seconds (64 allocations: 53.335 MiB, 93.09% gc time)
  0.030691 seconds (65.19 k allocations: 56.640 MiB, 10.63% gc ti

1024×1024 Matrix{ComplexF64}:
  -1.85734+0.0im         0.350591-0.110065im   …        0.0+0.0im
  0.350591+0.110065im    -3.46838+0.0im                 0.0+0.0im
  -1.08096+1.27211im      1.46881+1.35588im             0.0+0.0im
 -0.477103-0.0455295im   0.362754+0.0631736im           0.0+0.0im
  0.255555+1.39949im     0.238012-0.137416im            0.0+0.0im
  0.675206-1.25929im      1.77527+0.887075im   …        0.0+0.0im
  0.245787+2.59834im       1.4109-2.52496im             0.0+0.0im
   1.39558+0.310314im    0.226558+0.435209im            0.0+0.0im
 -0.130892-0.436828im         0.0+0.0im                 0.0+0.0im
       0.0+0.0im        -0.130892-0.436828im            0.0+0.0im
          ⋮                                    ⋱  
       0.0+0.0im              0.0+0.0im        …  -0.130892+0.436828im
       0.0+0.0im              0.0+0.0im             1.39558-0.310314im
       0.0+0.0im              0.0+0.0im           -0.245787+2.59834im
       0.0+0.0im              0.0+0.0im        

In [13]:
H = zeros(ComplexF64,2^N,2^N)
for k in 1:length(test_visual_list)
    H += x[k]*kron([Sigma[C[k][i]] for i in eachindex(C[1])]...)
end
H 

# Hay que guardar las A's
# Buscar el mejor formato para guardar matrices en Julia 

1024×1024 Matrix{ComplexF64}:
  -1.85734+0.0im         0.350591-0.110065im   …        0.0+0.0im
  0.350591+0.110065im    -3.46838+0.0im                 0.0+0.0im
  -1.08096+1.27211im      1.46881+1.35588im             0.0+0.0im
 -0.477103-0.0455295im   0.362754+0.0631736im           0.0+0.0im
  0.255555+1.39949im     0.238012-0.137416im            0.0+0.0im
  0.675206-1.25929im      1.77527+0.887075im   …        0.0+0.0im
  0.245787+2.59834im       1.4109-2.52496im             0.0+0.0im
   1.39558+0.310314im    0.226558+0.435209im            0.0+0.0im
 -0.130892-0.436828im         0.0+0.0im                 0.0+0.0im
       0.0+0.0im        -0.130892-0.436828im            0.0+0.0im
          ⋮                                    ⋱  
       0.0+0.0im              0.0+0.0im        …  -0.130892+0.436828im
       0.0+0.0im              0.0+0.0im             1.39558-0.310314im
       0.0+0.0im              0.0+0.0im           -0.245787+2.59834im
       0.0+0.0im              0.0+0.0im        

$\{A_i\}$ deben ser operadores fijos lo que varían son 1000 datos distintos del conjunto de $\{c_i\}$ y tomar la mitad inferior de $\{\ket{\psi_n\}}$ ¿Qué tanto podemos reducir los estados y que nos siga dando una buena aproximación? 