In [2]:
using Plots
using LinearAlgebra
using LaTeXStrings

In [3]:
list = [1:3  for _ in 1:k]

3-element Vector{UnitRange{Int64}}:
 1:3
 1:3
 1:3

In [4]:
N = 3 # number of qubits
d = 2^N # dimension of the Hilbert space

sigmax = [0 1; 1 0]
sigmay = [0 -im; im 0]
sigmaz = [1 0; 0 -1]
id= I(2)


Sigma = Dict(0 => id, 1 => sigmax, 2 => sigmay, 3 => sigmaz) #Diccionario para llamar a las matrices de Pauli
Sigma[1]

2×2 Matrix{Int64}:
 0  1
 1  0

### a |> f = f(a)

In [5]:
particles= 10
k=3
list=[1:3 for _ in 1:k]
test_visual_list = []
for place in 1:particles-k+1
    for i in Base.product(list...)
        total_list=zeros(particles)
        total_list[place:place+k-1]= i|>collect
        print(total_list)
        push!(test_visual_list,total_list)
        print("\n")
    end
end

[1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[2.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[3.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[1.0, 2.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[2.0, 2.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[3.0, 2.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[1.0, 3.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[2.0, 3.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[3.0, 3.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[1.0, 1.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[2.0, 1.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[3.0, 1.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[1.0, 2.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[2.0, 2.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[3.0, 2.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[1.0, 3.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[2.0, 3.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[3.0, 3.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[1.0, 1.0, 3.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[2.0, 1.0, 3.0, 0.0, 0.0, 0.0, 

In [6]:
# Usarlo para la suma 
N = particles
C = test_visual_list
x = rand(length(test_visual_list))*2 .-1
# A = reduce(kron, [Sigma[C[1][i]] for i in eachindex(C[1])])


216-element Vector{Float64}:
 -0.8009886198993579
 -0.3067439939570349
  0.5462772343216113
 -0.7875837407641584
 -0.8799721893594246
  0.6697140220344864
  0.6407175522216744
 -0.7874738744705578
  0.3299506656758455
  0.01141822209464416
  ⋮
  0.7905923864059763
 -0.22708765818366805
 -0.6535129281027541
  0.23003184064863613
 -0.9498709792875899
  0.6107606242996557
 -0.04974216410471932
  0.7310063567182645
 -0.9404894961321053

In [7]:
H = zeros(ComplexF64,2^N,2^N)
for k in 1:length(test_visual_list)
    H += x[k]*reduce(kron, [Sigma[C[k][i]] for i in eachindex(C[1])])
end
H 

1024×1024 Matrix{ComplexF64}:
   -3.04082+0.0im        -0.0861179+0.886226im  …         0.0+0.0im
 -0.0861179-0.886226im     -1.15984+0.0im                 0.0+0.0im
  -0.296708-0.0553172im    0.237618-0.398573im            0.0+0.0im
    -1.7091-0.901986im      1.01032-1.27684im             0.0+0.0im
    0.35107+2.2049im      -0.238663-1.33887im             0.0+0.0im
   -1.35797+0.369243im     0.450554+0.74289im   …         0.0+0.0im
    1.88169-0.60402im      -0.69112-0.672069im            0.0+0.0im
   0.269461+0.149112im     -1.59924-0.609908im            0.0+0.0im
    1.30532-0.197053im          0.0+0.0im                 0.0+0.0im
        0.0+0.0im           1.30532-0.197053im            0.0+0.0im
           ⋮                                    ⋱  
        0.0+0.0im               0.0+0.0im       …     1.30532+0.197053im
        0.0+0.0im               0.0+0.0im            0.269461-0.149112im
        0.0+0.0im               0.0+0.0im            -1.88169-0.60402im
        0.0+0.0im   

In [8]:
H = zeros(ComplexF64,2^N,2^N)
for k in 1:length(test_visual_list)
    H += x[k]*kron([Sigma[C[k][i]] for i in eachindex(C[1])]...)
end
H 

# Hay que guardar las A's
# Buscar el mejor formato para guardar matrices en Julia 

1024×1024 Matrix{ComplexF64}:
   -3.04082+0.0im        -0.0861179+0.886226im  …         0.0+0.0im
 -0.0861179-0.886226im     -1.15984+0.0im                 0.0+0.0im
  -0.296708-0.0553172im    0.237618-0.398573im            0.0+0.0im
    -1.7091-0.901986im      1.01032-1.27684im             0.0+0.0im
    0.35107+2.2049im      -0.238663-1.33887im             0.0+0.0im
   -1.35797+0.369243im     0.450554+0.74289im   …         0.0+0.0im
    1.88169-0.60402im      -0.69112-0.672069im            0.0+0.0im
   0.269461+0.149112im     -1.59924-0.609908im            0.0+0.0im
    1.30532-0.197053im          0.0+0.0im                 0.0+0.0im
        0.0+0.0im           1.30532-0.197053im            0.0+0.0im
           ⋮                                    ⋱  
        0.0+0.0im               0.0+0.0im       …     1.30532+0.197053im
        0.0+0.0im               0.0+0.0im            0.269461-0.149112im
        0.0+0.0im               0.0+0.0im            -1.88169-0.60402im
        0.0+0.0im   

$\{A_i\}$ deben ser operadores fijos lo que varían son 1000 datos distintos del conjunto de $\{c_i\}$ y tomar la mitad inferior de $\{\ket{\psi_n\}}$ ¿Qué tanto podemos reducir los estados y que nos siga dando una buena aproximación? 

### Almacenar todos los operadores locales A 

In [22]:
particles=3
k=3
list=[0:3 for _ in 1:k]
test_visual_list = []
for place in 1:particles-k+1
for i in Base.product(list...)
    total_list=zeros(particles)
    total_list[place:place+k-1]= i|>collect
    print(total_list)
    push!(test_visual_list,total_list)
    print("\n")
end
end

[0.0, 0.0, 0.0]
[1.0, 0.0, 0.0]
[2.0, 0.0, 0.0]
[3.0, 0.0, 0.0]
[0.0, 1.0, 0.0]
[1.0, 1.0, 0.0]
[2.0, 1.0, 0.0]
[3.0, 1.0, 0.0]
[0.0, 2.0, 0.0]
[1.0, 2.0, 0.0]
[2.0, 2.0, 0.0]
[3.0, 2.0, 0.0]
[0.0, 3.0, 0.0]
[1.0, 3.0, 0.0]
[2.0, 3.0, 0.0]
[3.0, 3.0, 0.0]
[0.0, 0.0, 1.0]
[1.0, 0.0, 1.0]
[2.0, 0.0, 1.0]
[3.0, 0.0, 1.0]
[0.0, 1.0, 1.0]
[1.0, 1.0, 1.0]
[2.0, 1.0, 1.0]
[3.0, 1.0, 1.0]
[0.0, 2.0, 1.0]
[1.0, 2.0, 1.0]
[2.0, 2.0, 1.0]
[3.0, 2.0, 1.0]
[0.0, 3.0, 1.0]
[1.0, 3.0, 1.0]
[2.0, 3.0, 1.0]
[3.0, 3.0, 1.0]
[0.0, 0.0, 2.0]
[1.0, 0.0, 2.0]
[2.0, 0.0, 2.0]
[3.0, 0.0, 2.0]
[0.0, 1.0, 2.0]
[1.0, 1.0, 2.0]
[2.0, 1.0, 2.0]
[3.0, 1.0, 2.0]
[0.0, 2.0, 2.0]
[1.0, 2.0, 2.0]
[2.0, 2.0, 2.0]
[3.0, 2.0, 2.0]
[0.0, 3.0, 2.0]
[1.0, 3.0, 2.0]
[2.0, 3.0, 2.0]
[3.0, 3.0, 2.0]
[0.0, 0.0, 3.0]
[1.0, 0.0, 3.0]
[2.0, 0.0, 3.0]
[3.0, 0.0, 3.0]
[0.0, 1.0, 3.0]
[1.0, 1.0, 3.0]
[2.0, 1.0, 3.0]
[3.0, 1.0, 3.0]
[0.0, 2.0, 3.0]
[1.0, 2.0, 3.0]
[2.0, 2.0, 3.0]
[3.0, 2.0, 3.0]
[0.0, 3.0, 3.0]
[1.0, 3.0, 3.0]
[2.0, 3.

In [33]:
particles=3
k=2
list=[0:3 for _ in 1:k]
test_visual_list = []
place=1
for i in Base.product(list...)
    total_list=zeros(particles)
    total_list[place:place+k-1]= i|>collect
    if sum(total_list) != 0
        print(total_list)
        push!(test_visual_list,total_list)
    end
    print("\n")
end


[1.0, 0.0, 0.0]
[2.0, 0.0, 0.0]
[3.0, 0.0, 0.0]
[0.0, 1.0, 0.0]
[1.0, 1.0, 0.0]
[2.0, 1.0, 0.0]
[3.0, 1.0, 0.0]
[0.0, 2.0, 0.0]
[1.0, 2.0, 0.0]
[2.0, 2.0, 0.0]
[3.0, 2.0, 0.0]
[0.0, 3.0, 0.0]
[1.0, 3.0, 0.0]
[2.0, 3.0, 0.0]
[3.0, 3.0, 0.0]
