In [1]:
using Plots
using LinearAlgebra
using LaTeXStrings

In [2]:
list = [1:3  for _ in 1:k]

UndefVarError: UndefVarError: `k` not defined in `Main`
Suggestion: check for spelling errors or missing imports.

In [3]:
N = 3 # number of qubits
d = 2^N # dimension of the Hilbert space

sigmax = [0 1; 1 0]
sigmay = [0 -im; im 0]
sigmaz = [1 0; 0 -1]
id= I(2)


Sigma = Dict(0 => id, 1 => sigmax, 2 => sigmay, 3 => sigmaz) #Diccionario para llamar a las matrices de Pauli
Sigma[1]

2×2 Matrix{Int64}:
 0  1
 1  0

### a |> f = f(a)

In [4]:
particles= 10
k=3
list=[1:3 for _ in 1:k]
test_visual_list = []
for place in 1:particles-k+1
    for i in Base.product(list...)
        total_list=zeros(particles)
        total_list[place:place+k-1]= i|>collect
        print(total_list)
        push!(test_visual_list,total_list)
        print("\n")
    end
end

[1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[2.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[3.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[1.0, 2.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[2.0, 2.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[3.0, 2.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[1.0, 3.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[2.0, 3.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[3.0, 3.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[1.0, 1.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[2.0, 1.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[3.0, 1.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[1.0, 2.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[2.0, 2.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[3.0, 2.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[1.0, 3.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[2.0, 3.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[3.0, 3.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[1.0, 1.0, 3.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[2.0, 1.0, 3.0, 0.0, 0.0, 0.0, 

In [5]:
# Usarlo para la suma 
N = particles
C = test_visual_list
x = rand(length(test_visual_list))*2 .-1
# A = reduce(kron, [Sigma[C[1][i]] for i in eachindex(C[1])])


216-element Vector{Float64}:
  0.5243477609930509
 -0.48321474898041106
 -0.634125222430554
  0.3106743640549181
 -0.6928319520010311
 -0.824806079891524
 -0.7771748956420033
  0.4435565647131472
 -0.06095403965195789
  0.0010145727043033848
  ⋮
  0.4401935026839574
 -0.736847106915544
 -0.719093460850071
  0.31223261113003975
 -0.6282012977694718
 -0.6247001196078517
 -0.1205888418045229
  0.9341468504824377
  0.8679762575506695

In [6]:
H = zeros(ComplexF64,2^N,2^N)
for k in 1:length(test_visual_list)
    H += x[k]*reduce(kron, [Sigma[C[k][i]] for i in eachindex(C[1])])
end
H 

1024×1024 Matrix{ComplexF64}:
     1.1636+0.0im         0.437766+0.133028im   …        0.0+0.0im
   0.437766-0.133028im   -0.572351+0.0im                 0.0+0.0im
   -1.13607-1.57474im      1.79426+0.284687im            0.0+0.0im
 -0.0100686-1.05267im     0.302115-0.325343im            0.0+0.0im
   0.354397+0.999312im   0.0462627+0.143524im            0.0+0.0im
    1.58864+0.294883im    0.595574-0.868981im   …        0.0+0.0im
    1.10551+0.779326im     2.59243+0.146546im            0.0+0.0im
   0.324576+0.230181im    -1.03128+1.62855im             0.0+0.0im
   -1.51236-0.0977733im        0.0+0.0im                 0.0+0.0im
        0.0+0.0im         -1.51236-0.0977733im           0.0+0.0im
           ⋮                                    ⋱  
        0.0+0.0im              0.0+0.0im        …   -1.51236+0.0977733im
        0.0+0.0im              0.0+0.0im            0.324576-0.230181im
        0.0+0.0im              0.0+0.0im            -1.10551+0.779326im
        0.0+0.0im              

In [7]:
H = zeros(ComplexF64,2^N,2^N)
for k in 1:length(test_visual_list)
    H += x[k]*kron([Sigma[C[k][i]] for i in eachindex(C[1])]...)
end
H 

# Hay que guardar las A's
# Buscar el mejor formato para guardar matrices en Julia 

1024×1024 Matrix{ComplexF64}:
     1.1636+0.0im         0.437766+0.133028im   …        0.0+0.0im
   0.437766-0.133028im   -0.572351+0.0im                 0.0+0.0im
   -1.13607-1.57474im      1.79426+0.284687im            0.0+0.0im
 -0.0100686-1.05267im     0.302115-0.325343im            0.0+0.0im
   0.354397+0.999312im   0.0462627+0.143524im            0.0+0.0im
    1.58864+0.294883im    0.595574-0.868981im   …        0.0+0.0im
    1.10551+0.779326im     2.59243+0.146546im            0.0+0.0im
   0.324576+0.230181im    -1.03128+1.62855im             0.0+0.0im
   -1.51236-0.0977733im        0.0+0.0im                 0.0+0.0im
        0.0+0.0im         -1.51236-0.0977733im           0.0+0.0im
           ⋮                                    ⋱  
        0.0+0.0im              0.0+0.0im        …   -1.51236+0.0977733im
        0.0+0.0im              0.0+0.0im            0.324576-0.230181im
        0.0+0.0im              0.0+0.0im            -1.10551+0.779326im
        0.0+0.0im              

$\{A_i\}$ deben ser operadores fijos lo que varían son 1000 datos distintos del conjunto de $\{c_i\}$ y tomar la mitad inferior de $\{\ket{\psi_n\}}$ ¿Qué tanto podemos reducir los estados y que nos siga dando una buena aproximación? 