In [1]:
using Plots
using LinearAlgebra
using LaTeXStrings
using HDF5

No supervisado

Familias de Hamiltonianos y se generen valores esperados
y si se usa clustering y se agrupa con los datos e identificar los que se parecen 
y si se puede identificar las familias de Hamiltonianos

normalización de batches 
y dropout (Para eliminar aleatoriamente)

In [43]:
k=3
list = [1:3  for _ in 1:k]

3-element Vector{UnitRange{Int64}}:
 1:3
 1:3
 1:3

In [3]:
N = 3 # number of qubits
d = 2^N # dimension of the Hilbert space

sigmax = [0 1; 1 0]
sigmay = [0 -im; im 0]
sigmaz = [1 0; 0 -1]
id= [1 0; 0 1] # Matriz identidad


Sigma = Dict(0 => id, 1 => sigmax, 2 => sigmay, 3 => sigmaz) #Diccionario para llamar a las matrices de Pauli
Sigma[1]

2×2 Matrix{Int64}:
 0  1
 1  0

### a |> f = f(a)

In [4]:
#particles= 10
#k=3
#list=[1:3 for _ in 1:k]
#test_visual_list = []
#for place in 1:particles-k+1
#    for i in Base.product(list...)
#        total_list=zeros(particles)
#        total_list[place:place+k-1]= i|>collect
#        print(total_list)
#        push!(test_visual_list,total_list)
#        print("\n")
#    end
#end

In [5]:
# Usarlo para la suma 
N = particles
C = test_visual_list
x = rand(length(test_visual_list))*2 .-1
# A = reduce(kron, [Sigma[C[1][i]] for i in eachindex(C[1])])


UndefVarError: UndefVarError: `particles` not defined in `Main`
Suggestion: check for spelling errors or missing imports.

In [6]:
H = zeros(ComplexF64,2^N,2^N)
for k in 1:length(test_visual_list)
    H += x[k]*reduce(kron, [Sigma[C[k][i]] for i in eachindex(C[1])])
end
H 

UndefVarError: UndefVarError: `test_visual_list` not defined in `Main`
Suggestion: check for spelling errors or missing imports.

In [44]:
H = zeros(ComplexF64,2^N,2^N)
for k in 1:length(test_visual_list)
    H += x[k]*kron([Sigma[C[k][i]] for i in eachindex(C[1])]...)
end
H 

# Hay que guardar las A's
# Buscar el mejor formato para guardar matrices en Julia 

UndefVarError: UndefVarError: `x` not defined in `Main`
Suggestion: check for spelling errors or missing imports.

$\{A_i\}$ deben ser operadores fijos lo que varían son 1000 datos distintos del conjunto de $\{c_i\}$ y tomar la mitad inferior de $\{\ket{\psi_n\}}$ ¿Qué tanto podemos reducir los estados y que nos siga dando una buena aproximación? 

### Almacenar todos los operadores locales A 

In [8]:
#particles=3
#k=3
#list=[0:3 for _ in 1:k]
#test_visual_list2 = []
#for place in 1:particles-k+1
#for i in Base.product(list...)
#    total_list=zeros(particles)
#    total_list[place:place+k-1]= i|>collect
#    print(total_list)
#    push!(test_visual_list,total_list)
#    print("\n")
#end
#end

In [9]:
particles=3
k=2
list=[0:3 for _ in 1:k]
test_visual_list = []
place= 2
for i in Base.product(list...)
    total_list=zeros(particles)
    total_list[place:place+k-1]= i|>collect
    if sum(total_list) != 0
        ##print(total_list)
        push!(test_visual_list,total_list)
    end
   # print("\n")
end
test_visual_list

15-element Vector{Any}:
 [0.0, 1.0, 0.0]
 [0.0, 2.0, 0.0]
 [0.0, 3.0, 0.0]
 [0.0, 0.0, 1.0]
 [0.0, 1.0, 1.0]
 [0.0, 2.0, 1.0]
 [0.0, 3.0, 1.0]
 [0.0, 0.0, 2.0]
 [0.0, 1.0, 2.0]
 [0.0, 2.0, 2.0]
 [0.0, 3.0, 2.0]
 [0.0, 0.0, 3.0]
 [0.0, 1.0, 3.0]
 [0.0, 2.0, 3.0]
 [0.0, 3.0, 3.0]

In [10]:
sum(test_visual_list[6])

3.0

In [11]:
particles = 3 
place = 1

k=2
list=[0:3 for _ in 1:k]
test_visual_list = []

for i in Base.product(list...)
    total_list=zeros(particles)
    total_list[place:place+k-1]= i|>collect
    if sum(total_list) != 0
        ##print(total_list)
        push!(test_visual_list,total_list)
    end
   # print("\n")
end

ArrayA1 = []
for i in 1:length(test_visual_list)
    if test_visual_list[i][place] != test_visual_list[i][place+1] && sum(test_visual_list[i]) != 0
        push!(ArrayA1,test_visual_list[i])
    end
end
ArrayA1

12-element Vector{Any}:
 [1.0, 0.0, 0.0]
 [2.0, 0.0, 0.0]
 [3.0, 0.0, 0.0]
 [0.0, 1.0, 0.0]
 [2.0, 1.0, 0.0]
 [3.0, 1.0, 0.0]
 [0.0, 2.0, 0.0]
 [1.0, 2.0, 0.0]
 [3.0, 2.0, 0.0]
 [0.0, 3.0, 0.0]
 [1.0, 3.0, 0.0]
 [2.0, 3.0, 0.0]

In [12]:
particles = 3 
place = 2

k=2
list=[0:3 for _ in 1:k]
test_visual_list = []

for i in Base.product(list...)
    total_list=zeros(particles)
    total_list[place:place+k-1]= i|>collect
    if sum(total_list) != 0
        ##print(total_list)
        push!(test_visual_list,total_list)
    end
   # print("\n")
end

ArrayA2 = []
for i in 1:length(test_visual_list)
    if test_visual_list[i][place] != test_visual_list[i][place+1] && sum(test_visual_list[i]) != 0
        push!(ArrayA2,test_visual_list[i])
    end
end
ArrayA2

12-element Vector{Any}:
 [0.0, 1.0, 0.0]
 [0.0, 2.0, 0.0]
 [0.0, 3.0, 0.0]
 [0.0, 0.0, 1.0]
 [0.0, 2.0, 1.0]
 [0.0, 3.0, 1.0]
 [0.0, 0.0, 2.0]
 [0.0, 1.0, 2.0]
 [0.0, 3.0, 2.0]
 [0.0, 0.0, 3.0]
 [0.0, 1.0, 3.0]
 [0.0, 2.0, 3.0]

In [13]:
ArrayA1

12-element Vector{Any}:
 [1.0, 0.0, 0.0]
 [2.0, 0.0, 0.0]
 [3.0, 0.0, 0.0]
 [0.0, 1.0, 0.0]
 [2.0, 1.0, 0.0]
 [3.0, 1.0, 0.0]
 [0.0, 2.0, 0.0]
 [1.0, 2.0, 0.0]
 [3.0, 2.0, 0.0]
 [0.0, 3.0, 0.0]
 [1.0, 3.0, 0.0]
 [2.0, 3.0, 0.0]

In [14]:
ArrayA2

xaleat = rand(length(ArrayA1))*2 .-1
xaleat2 = rand(length(ArrayA2))*2 .-1

12-element Vector{Float64}:
 -0.7417188037796398
  0.4631239517584471
 -0.6331800101314484
  0.34455406479174777
 -0.7837308960196161
  0.6089140438712128
  0.45682870318674396
 -0.9417333837912369
 -0.05047178559911236
 -0.4796313373178003
 -0.03342675165265763
  0.3740180134753792

In [15]:

xaleat = rand(length(ArrayA1))*2 .-1
xaleat2 = rand(length(ArrayA2))*2 .-1

A1= zeros(2^particles,2^particles)

for k in 1:length(ArrayA1)
    A1 += xaleat[k]*kron([Sigma[ArrayA1[k][i]] for i in eachindex(ArrayA1[1])]...)
end

A2= zeros(2^particles,2^particles)

for k in 1:length(ArrayA2)
    A2 += xaleat2[k]*kron([Sigma[ArrayA2[k][i]] for i in eachindex(ArrayA2[1])]...)
end

In [16]:
A1

8×8 Matrix{ComplexF64}:
 -0.33302+0.0im            0.0+0.0im       …         0.0+0.0im
      0.0+0.0im       -0.33302+0.0im                 0.0-0.576647im
 -1.46955+0.628368im       0.0+0.0im                 0.0+0.0im
      0.0+0.0im       -1.46955+0.628368im        1.43739+0.199916im
 0.486991-1.24725im        0.0+0.0im                 0.0+0.0im
      0.0+0.0im       0.486991-1.24725im   …  -0.0496428+0.953762im
      0.0+0.576647im       0.0+0.0im                 0.0+0.0im
      0.0+0.0im            0.0+0.576647im        0.33302+0.0im

In [17]:
A2

8×8 Matrix{ComplexF64}:
 -0.677826+0.0im        -0.655832+0.341425im   …       0.0+0.0im
 -0.655832-0.341425im    -1.22717+0.0im                0.0+0.0im
  0.264449+1.13526im          0.0-1.23149im            0.0+0.0im
       0.0-0.0747423im   -0.17822-0.0178427im          0.0+0.0im
       0.0+0.0im              0.0+0.0im                0.0+0.0747423im
       0.0+0.0im              0.0+0.0im        …  -0.17822+0.0178427im
       0.0+0.0im              0.0+0.0im            1.31229-0.638159im
       0.0+0.0im              0.0+0.0im           0.677826+0.0im

Ya tengo dos operadores locales para el caso de 3 partículas, será un problema generalizar, porque lo tendré que hacer a mano pues no veo una forma buena de hacer los Arrays, tal vez deba ver cómo hacerlo en diccionario...

$H = \sum_i C_i A_i$, aquí es donde queremos generar 1000 pares de elementos C1 y C2 para formar distintos Hamiltonianos y almacenarlos 

Necesito los promedios también de A1 y A2 con los vectores propios de H, haremos una prueba para un sólo valor 

In [18]:
c = rand(1000,2)*2 .-1 # sería conveniente generar una matriz de n x 2 

1000×2 Matrix{Float64}:
 -0.21971    -0.0419819
 -0.437143   -0.368655
 -0.188752    0.606834
  0.956681   -0.361249
  0.988594    0.955421
  0.490063    0.773678
 -0.93405    -0.977242
 -0.880865    0.153427
  0.438016    0.832831
  0.89808     0.636521
  ⋮          
 -0.337599   -0.060717
  0.569139    0.460947
 -0.917462    0.659773
  0.605514   -0.842676
  0.287262   -0.143436
 -0.244441   -0.885875
 -0.661235    0.598209
  0.0494836   0.939016
  0.794976    0.682964

In [19]:
Hnew = c[1,1]A1 + c[1,2]A2 # Recordemos quiero almacenar ai y ci, ai son promedios de los operadores y ci son simplemente números aleatorios uniformes entre [-1.1]
vecs = eigen(Hnew).vectors
advecs = adjoint(vecs)

# NADA MÁS QUEREMOS USAR LA PRIMER MITAD DE LOS VALORES ESPERADOS 
# ¿Cómo entrenar la red? 
# ¿Cuál es el formato que espera para los datos de entrada y salida? El resto se tiene que automatizar 
# Que reciba los valores esperados, pero para entrenarlo, la idea es que tome varios conjuntos de valores esperados y para cada uno de ellos valorar la red para definir 
# la función que va a minimizar. 
# Lux   (y SciML)
# SimpleChains 

8×8 adjoint(::Matrix{ComplexF64}) with eltype ComplexF64:
  0.118113-0.268209im    0.310316-0.100152im   …  -0.401206+0.0im
 -0.126909+0.355377im    0.227705-0.207605im      -0.331091+0.0im
  0.223704-0.236331im   -0.134988-0.130572im      -0.184812+0.0im
  0.144724-0.0959837im   0.336694+0.153677im       0.548377-0.0im
 -0.111739-0.332972im    0.242841-0.25534im        0.334716+0.0im
 0.0315124+0.38378im     0.248308-0.296741im   …   0.415967-0.0im
  0.347222+0.414017im    0.325481+0.0846081im     -0.185488+0.0im
   0.20456+0.173803im   -0.488661+0.0265426im      0.273991+0.0im

In [20]:
ExpVal1 = zeros(ComplexF64,size(vecs)[1])
for i in 1:size(vecs)[1]
    ExpVal1[i] = transpose(advecs[i,:])*A1*vecs[:,i]
end

ExpVal2 = zeros(ComplexF64,size(vecs)[1])  # ExpVal2[1] = a21 = \bra{\phi1_}A_2\ket{\phi_1}
for i in 1:size(vecs)[1]
    ExpVal2[i] = transpose(advecs[i,:])*A2*vecs[:,i]
end
ExpVal1

8-element Vector{ComplexF64}:
  2.8857594564878037 + 0.0im
    2.92570523638577 - 4.85722573273506e-17im
  0.8148990951819786 + 0.0im
  0.7883604705416176 - 2.42861286636753e-17im
 -0.8013513317038493 - 2.42861286636753e-17im
 -0.7802473685188491 + 2.7755575615628914e-17im
 -2.8912765602740866 + 0.0im
  -2.941848998100386 + 1.1102230246251565e-16im

In [21]:
c1 = Tuple(c[1,:])
dic = Dict()



Dict{Any, Any}()

In [22]:
c[1,:]

2-element Vector{Float64}:
 -0.21970962060181654
 -0.041981897709292504

In [23]:
dic[c1] = [ExpVal1,ExpVal2]

2-element Vector{Vector{ComplexF64}}:
 [2.8857594564878037 + 0.0im, 2.92570523638577 - 4.85722573273506e-17im, 0.8148990951819786 + 0.0im, 0.7883604705416176 - 2.42861286636753e-17im, -0.8013513317038493 - 2.42861286636753e-17im, -0.7802473685188491 + 2.7755575615628914e-17im, -2.8912765602740866 + 0.0im, -2.941848998100386 + 1.1102230246251565e-16im]
 [0.6672368213123576 - 6.938893903907228e-17im, -0.7274687332745928 + 1.457167719820518e-16im, 0.8628233815315766 - 4.163336342344337e-17im, -0.7300289781942149 + 1.3877787807814457e-17im, 0.7339356593242814 + 2.0816681711721685e-17im, -0.5298954792039678 - 3.469446951953614e-18im, 0.7312745370436072 + 4.163336342344337e-17im, -1.0078772085390477 - 6.938893903907228e-17im]

In [24]:
dic[c1][1] #ExpVal1 

8-element Vector{ComplexF64}:
  2.8857594564878037 + 0.0im
    2.92570523638577 - 4.85722573273506e-17im
  0.8148990951819786 + 0.0im
  0.7883604705416176 - 2.42861286636753e-17im
 -0.8013513317038493 - 2.42861286636753e-17im
 -0.7802473685188491 + 2.7755575615628914e-17im
 -2.8912765602740866 + 0.0im
  -2.941848998100386 + 1.1102230246251565e-16im

In [25]:
dic[c1][2] # ExpVal2

8-element Vector{ComplexF64}:
  0.6672368213123576 - 6.938893903907228e-17im
 -0.7274687332745928 + 1.457167719820518e-16im
  0.8628233815315766 - 4.163336342344337e-17im
 -0.7300289781942149 + 1.3877787807814457e-17im
  0.7339356593242814 + 2.0816681711721685e-17im
 -0.5298954792039678 - 3.469446951953614e-18im
  0.7312745370436072 + 4.163336342344337e-17im
 -1.0078772085390477 - 6.938893903907228e-17im

In [26]:
c1

(-0.21970962060181654, -0.041981897709292504)

In [27]:
dic[c1]

2-element Vector{Vector{ComplexF64}}:
 [2.8857594564878037 + 0.0im, 2.92570523638577 - 4.85722573273506e-17im, 0.8148990951819786 + 0.0im, 0.7883604705416176 - 2.42861286636753e-17im, -0.8013513317038493 - 2.42861286636753e-17im, -0.7802473685188491 + 2.7755575615628914e-17im, -2.8912765602740866 + 0.0im, -2.941848998100386 + 1.1102230246251565e-16im]
 [0.6672368213123576 - 6.938893903907228e-17im, -0.7274687332745928 + 1.457167719820518e-16im, 0.8628233815315766 - 4.163336342344337e-17im, -0.7300289781942149 + 1.3877787807814457e-17im, 0.7339356593242814 + 2.0816681711721685e-17im, -0.5298954792039678 - 3.469446951953614e-18im, 0.7312745370436072 + 4.163336342344337e-17im, -1.0078772085390477 - 6.938893903907228e-17im]

In [28]:
dic2 = Dict()

Dict{Any, Any}()

In [29]:
dic2[1] = c1

(-0.21970962060181654, -0.041981897709292504)

In [30]:
dic2[1]

(-0.21970962060181654, -0.041981897709292504)

In [31]:
dic2

Dict{Any, Any} with 1 entry:
  1 => (-0.21971, -0.0419819)

In [32]:
dic[dic2[1]]

2-element Vector{Vector{ComplexF64}}:
 [2.8857594564878037 + 0.0im, 2.92570523638577 - 4.85722573273506e-17im, 0.8148990951819786 + 0.0im, 0.7883604705416176 - 2.42861286636753e-17im, -0.8013513317038493 - 2.42861286636753e-17im, -0.7802473685188491 + 2.7755575615628914e-17im, -2.8912765602740866 + 0.0im, -2.941848998100386 + 1.1102230246251565e-16im]
 [0.6672368213123576 - 6.938893903907228e-17im, -0.7274687332745928 + 1.457167719820518e-16im, 0.8628233815315766 - 4.163336342344337e-17im, -0.7300289781942149 + 1.3877787807814457e-17im, 0.7339356593242814 + 2.0816681711721685e-17im, -0.5298954792039678 - 3.469446951953614e-18im, 0.7312745370436072 + 4.163336342344337e-17im, -1.0078772085390477 - 6.938893903907228e-17im]

In [33]:
dic3 = Dict()
for i in 1:10
    dic3[i] = 2*i
end
dic3

Dict{Any, Any} with 10 entries:
  5  => 10
  4  => 8
  6  => 12
  7  => 14
  2  => 4
  10 => 20
  9  => 18
  8  => 16
  3  => 6
  1  => 2

In [34]:
dic3[7]

14

In [36]:
xaleatMat1 = rand(1000,length(ArrayA1)).*2 .-1
xaleatMat2 = rand(1000,length(ArrayA2)).*2 .-1

APrueba = zeros(2^particles,2^particles)
APrueba2 = ones(2^particles,2^particles)

dicPrueba = Dict()
dicPrueba[1] = APrueba
dicPrueba[2] = APrueba2
dicPrueba[1][:,:]
xaleatMat1[1,:]

12-element Vector{Float64}:
  0.3336181700222902
  0.6142766211137931
  0.590061560750117
 -0.801345044840241
 -0.02874271817173013
 -0.1604860018540908
 -0.706845372297846
  0.761022958733413
  0.9017563887996225
  0.8179897783232859
 -0.24172488312581097
 -0.0277082459374578

In [45]:
# Construcción de las 1000 tuplas con dos constantes aleatorias para c1 y c2 para A1 y A2 respectivamente
Cdic = Dict()
for k in 1:1000
    Cdic[k] = Tuple(c[k,:])
end
Cdic[k]

# Construcción de los 1000 operadores locales (Aleatorios)

xaleatMat1 = rand(1000,length(ArrayA1)).*2 .-1
xaleatMat2 = rand(1000,length(ArrayA2)).*2 .-1

dicA1Total = Dict()

for i in 1:1000
    A1P = zeros(2^particles,2^particles)
    for k in 1:length(ArrayA1)
        A1P += xaleatMat1[i,k]*kron([Sigma[ArrayA1[k][i]] for i in eachindex(ArrayA1[1])]...)
    end
    dicA1Total[i] = A1P
end

dicA2Total = Dict()

for i in 1:1000
    A2P = zeros(2^particles,2^particles)
    for k in 1:length(ArrayA2)
        A2P += xaleatMat2[i,k]*kron([Sigma[ArrayA2[k][i]] for i in eachindex(ArrayA2[1])]...)
    end
    dicA2Total[i] = A2P
end

Cdic[k] # Cdic[k][1] y Cdic[k][2]

Hdic = Dict()

for i in 1:1000
    Hdic[i] = c[i,1]*dicA1Total[i] + c[i,2]*dicA2Total[i]
end
Hdic[152]

8×8 Matrix{ComplexF64}:
 -0.733528+0.0im          0.11387+0.0118346im  …         0.0+0.0im
   0.11387-0.0118346im   -0.61196+0.0im                  0.0-0.485578im
  0.702363+0.502204im         0.0-0.0851177im            0.0+0.0im
       0.0-0.00772831im  0.687154+0.547347im       -0.186474+1.4018im
  0.890233+0.311326im         0.0+0.0im                  0.0+0.00772831im
       0.0+0.0im         0.890233+0.311326im   …    -0.76153+1.30626im
       0.0+0.485578im         0.0+0.0im           -0.0420166+0.0971603im
       0.0+0.0im              0.0+0.485578im        0.733528+0.0im

In [ ]:
# Tengo 1000 Hamiltonianos que serán los que supervisaran la red con respecto a los 1000 operadores A1 y A2, pero recordemos que sólo 
# nos interesa la mitad de los estados propios, entonces tendremos algo de la siguiente dimensión 

# 1000 x 1 x (2^N)/2 x 
# 1 x 2^N es un vector (1x8) en este ejemplo, pero queremos sólo tomar la primer mitad de valores esperados
# 1 x 4 

In [57]:
ExpVal1Dic = Dict()
ExpVal2Dic = Dict()

for k in 1:1000
    Hnew = Hdic[k]
    vecs = eigen(Hnew).vectors
    advecs = adjoint(vecs)

    ExpVal1 = zeros(ComplexF64, Int((size(vecs)[1])/2))
    for i in 1:Int((size(vecs)[1])/2)
        ExpVal1[i] = transpose(advecs[i,:])*A1*vecs[:,i]
    end

    ExpVal2 = zeros(ComplexF64,Int((size(vecs)[1])/2))  # ExpVal2[1] = a21 = \bra{\phi1_}A_2\ket{\phi_1}
    for i in 1:Int((size(vecs)[1])/2)
        ExpVal2[i] = transpose(advecs[i,:])*A2*vecs[:,i]
    end
    ExpVal1Dic[k] = ExpVal1
    ExpVal2Dic[k] = ExpVal2
end
ExpVal1Dic[1]
ExpVal2Dic[1]


4-element Vector{ComplexF64}:
 -0.015883019249818497 + 0.0im
   -1.1869972480903512 - 2.7755575615628914e-17im
   0.31703259249673826 - 1.734723475976807e-17im
    0.7582385286625842 - 2.7755575615628914e-17im

In [58]:
ExpVals = Dict(k => (ExpVal1Dic[k], ExpVal2Dic[k]) for k in keys(ExpVal1Dic))

Dict{Int64, Tuple{Vector{ComplexF64}, Vector{ComplexF64}}} with 1000 entries:
  719 => ([-0.576412+4.16334e-17im, 0.239658+5.55112e-17im, 0.400609-8.32667e-1…
  699 => ([-0.537126+5.55112e-17im, 0.942609-5.55112e-17im, -0.963072-4.16334e-…
  831 => ([0.512426-5.55112e-17im, -0.548506+5.55112e-17im, -0.794164+0.0im, 0.…
  319 => ([-1.38881-2.77556e-17im, -0.742922+0.0im, -0.254176+5.55112e-17im, 0.…
  687 => ([1.35393+2.1684e-18im, 0.0168039+4.68375e-17im, 0.56573-5.55112e-17im…
  185 => ([1.22248+2.77556e-17im, 0.571068+1.17961e-16im, 0.628268+1.38778e-17i…
  823 => ([0.718014+2.77556e-17im, -0.860443+4.16334e-17im, 0.0477132+1.38778e-…
  420 => ([1.57545-2.77556e-17im, -0.431324-4.85723e-17im, 1.41122+3.46945e-18i…
  525 => ([0.630321+0.0im, 0.926886+6.93889e-17im, -0.0157451+2.08167e-17im, -0…
  365 => ([-0.443393+5.55112e-17im, -0.594456-2.77556e-17im, 0.593124-1.38778e-…
  638 => ([-0.911402+0.0im, -0.000103779+0.0im, 0.539382+1.38778e-17im, 0.21228…
  263 => ([-1.8919-6.93889e-17i

Se presenta en el diccionario ExpVals 

$\bra{\varphi_k} A_1\ket{\varphi_k}$ y despues $\bra{\varphi_k} A_2\ket{\varphi_k}$

$k = 1,2,3,4$

In [69]:
ExpVals  # (4x1, 4x1) x 1000  Se presenta primero A1 y luego A2

Dict{Int64, Tuple{Vector{ComplexF64}, Vector{ComplexF64}}} with 1000 entries:
  719 => ([-0.576412+4.16334e-17im, 0.239658+5.55112e-17im, 0.400609-8.32667e-1…
  699 => ([-0.537126+5.55112e-17im, 0.942609-5.55112e-17im, -0.963072-4.16334e-…
  831 => ([0.512426-5.55112e-17im, -0.548506+5.55112e-17im, -0.794164+0.0im, 0.…
  319 => ([-1.38881-2.77556e-17im, -0.742922+0.0im, -0.254176+5.55112e-17im, 0.…
  687 => ([1.35393+2.1684e-18im, 0.0168039+4.68375e-17im, 0.56573-5.55112e-17im…
  185 => ([1.22248+2.77556e-17im, 0.571068+1.17961e-16im, 0.628268+1.38778e-17i…
  823 => ([0.718014+2.77556e-17im, -0.860443+4.16334e-17im, 0.0477132+1.38778e-…
  420 => ([1.57545-2.77556e-17im, -0.431324-4.85723e-17im, 1.41122+3.46945e-18i…
  525 => ([0.630321+0.0im, 0.926886+6.93889e-17im, -0.0157451+2.08167e-17im, -0…
  365 => ([-0.443393+5.55112e-17im, -0.594456-2.77556e-17im, 0.593124-1.38778e-…
  638 => ([-0.911402+0.0im, -0.000103779+0.0im, 0.539382+1.38778e-17im, 0.21228…
  263 => ([-1.8919-6.93889e-17i

In [71]:
Hdic # (8x8) x 1000 son matrices 8x8 y 1000 matrices de esas 

Dict{Any, Any} with 1000 entries:
  719 => ComplexF64[0.441393+0.0im 0.308581-0.33396im … 0.0-0.384196im 0.0+0.0i…
  699 => ComplexF64[0.204599+0.0im -1.21852-0.131697im … 0.0-0.089637im 0.0+0.0…
  831 => ComplexF64[0.702615+0.0im 1.14756-0.601414im … 0.0+0.0559107im 0.0+0.0…
  319 => ComplexF64[-0.270441-0.0im -0.645096+0.728638im … -0.0-0.700548im -0.0…
  687 => ComplexF64[-0.462138+0.0im 0.135471-0.404278im … 0.0-0.0957643im 0.0+0…
  185 => ComplexF64[-1.06188-0.0im -0.396282+0.367417im … -0.0+0.295424im -0.0-…
  823 => ComplexF64[0.279951+0.0im 0.570548+0.816197im … 0.0-0.205602im 0.0+0.0…
  420 => ComplexF64[0.473206-0.0im -0.57563-0.900399im … -0.0+0.207434im -0.0-0…
  525 => ComplexF64[-0.381603+0.0im 0.663658-0.115238im … 0.0+0.809543im 0.0+0.…
  365 => ComplexF64[0.306788+0.0im 0.154245-0.0103706im … 0.0+0.0136655im 0.0+0…
  638 => ComplexF64[0.466332+0.0im 0.00773512+0.392106im … 0.0-0.00105432im 0.0…
  263 => ComplexF64[-0.478983-0.0im 0.341211-0.576927im … -0.0-0.27398im -0