In [2]:
using Plots
using LinearAlgebra
using LaTeXStrings
using HDF5

In [3]:
list = [1:3  for _ in 1:k]

UndefVarError: UndefVarError: `k` not defined in `Main`
Suggestion: check for spelling errors or missing imports.

In [4]:
N = 3 # number of qubits
d = 2^N # dimension of the Hilbert space

sigmax = [0 1; 1 0]
sigmay = [0 -im; im 0]
sigmaz = [1 0; 0 -1]
id= [1 0; 0 1] # Matriz identidad


Sigma = Dict(0 => id, 1 => sigmax, 2 => sigmay, 3 => sigmaz) #Diccionario para llamar a las matrices de Pauli
Sigma[1]

2×2 Matrix{Int64}:
 0  1
 1  0

### a |> f = f(a)

In [5]:
#particles= 10
#k=3
#list=[1:3 for _ in 1:k]
#test_visual_list = []
#for place in 1:particles-k+1
#    for i in Base.product(list...)
#        total_list=zeros(particles)
#        total_list[place:place+k-1]= i|>collect
#        print(total_list)
#        push!(test_visual_list,total_list)
#        print("\n")
#    end
#end

In [6]:
# Usarlo para la suma 
N = particles
C = test_visual_list
x = rand(length(test_visual_list))*2 .-1
# A = reduce(kron, [Sigma[C[1][i]] for i in eachindex(C[1])])


UndefVarError: UndefVarError: `particles` not defined in `Main`
Suggestion: check for spelling errors or missing imports.

In [7]:
H = zeros(ComplexF64,2^N,2^N)
for k in 1:length(test_visual_list)
    H += x[k]*reduce(kron, [Sigma[C[k][i]] for i in eachindex(C[1])])
end
H 

UndefVarError: UndefVarError: `test_visual_list` not defined in `Main`
Suggestion: check for spelling errors or missing imports.

In [8]:
H = zeros(ComplexF64,2^N,2^N)
for k in 1:length(test_visual_list)
    H += x[k]*kron([Sigma[C[k][i]] for i in eachindex(C[1])]...)
end
H 

# Hay que guardar las A's
# Buscar el mejor formato para guardar matrices en Julia 

UndefVarError: UndefVarError: `test_visual_list` not defined in `Main`
Suggestion: check for spelling errors or missing imports.

$\{A_i\}$ deben ser operadores fijos lo que varían son 1000 datos distintos del conjunto de $\{c_i\}$ y tomar la mitad inferior de $\{\ket{\psi_n\}}$ ¿Qué tanto podemos reducir los estados y que nos siga dando una buena aproximación? 

### Almacenar todos los operadores locales A 

In [9]:
#particles=3
#k=3
#list=[0:3 for _ in 1:k]
#test_visual_list2 = []
#for place in 1:particles-k+1
#for i in Base.product(list...)
#    total_list=zeros(particles)
#    total_list[place:place+k-1]= i|>collect
#    print(total_list)
#    push!(test_visual_list,total_list)
#    print("\n")
#end
#end

In [10]:
particles=3
k=2
list=[0:3 for _ in 1:k]
test_visual_list = []
place= 2
for i in Base.product(list...)
    total_list=zeros(particles)
    total_list[place:place+k-1]= i|>collect
    if sum(total_list) != 0
        ##print(total_list)
        push!(test_visual_list,total_list)
    end
   # print("\n")
end
test_visual_list

15-element Vector{Any}:
 [0.0, 1.0, 0.0]
 [0.0, 2.0, 0.0]
 [0.0, 3.0, 0.0]
 [0.0, 0.0, 1.0]
 [0.0, 1.0, 1.0]
 [0.0, 2.0, 1.0]
 [0.0, 3.0, 1.0]
 [0.0, 0.0, 2.0]
 [0.0, 1.0, 2.0]
 [0.0, 2.0, 2.0]
 [0.0, 3.0, 2.0]
 [0.0, 0.0, 3.0]
 [0.0, 1.0, 3.0]
 [0.0, 2.0, 3.0]
 [0.0, 3.0, 3.0]

In [11]:
sum(test_visual_list[6])

3.0

In [12]:
particles = 3 
place = 1

k=2
list=[0:3 for _ in 1:k]
test_visual_list = []

for i in Base.product(list...)
    total_list=zeros(particles)
    total_list[place:place+k-1]= i|>collect
    if sum(total_list) != 0
        ##print(total_list)
        push!(test_visual_list,total_list)
    end
   # print("\n")
end

ArrayA1 = []
for i in 1:length(test_visual_list)
    if test_visual_list[i][place] != test_visual_list[i][place+1] && sum(test_visual_list[i]) != 0
        push!(ArrayA1,test_visual_list[i])
    end
end
ArrayA1

12-element Vector{Any}:
 [1.0, 0.0, 0.0]
 [2.0, 0.0, 0.0]
 [3.0, 0.0, 0.0]
 [0.0, 1.0, 0.0]
 [2.0, 1.0, 0.0]
 [3.0, 1.0, 0.0]
 [0.0, 2.0, 0.0]
 [1.0, 2.0, 0.0]
 [3.0, 2.0, 0.0]
 [0.0, 3.0, 0.0]
 [1.0, 3.0, 0.0]
 [2.0, 3.0, 0.0]

In [13]:
particles = 3 
place = 2

k=2
list=[0:3 for _ in 1:k]
test_visual_list = []

for i in Base.product(list...)
    total_list=zeros(particles)
    total_list[place:place+k-1]= i|>collect
    if sum(total_list) != 0
        ##print(total_list)
        push!(test_visual_list,total_list)
    end
   # print("\n")
end

ArrayA2 = []
for i in 1:length(test_visual_list)
    if test_visual_list[i][place] != test_visual_list[i][place+1] && sum(test_visual_list[i]) != 0
        push!(ArrayA2,test_visual_list[i])
    end
end
ArrayA2

12-element Vector{Any}:
 [0.0, 1.0, 0.0]
 [0.0, 2.0, 0.0]
 [0.0, 3.0, 0.0]
 [0.0, 0.0, 1.0]
 [0.0, 2.0, 1.0]
 [0.0, 3.0, 1.0]
 [0.0, 0.0, 2.0]
 [0.0, 1.0, 2.0]
 [0.0, 3.0, 2.0]
 [0.0, 0.0, 3.0]
 [0.0, 1.0, 3.0]
 [0.0, 2.0, 3.0]

In [14]:
ArrayA1

12-element Vector{Any}:
 [1.0, 0.0, 0.0]
 [2.0, 0.0, 0.0]
 [3.0, 0.0, 0.0]
 [0.0, 1.0, 0.0]
 [2.0, 1.0, 0.0]
 [3.0, 1.0, 0.0]
 [0.0, 2.0, 0.0]
 [1.0, 2.0, 0.0]
 [3.0, 2.0, 0.0]
 [0.0, 3.0, 0.0]
 [1.0, 3.0, 0.0]
 [2.0, 3.0, 0.0]

In [15]:
ArrayA2

xaleat = rand(length(ArrayA1))*2 .-1
xaleat2 = rand(length(ArrayA2))*2 .-1

12-element Vector{Float64}:
 -0.2674755409753218
  0.43872843376963844
 -0.03443596211122646
 -0.1659202632980954
  0.20050619949966753
  0.5889352516152366
 -0.5844218843327234
  0.7567607012181752
 -0.7962626292274133
 -0.2661715273385772
 -0.7849075010037878
 -0.6605323885864827

In [16]:

xaleat = rand(length(ArrayA1))*2 .-1
xaleat2 = rand(length(ArrayA2))*2 .-1

A1= zeros(2^particles,2^particles)

for k in 1:length(ArrayA1)
    A1 += xaleat[k]*kron([Sigma[ArrayA1[k][i]] for i in eachindex(ArrayA1[1])]...)
end

A2= zeros(2^particles,2^particles)

for k in 1:length(ArrayA2)
    A2 += xaleat2[k]*kron([Sigma[ArrayA2[k][i]] for i in eachindex(ArrayA2[1])]...)
end

In [17]:
A1

8×8 Matrix{ComplexF64}:
  1.00279+0.0im            0.0+0.0im       …       0.0+0.0im
      0.0+0.0im        1.00279+0.0im               0.0-1.20936im
  0.27451+1.61079im        0.0+0.0im               0.0+0.0im
      0.0+0.0im        0.27451+1.61079im      0.125444-1.32843im
 -1.15677-0.217158im       0.0+0.0im               0.0+0.0im
      0.0+0.0im       -1.15677-0.217158im  …   1.63822-0.183076im
      0.0+1.20936im        0.0+0.0im               0.0+0.0im
      0.0+0.0im            0.0+1.20936im      -1.00279+0.0im

In [18]:
A2

8×8 Matrix{ComplexF64}:
 -0.300607+0.0im       0.423015+1.38068im   …        0.0+0.0im
  0.423015-1.38068im   0.231736+0.0im                0.0+0.0im
  -1.05238-0.221804im       0.0-0.556255im           0.0+0.0im
       0.0+0.957267im  0.517432+1.09926im            0.0+0.0im
       0.0+0.0im            0.0+0.0im                0.0-0.957267im
       0.0+0.0im            0.0+0.0im       …   0.517432-1.09926im
       0.0+0.0im            0.0+0.0im          -0.754856-0.211841im
       0.0+0.0im            0.0+0.0im           0.300607+0.0im

Ya tengo dos operadores locales para el caso de 3 partículas, será un problema generalizar, porque lo tendré que hacer a mano pues no veo una forma buena de hacer los Arrays, tal vez deba ver cómo hacerlo en diccionario...

$H = \sum_i C_i A_i$, aquí es donde queremos generar 1000 pares de elementos C1 y C2 para formar distintos Hamiltonianos y almacenarlos 

Necesito los promedios también de A1 y A2 con los vectores propios de H, haremos una prueba para un sólo valor 

In [20]:
c = rand(1000,2)*2 .-1 # sería conveniente generar una matriz de n x 2 

1000×2 Matrix{Float64}:
  0.128751    -0.224289
  0.0951491   -0.519208
 -0.426759    -0.155877
 -0.543796    -0.0356709
 -0.107201    -0.583708
  0.0458303    0.281002
  0.674878     0.411383
  0.312834     0.356403
  0.0568724    0.614144
  0.531558    -0.137583
  ⋮           
 -0.648755    -0.95141
  0.00956045   0.0154188
 -0.432874     0.916821
  0.0355624    0.74575
  0.707734    -0.162105
 -0.354535     0.960939
  0.873749    -0.460683
  0.00867395  -0.00664972
 -0.145764     0.576263

In [21]:
Hnew = c[1,1]A1 + c[1,2]A2 # Recordemos quiero almacenar ai y ci, ai son promedios de los operadores y ci son simplemente números aleatorios uniformes entre [-1.1]
vecs = eigen(Hnew).vectors
advecs = adjoint(vecs)

# NADA MÁS QUEREMOS USAR LA PRIMER MITAD DE LOS VALORES ESPERADOS 
# ¿Cómo entrenar la red? 
# ¿Cuál es el formato que espera para los datos de entrada y salida? El resto se tiene que automatizar 
# Que reciba los valores esperados, pero para entrenarlo, la idea es que tome varios conjuntos de valores esperados y para cada uno de ellos valorar la red para definir 
# la función que va a minimizar. 
# Lux   (y SciML)
# SimpleChains 

8×8 adjoint(::Matrix{ComplexF64}) with eltype ComplexF64:
  0.0685181+0.181587im   -0.0869738+0.0377618im   …   0.410119+0.0im
  -0.212765-0.441525im     0.173311-0.422268im        0.389925+0.0im
   0.141854+0.307032im    -0.267651-0.0885801im       0.507523-0.0im
   0.164378+0.049367im    -0.382374-0.00805941im     -0.339486+0.0im
   0.163197-0.0312759im    0.184267+0.169359im        0.407821-0.0im
  -0.153569-0.0545017im   -0.487894+0.123108im    …   0.113225-0.0im
 -0.0504255+0.335566im     0.262245-0.295048im       -0.327566+0.0im
   0.188703-0.611022im    -0.280232-0.0819497im      -0.143152+0.0im

In [22]:
ExpVal1 = zeros(ComplexF64,size(vecs)[1])
for i in 1:size(vecs)[1]
    ExpVal1[i] = transpose(advecs[i,:])*A1*vecs[:,i]
end

ExpVal2 = zeros(ComplexF64,size(vecs)[1])  # ExpVal2[1] = a21 = \bra{\phi1_}A_2\ket{\phi_1}
for i in 1:size(vecs)[1]
    ExpVal2[i] = transpose(advecs[i,:])*A2*vecs[:,i]
end
ExpVal1

8-element Vector{ComplexF64}:
  -2.575629106840477 - 5.551115123125783e-17im
 -0.3200521225301304 - 2.7755575615628914e-17im
  -1.668984841556536 + 2.7755575615628914e-17im
 -0.5916711649779395 - 2.0816681711721685e-17im
  0.6931476326933376 - 6.938893903907228e-18im
  1.1063504093144663 - 1.734723475976807e-17im
  0.7946549930335923 + 2.7755575615628914e-17im
  2.5621842008636837 - 4.85722573273506e-17im

In [23]:
c1 = Tuple(c[1,:])
dic = Dict()



Dict{Any, Any}()

In [43]:
c[1,:]

2-element Vector{Float64}:
  0.12875070530750987
 -0.22428936378832987

In [25]:
dic[c1] = [ExpVal1,ExpVal2]

2-element Vector{Vector{ComplexF64}}:
 [-2.575629106840477 - 5.551115123125783e-17im, -0.3200521225301304 - 2.7755575615628914e-17im, -1.668984841556536 + 2.7755575615628914e-17im, -0.5916711649779395 - 2.0816681711721685e-17im, 0.6931476326933376 - 6.938893903907228e-18im, 1.1063504093144663 - 1.734723475976807e-17im, 0.7946549930335923 + 2.7755575615628914e-17im, 2.5621842008636837 - 4.85722573273506e-17im]
 [2.3969414158544033 - 8.326672684688674e-17im, 2.1688747484543063 - 5.551115123125783e-17im, 0.07349705282276253 - 2.7755575615628914e-17im, 0.022285031186499382 + 0.0im, -0.2876872574605929 + 3.642919299551295e-17im, -0.6255174224790576 - 1.3877787807814457e-17im, -1.7811974631890561 + 4.163336342344337e-17im, -1.9671961051892686 + 1.3877787807814457e-17im]

In [26]:
dic[c1][1] #ExpVal1 

8-element Vector{ComplexF64}:
  -2.575629106840477 - 5.551115123125783e-17im
 -0.3200521225301304 - 2.7755575615628914e-17im
  -1.668984841556536 + 2.7755575615628914e-17im
 -0.5916711649779395 - 2.0816681711721685e-17im
  0.6931476326933376 - 6.938893903907228e-18im
  1.1063504093144663 - 1.734723475976807e-17im
  0.7946549930335923 + 2.7755575615628914e-17im
  2.5621842008636837 - 4.85722573273506e-17im

In [27]:
dic[c1][2] # ExpVal2

8-element Vector{ComplexF64}:
   2.3969414158544033 - 8.326672684688674e-17im
   2.1688747484543063 - 5.551115123125783e-17im
  0.07349705282276253 - 2.7755575615628914e-17im
 0.022285031186499382 + 0.0im
  -0.2876872574605929 + 3.642919299551295e-17im
  -0.6255174224790576 - 1.3877787807814457e-17im
  -1.7811974631890561 + 4.163336342344337e-17im
  -1.9671961051892686 + 1.3877787807814457e-17im

In [28]:
c1

(0.12875070530750987, -0.22428936378832987)

In [29]:
dic[c1]

2-element Vector{Vector{ComplexF64}}:
 [-2.575629106840477 - 5.551115123125783e-17im, -0.3200521225301304 - 2.7755575615628914e-17im, -1.668984841556536 + 2.7755575615628914e-17im, -0.5916711649779395 - 2.0816681711721685e-17im, 0.6931476326933376 - 6.938893903907228e-18im, 1.1063504093144663 - 1.734723475976807e-17im, 0.7946549930335923 + 2.7755575615628914e-17im, 2.5621842008636837 - 4.85722573273506e-17im]
 [2.3969414158544033 - 8.326672684688674e-17im, 2.1688747484543063 - 5.551115123125783e-17im, 0.07349705282276253 - 2.7755575615628914e-17im, 0.022285031186499382 + 0.0im, -0.2876872574605929 + 3.642919299551295e-17im, -0.6255174224790576 - 1.3877787807814457e-17im, -1.7811974631890561 + 4.163336342344337e-17im, -1.9671961051892686 + 1.3877787807814457e-17im]

In [30]:
dic2 = Dict()

Dict{Any, Any}()

In [31]:
dic2[1] = c1

(0.12875070530750987, -0.22428936378832987)

In [32]:
dic2[1]

(0.12875070530750987, -0.22428936378832987)

In [44]:
dic2

Dict{Any, Any} with 1 entry:
  1 => (0.128751, -0.224289)

In [33]:
dic[dic2[1]]

2-element Vector{Vector{ComplexF64}}:
 [-2.575629106840477 - 5.551115123125783e-17im, -0.3200521225301304 - 2.7755575615628914e-17im, -1.668984841556536 + 2.7755575615628914e-17im, -0.5916711649779395 - 2.0816681711721685e-17im, 0.6931476326933376 - 6.938893903907228e-18im, 1.1063504093144663 - 1.734723475976807e-17im, 0.7946549930335923 + 2.7755575615628914e-17im, 2.5621842008636837 - 4.85722573273506e-17im]
 [2.3969414158544033 - 8.326672684688674e-17im, 2.1688747484543063 - 5.551115123125783e-17im, 0.07349705282276253 - 2.7755575615628914e-17im, 0.022285031186499382 + 0.0im, -0.2876872574605929 + 3.642919299551295e-17im, -0.6255174224790576 - 1.3877787807814457e-17im, -1.7811974631890561 + 4.163336342344337e-17im, -1.9671961051892686 + 1.3877787807814457e-17im]

In [34]:
dic3 = Dict()
for i in 1:10
    dic3[i] = 2*i
end
dic3

Dict{Any, Any} with 10 entries:
  5  => 10
  4  => 8
  6  => 12
  7  => 14
  2  => 4
  10 => 20
  9  => 18
  8  => 16
  3  => 6
  1  => 2

In [35]:
dic3[7]

14

In [36]:
Cdic = Dict()
for k in 1:1000
    Cdic["c$k"] = Tuple(c[k,:])
end
Cdic["c2"]

(0.09514905840989818, -0.519208318479248)

In [37]:
Cdic["c725"]

(0.1567730178275888, 0.09268239418420943)

In [64]:
xaleatMat1 = rand(1000,length(ArrayA1)).*2 .-1
xaleatMat2 = rand(1000,length(ArrayA2)).*2 .-1

APrueba = zeros(2^particles,2^particles)
APrueba2 = ones(2^particles,2^particles)

dicPrueba = Dict()
dicPrueba[1] = APrueba
dicPrueba[2] = APrueba2
dicPrueba[1][:,:]

8×8 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [38]:
xaleat = rand(length(ArrayA1))*2 .-1
xaleat2 = rand(length(ArrayA2))*2 .-1

A1= zeros(2^particles,2^particles)

for k in 1:length(ArrayA1)
    A1 += xaleat[k]*kron([Sigma[ArrayA1[k][i]] for i in eachindex(ArrayA1[1])]...)
end

A2= zeros(2^particles,2^particles)

for k in 1:length(ArrayA2)
    A2 += xaleat2[k]*kron([Sigma[ArrayA2[k][i]] for i in eachindex(ArrayA2[1])]...)
end

In [45]:
ExpVal1 = zeros(ComplexF64,size(vecs)[1])
for i in 1:size(vecs)[1]
    ExpVal1[i] = transpose(advecs[i,:])*A1*vecs[:,i]
end

ExpVal2 = zeros(ComplexF64,size(vecs)[1])  # ExpVal2[1] = a21 = \bra{\phi1_}A_2\ket{\phi_1}
for i in 1:size(vecs)[1]
    ExpVal2[i] = transpose(advecs[i,:])*A2*vecs[:,i]
end
ExpVal1

8-element Vector{ComplexF64}:
  -2.575629106840477 - 5.551115123125783e-17im
 -0.3200521225301304 - 2.7755575615628914e-17im
  -1.668984841556536 + 2.7755575615628914e-17im
 -0.5916711649779395 - 2.0816681711721685e-17im
  0.6931476326933376 - 6.938893903907228e-18im
  1.1063504093144663 - 1.734723475976807e-17im
  0.7946549930335923 + 2.7755575615628914e-17im
  2.5621842008636837 - 4.85722573273506e-17im

In [2]:
Threads.nthreads()

4