In [37]:
using Plots
using LinearAlgebra
using LaTeXStrings
using HDF5

In [7]:
list = [1:3  for _ in 1:k]

2-element Vector{UnitRange{Int64}}:
 1:3
 1:3

In [50]:
N = 3 # number of qubits
d = 2^N # dimension of the Hilbert space

sigmax = [0 1; 1 0]
sigmay = [0 -im; im 0]
sigmaz = [1 0; 0 -1]
id= [1 0; 0 1] # Matriz identidad


Sigma = Dict(0 => id, 1 => sigmax, 2 => sigmay, 3 => sigmaz) #Diccionario para llamar a las matrices de Pauli
Sigma[1]

2×2 Matrix{Int64}:
 0  1
 1  0

### a |> f = f(a)

In [18]:
#particles= 10
#k=3
#list=[1:3 for _ in 1:k]
#test_visual_list = []
#for place in 1:particles-k+1
#    for i in Base.product(list...)
#        total_list=zeros(particles)
#        total_list[place:place+k-1]= i|>collect
#        print(total_list)
#        push!(test_visual_list,total_list)
#        print("\n")
#    end
#end

In [19]:
# Usarlo para la suma 
N = particles
C = test_visual_list
x = rand(length(test_visual_list))*2 .-1
# A = reduce(kron, [Sigma[C[1][i]] for i in eachindex(C[1])])


15-element Vector{Float64}:
  0.3350708057100491
 -0.22848040240041234
  0.8316531740312876
  0.7228697932587629
  0.04048530495228575
 -0.5335085531680817
 -0.9438246068135225
  0.563893824462919
  0.3833106042576735
  0.04998648058998101
 -0.6531101441133935
 -0.3494504746708438
  0.5599166003905618
  0.8372742846943808
  0.8683182109651142

In [20]:
H = zeros(ComplexF64,2^N,2^N)
for k in 1:length(test_visual_list)
    H += x[k]*reduce(kron, [Sigma[C[k][i]] for i in eachindex(C[1])])
end
H 

8×8 Matrix{ComplexF64}:
     1.35052+0.0im                0.0+0.0im        …          0.0+0.0im
         0.0+0.0im            1.35052+0.0im           -0.00950118+0.150198im
   -0.220955-0.0892163im          0.0+0.0im                   0.0+0.0im
         0.0+0.0im          -0.220955-0.0892163im       -0.224846+1.06575im
    0.894987+0.608794im           0.0+0.0im                   0.0+0.0im
         0.0+0.0im           0.894987+0.608794im   …      1.66669-1.217im
 -0.00950118-0.150198im           0.0+0.0im                   0.0+0.0im
         0.0+0.0im        -0.00950118-0.150198im         0.386116+0.0im

In [12]:
H = zeros(ComplexF64,2^N,2^N)
for k in 1:length(test_visual_list)
    H += x[k]*kron([Sigma[C[k][i]] for i in eachindex(C[1])]...)
end
H 

# Hay que guardar las A's
# Buscar el mejor formato para guardar matrices en Julia 

1024×1024 Matrix{ComplexF64}:
  -0.772553+0.0im       0.0343036-0.964566im  …         0.0+0.0im
  0.0343036+0.964566im   -1.51135+0.0im                 0.0+0.0im
   -1.54574-0.816295im   0.248876+0.399636im            0.0+0.0im
   0.231813-0.16959im    0.161895-1.06602im             0.0+0.0im
    1.13377-0.127766im  -0.754049+0.733054im            0.0+0.0im
   -1.20085-1.05287im   -0.857764+1.22064im   …         0.0+0.0im
  0.0620953+1.1478im      2.51535-0.635509im            0.0+0.0im
 -0.0333301-0.529918im   -1.48841+0.239415im            0.0+0.0im
     0.4776-0.104811im        0.0+0.0im                 0.0+0.0im
        0.0+0.0im          0.4776-0.104811im            0.0+0.0im
           ⋮                                  ⋱  
        0.0+0.0im             0.0+0.0im       …      0.4776+0.104811im
        0.0+0.0im             0.0+0.0im          -0.0333301+0.529918im
        0.0+0.0im             0.0+0.0im          -0.0620953+1.1478im
        0.0+0.0im             0.0+0.0im          

$\{A_i\}$ deben ser operadores fijos lo que varían son 1000 datos distintos del conjunto de $\{c_i\}$ y tomar la mitad inferior de $\{\ket{\psi_n\}}$ ¿Qué tanto podemos reducir los estados y que nos siga dando una buena aproximación? 

### Almacenar todos los operadores locales A 

In [13]:
#particles=3
#k=3
#list=[0:3 for _ in 1:k]
#test_visual_list2 = []
#for place in 1:particles-k+1
#for i in Base.product(list...)
#    total_list=zeros(particles)
#    total_list[place:place+k-1]= i|>collect
#    print(total_list)
#    push!(test_visual_list,total_list)
#    print("\n")
#end
#end

In [33]:
particles=3
k=2
list=[0:3 for _ in 1:k]
test_visual_list = []
place= 2
for i in Base.product(list...)
    total_list=zeros(particles)
    total_list[place:place+k-1]= i|>collect
    if sum(total_list) != 0
        ##print(total_list)
        push!(test_visual_list,total_list)
    end
   # print("\n")
end
test_visual_list

15-element Vector{Any}:
 [0.0, 1.0, 0.0]
 [0.0, 2.0, 0.0]
 [0.0, 3.0, 0.0]
 [0.0, 0.0, 1.0]
 [0.0, 1.0, 1.0]
 [0.0, 2.0, 1.0]
 [0.0, 3.0, 1.0]
 [0.0, 0.0, 2.0]
 [0.0, 1.0, 2.0]
 [0.0, 2.0, 2.0]
 [0.0, 3.0, 2.0]
 [0.0, 0.0, 3.0]
 [0.0, 1.0, 3.0]
 [0.0, 2.0, 3.0]
 [0.0, 3.0, 3.0]

In [16]:
sum(test_visual_list[6])

3.0

In [35]:
particles = 3 
place = 1

k=2
list=[0:3 for _ in 1:k]
test_visual_list = []

for i in Base.product(list...)
    total_list=zeros(particles)
    total_list[place:place+k-1]= i|>collect
    if sum(total_list) != 0
        ##print(total_list)
        push!(test_visual_list,total_list)
    end
   # print("\n")
end

ArrayA1 = []
for i in 1:length(test_visual_list)
    if test_visual_list[i][place] != test_visual_list[i][place+1] && sum(test_visual_list[i]) != 0
        push!(ArrayA1,test_visual_list[i])
    end
end
ArrayA1

12-element Vector{Any}:
 [1.0, 0.0, 0.0]
 [2.0, 0.0, 0.0]
 [3.0, 0.0, 0.0]
 [0.0, 1.0, 0.0]
 [2.0, 1.0, 0.0]
 [3.0, 1.0, 0.0]
 [0.0, 2.0, 0.0]
 [1.0, 2.0, 0.0]
 [3.0, 2.0, 0.0]
 [0.0, 3.0, 0.0]
 [1.0, 3.0, 0.0]
 [2.0, 3.0, 0.0]

In [36]:
particles = 3 
place = 2

k=2
list=[0:3 for _ in 1:k]
test_visual_list = []

for i in Base.product(list...)
    total_list=zeros(particles)
    total_list[place:place+k-1]= i|>collect
    if sum(total_list) != 0
        ##print(total_list)
        push!(test_visual_list,total_list)
    end
   # print("\n")
end

ArrayA2 = []
for i in 1:length(test_visual_list)
    if test_visual_list[i][place] != test_visual_list[i][place+1] && sum(test_visual_list[i]) != 0
        push!(ArrayA2,test_visual_list[i])
    end
end
ArrayA2

12-element Vector{Any}:
 [0.0, 1.0, 0.0]
 [0.0, 2.0, 0.0]
 [0.0, 3.0, 0.0]
 [0.0, 0.0, 1.0]
 [0.0, 2.0, 1.0]
 [0.0, 3.0, 1.0]
 [0.0, 0.0, 2.0]
 [0.0, 1.0, 2.0]
 [0.0, 3.0, 2.0]
 [0.0, 0.0, 3.0]
 [0.0, 1.0, 3.0]
 [0.0, 2.0, 3.0]

In [38]:
ArrayA1

12-element Vector{Any}:
 [1.0, 0.0, 0.0]
 [2.0, 0.0, 0.0]
 [3.0, 0.0, 0.0]
 [0.0, 1.0, 0.0]
 [2.0, 1.0, 0.0]
 [3.0, 1.0, 0.0]
 [0.0, 2.0, 0.0]
 [1.0, 2.0, 0.0]
 [3.0, 2.0, 0.0]
 [0.0, 3.0, 0.0]
 [1.0, 3.0, 0.0]
 [2.0, 3.0, 0.0]

In [57]:
ArrayA2

xaleat = rand(length(ArrayA1))*2 .-1
xaleat2 = rand(length(ArrayA2))*2 .-1

12-element Vector{Float64}:
 -0.6925826287647037
  0.9091839158056623
  0.6027100538080601
  0.8289551007213349
  0.8367676665572432
 -0.5615421332981738
 -0.5601038742376858
  0.2701535794002765
  0.3675309234654238
 -0.8262707715165598
 -0.1647955307103557
 -0.7576294488054813

In [61]:
A1= zeros(2^particles,2^particles)

for k in 1:length(ArrayA1)
    A1 += xaleat[k]*kron([Sigma[ArrayA1[k][i]] for i in eachindex(ArrayA1[1])]...)
end

A2= zeros(2^particles,2^particles)

for k in 1:length(ArrayA2)
    A2 += xaleat2[k]*kron([Sigma[ArrayA2[k][i]] for i in eachindex(ArrayA2[1])]...)
end

In [62]:
A1

8×8 Matrix{ComplexF64}:
   0.36309+0.0im              0.0+0.0im        …        0.0+0.0im
       0.0+0.0im          0.36309+0.0im                 0.0-0.0575059im
 -0.223731+0.982623im         0.0+0.0im                 0.0+0.0im
       0.0+0.0im        -0.223731+0.982623im      -0.487158+0.314061im
   -1.2676-0.279774im         0.0+0.0im                 0.0+0.0im
       0.0+0.0im          -1.2676-0.279774im   …   0.280919-0.605944im
       0.0+0.0575059im        0.0+0.0im                 0.0+0.0im
       0.0+0.0im              0.0+0.0575059im      -0.36309+0.0im

In [63]:
A2

8×8 Matrix{ComplexF64}:
 -0.223561+0.0im        0.267413+0.192573im  …        0.0+0.0im
  0.267413-0.192573im    1.42898+0.0im                0.0+0.0im
 -0.857378+0.151554im        0.0+0.566614im           0.0+0.0im
       0.0+1.10692im   -0.527787+1.66681im            0.0+0.0im
       0.0+0.0im             0.0+0.0im                0.0-1.10692im
       0.0+0.0im             0.0+0.0im       …  -0.527787-1.66681im
       0.0+0.0im             0.0+0.0im             1.3905+0.927635im
       0.0+0.0im             0.0+0.0im           0.223561+0.0im

Ya tengo dos operadores locales para el caso de 3 partículas, será un problema generalizar, porque lo tendré que hacer a mano pues no veo una forma buena de hacer los Arrays, tal vez deba ver cómo hacerlo en diccionario...

$H = \sum_i C_i A_i$, aquí es donde queremos generar 1000 pares de elementos C1 y C2 para formar distintos Hamiltonianos y almacenarlos 

In [ ]:
Necesito los promedios también de A1 y A2 con los vectores propios de H, haremos una prueba para un sólo valor 

In [132]:
c = rand(1000,2)*2 .-1 # sería conveniente generar una matriz de n x 2 

1000×2 Matrix{Float64}:
  0.369962   -0.984586
 -0.136591   -0.947296
 -0.0789107  -0.637931
  0.30606    -0.441566
  0.470358    0.340951
  0.889051    0.771175
 -0.169809   -0.559178
 -0.600016    0.190834
  0.22221     0.660444
 -0.335319   -0.892549
  ⋮          
  0.1797      0.261118
 -0.855177    0.18213
 -0.178156   -0.42196
  0.87144    -0.835564
 -0.299755   -0.495145
 -0.887879    0.834076
  0.418967   -0.56113
  0.50366    -0.019274
  0.877851    0.557863

In [133]:
Hnew = c[1,1]A1 + c[1,2]A2 # Recordemos quiero almacenar ai y ci, ai son promedios de los operadores y ci son simplemente números aleatorios uniformes entre [-1.1]
vecs = eigen(Hnew).vectors
advecs = adjoint(vecs)

# NADA MÁS QUEREMOS USAR LA PRIMER MITAD DE LOS VALORES ESPERADOS 
# ¿Cómo entrenar la red? 
# ¿Cuál es el formato que espera para los datos de entrada y salida? El resto se tiene que automatizar 
# Que reciba los valores esperados, pero para entrenarlo, la idea es que tome varios conjuntos de valores esperados y para cada uno de ellos valorar la red para definir 
# la función que va a minimizar. 
# Lux   (y SciML)
# SimpleChains 

8×8 adjoint(::Matrix{ComplexF64}) with eltype ComplexF64:
  0.112038-0.164471im     0.251483-0.32945im    …   -0.407994+0.0im
  0.100598-0.172425im     0.273649-0.354011im        0.535361-0.0im
  0.208274-0.373585im    -0.178522+0.457793im      -0.0908619+0.0im
  0.293822+0.0421079im     -0.3433+0.363274im        0.177727+0.0im
  0.380291-0.59508im    -0.0977507-0.289137im        0.115751+0.0im
  0.134815-0.0741986im   -0.047113-0.176809im   …    -0.45747+0.0im
  -0.24029-0.0635614im   0.0376814-0.0545028im       0.410052+0.0im
 -0.219207-0.131325im    0.0727135-0.0207499im       -0.34098+0.0im

In [135]:
ExpVal1 = zeros(ComplexF64,size(vecs)[1])
for i in 1:size(vecs)[1]
    ExpVal1[i] = transpose(advecs[i,:])*A1*vecs[:,i]
end

ExpVal2 = zeros(ComplexF64,size(vecs)[1])  # ExpVal2[1] = a21 = \bra{\phi1_}A_2\ket{\phi_1}
for i in 1:size(vecs)[1]
    ExpVal2[i] = transpose(advecs[i,:])*A2*vecs[:,i]
end
ExpVal1

8-element Vector{ComplexF64}:
 -1.2628281028503556 + 6.938893903907228e-18im
   2.018982108148898 + 2.0816681711721685e-17im
 -1.0485201415148178 + 4.163336342344337e-17im
  0.3775581544904767 - 8.326672684688674e-17im
 -0.8343597631026666 + 0.0im
 -0.2271499937098767 - 8.326672684688674e-17im
  -0.554900876813133 - 2.7755575615628914e-17im
  1.5312186153514757 - 1.1102230246251565e-16im

In [151]:
c1 = Tuple(c[1,:])
dic = Dict()



Dict{Any, Any}()

In [152]:
dic[c1] = [ExpVal1,ExpVal2]

2-element Vector{Vector{ComplexF64}}:
 [-1.2628281028503556 + 6.938893903907228e-18im, 2.018982108148898 + 2.0816681711721685e-17im, -1.0485201415148178 + 4.163336342344337e-17im, 0.3775581544904767 - 8.326672684688674e-17im, -0.8343597631026666 + 0.0im, -0.2271499937098767 - 8.326672684688674e-17im, -0.554900876813133 - 2.7755575615628914e-17im, 1.5312186153514757 - 1.1102230246251565e-16im]
 [3.3695147734335578 + 1.6653345369377348e-16im, 3.289810672066956 + 5.551115123125783e-17im, 0.5023315404974288 + 2.168404344971009e-18im, 0.36318247742319487 + 0.0im, -1.1559448436886575 + 5.551115123125783e-17im, -1.271649593842067 + 4.85722573273506e-17im, -2.615829017857765 + 0.0im, -2.481416008032646 + 1.1796119636642288e-16im]

In [158]:
dic[c1][1] #ExpVal1 

8-element Vector{ComplexF64}:
 -1.2628281028503556 + 6.938893903907228e-18im
   2.018982108148898 + 2.0816681711721685e-17im
 -1.0485201415148178 + 4.163336342344337e-17im
  0.3775581544904767 - 8.326672684688674e-17im
 -0.8343597631026666 + 0.0im
 -0.2271499937098767 - 8.326672684688674e-17im
  -0.554900876813133 - 2.7755575615628914e-17im
  1.5312186153514757 - 1.1102230246251565e-16im

In [159]:
dic[c1][2] # ExpVal2

8-element Vector{ComplexF64}:
  3.3695147734335578 + 1.6653345369377348e-16im
   3.289810672066956 + 5.551115123125783e-17im
  0.5023315404974288 + 2.168404344971009e-18im
 0.36318247742319487 + 0.0im
 -1.1559448436886575 + 5.551115123125783e-17im
  -1.271649593842067 + 4.85722573273506e-17im
  -2.615829017857765 + 0.0im
  -2.481416008032646 + 1.1796119636642288e-16im

In [160]:
c1

(0.36996219290147137, -0.984585604995873)

In [163]:
dic[c1]

2-element Vector{Vector{ComplexF64}}:
 [-1.2628281028503556 + 6.938893903907228e-18im, 2.018982108148898 + 2.0816681711721685e-17im, -1.0485201415148178 + 4.163336342344337e-17im, 0.3775581544904767 - 8.326672684688674e-17im, -0.8343597631026666 + 0.0im, -0.2271499937098767 - 8.326672684688674e-17im, -0.554900876813133 - 2.7755575615628914e-17im, 1.5312186153514757 - 1.1102230246251565e-16im]
 [3.3695147734335578 + 1.6653345369377348e-16im, 3.289810672066956 + 5.551115123125783e-17im, 0.5023315404974288 + 2.168404344971009e-18im, 0.36318247742319487 + 0.0im, -1.1559448436886575 + 5.551115123125783e-17im, -1.271649593842067 + 4.85722573273506e-17im, -2.615829017857765 + 0.0im, -2.481416008032646 + 1.1796119636642288e-16im]

In [173]:
dic2 = Dict()

Dict{Any, Any}()

In [174]:
dic2[1] = c1

(0.36996219290147137, -0.984585604995873)

In [175]:
dic2[1]

(0.36996219290147137, -0.984585604995873)

In [177]:
dic[dic2[1]]

2-element Vector{Vector{ComplexF64}}:
 [-1.2628281028503556 + 6.938893903907228e-18im, 2.018982108148898 + 2.0816681711721685e-17im, -1.0485201415148178 + 4.163336342344337e-17im, 0.3775581544904767 - 8.326672684688674e-17im, -0.8343597631026666 + 0.0im, -0.2271499937098767 - 8.326672684688674e-17im, -0.554900876813133 - 2.7755575615628914e-17im, 1.5312186153514757 - 1.1102230246251565e-16im]
 [3.3695147734335578 + 1.6653345369377348e-16im, 3.289810672066956 + 5.551115123125783e-17im, 0.5023315404974288 + 2.168404344971009e-18im, 0.36318247742319487 + 0.0im, -1.1559448436886575 + 5.551115123125783e-17im, -1.271649593842067 + 4.85722573273506e-17im, -2.615829017857765 + 0.0im, -2.481416008032646 + 1.1796119636642288e-16im]

In [182]:
dic3 = Dict()
for i in 1:10
    dic3[i] = 2*i
end
dic3

Dict{Any, Any} with 10 entries:
  5  => 10
  4  => 8
  6  => 12
  7  => 14
  2  => 4
  10 => 20
  9  => 18
  8  => 16
  3  => 6
  1  => 2

In [183]:
dic3[7]

14

In [199]:
Cdic = Dict()
for k in 1:1000
    Cdic["c$k"] = Tuple(c[k,:])
end
Cdic["c2"]

(-0.13659082060630778, -0.9472960560057897)

In [205]:
Cdic["c725"]

(0.01677094343142782, -0.9571081572929685)