In [217]:
using Plots
using LinearAlgebra
using LaTeXStrings
using HDF5

using Lux, MLUtils, Optimisers, Zygote, OneHotArrays, Random, Statistics, Printf, Reactant
using MLDatasets: MNIST
using SimpleChains: SimpleChains

Reactant.set_default_backend("cpu")

No supervisado

Familias de Hamiltonianos y se generen valores esperados
y si se usa clustering y se agrupa con los datos e identificar los que se parecen 
y si se puede identificar las familias de Hamiltonianos

normalización de batches 
y dropout (Para eliminar aleatoriamente)

In [148]:
k=3
list = [1:3  for _ in 1:k]

3-element Vector{UnitRange{Int64}}:
 1:3
 1:3
 1:3

In [149]:
N = 3 # number of qubits
d = 2^N # dimension of the Hilbert space

sigmax = [0 1; 1 0]
sigmay = [0 -im; im 0]
sigmaz = [1 0; 0 -1]
id= [1 0; 0 1] # Matriz identidad


Sigma = Dict(0 => id, 1 => sigmax, 2 => sigmay, 3 => sigmaz) #Diccionario para llamar a las matrices de Pauli
Sigma[1]

2×2 Matrix{Int64}:
 0  1
 1  0

### a |> f = f(a)

In [150]:
#particles= 10
#k=3
#list=[1:3 for _ in 1:k]
#test_visual_list = []
#for place in 1:particles-k+1
#    for i in Base.product(list...)
#        total_list=zeros(particles)
#        total_list[place:place+k-1]= i|>collect
#        print(total_list)
#        push!(test_visual_list,total_list)
#        print("\n")
#    end
#end

In [151]:
# Usarlo para la suma 
N = particles
C = test_visual_list
x = rand(length(test_visual_list))*2 .-1
# A = reduce(kron, [Sigma[C[1][i]] for i in eachindex(C[1])])


15-element Vector{Float64}:
 -0.9738478165164566
 -0.9302133046999943
  0.5256253273451545
 -0.6459948240151858
  0.7985461365158004
  0.5993859013377856
 -0.7937045161990621
  0.25842555101688247
  0.7053306366329797
  0.791377910037746
 -0.7981691026834881
  0.7036095913520723
  0.119502665563195
 -0.9061488798078601
  0.05948602393335012

In [152]:
H = zeros(ComplexF64,2^N,2^N)
for k in 1:length(test_visual_list)
    H += x[k]*reduce(kron, [Sigma[C[k][i]] for i in eachindex(C[1])])
end
H 

8×8 Matrix{ComplexF64}:
    1.28872+0.0im        -1.4397+0.539744im   …         0.0+0.0im
    -1.4397-0.539744im  -0.23747+0.0im                  0.0+0.0im
  -0.854345-1.83636im    1.58992-0.105945im             0.0+0.0im
 0.00716823+1.30472im   -1.09335-0.0240644im            0.0+0.0im
        0.0+0.0im            0.0+0.0im           0.00716823-1.30472im
        0.0+0.0im            0.0+0.0im        …    -1.09335+0.0240644im
        0.0+0.0im            0.0+0.0im              0.14771-1.05659im
        0.0+0.0im            0.0+0.0im             -1.16975+0.0im

In [153]:
H = zeros(ComplexF64,2^N,2^N)
for k in 1:length(test_visual_list)
    H += x[k]*kron([Sigma[C[k][i]] for i in eachindex(C[1])]...)
end
H 

# Hay que guardar las A's
# Buscar el mejor formato para guardar matrices en Julia 

8×8 Matrix{ComplexF64}:
    1.28872+0.0im        -1.4397+0.539744im   …         0.0+0.0im
    -1.4397-0.539744im  -0.23747+0.0im                  0.0+0.0im
  -0.854345-1.83636im    1.58992-0.105945im             0.0+0.0im
 0.00716823+1.30472im   -1.09335-0.0240644im            0.0+0.0im
        0.0+0.0im            0.0+0.0im           0.00716823-1.30472im
        0.0+0.0im            0.0+0.0im        …    -1.09335+0.0240644im
        0.0+0.0im            0.0+0.0im              0.14771-1.05659im
        0.0+0.0im            0.0+0.0im             -1.16975+0.0im

$\{A_i\}$ deben ser operadores fijos lo que varían son 1000 datos distintos del conjunto de $\{c_i\}$ y tomar la mitad inferior de $\{\ket{\psi_n\}}$ ¿Qué tanto podemos reducir los estados y que nos siga dando una buena aproximación? 

### Almacenar todos los operadores locales A 

In [154]:
#particles=3
#k=3
#list=[0:3 for _ in 1:k]
#test_visual_list2 = []
#for place in 1:particles-k+1
#for i in Base.product(list...)
#    total_list=zeros(particles)
#    total_list[place:place+k-1]= i|>collect
#    print(total_list)
#    push!(test_visual_list,total_list)
#    print("\n")
#end
#end

In [155]:
particles=3
k=2
list=[0:3 for _ in 1:k]
test_visual_list = []
place= 2
for i in Base.product(list...)
    total_list=zeros(particles)
    total_list[place:place+k-1]= i|>collect
    if sum(total_list) != 0
        ##print(total_list)
        push!(test_visual_list,total_list)
    end
   # print("\n")
end
test_visual_list

15-element Vector{Any}:
 [0.0, 1.0, 0.0]
 [0.0, 2.0, 0.0]
 [0.0, 3.0, 0.0]
 [0.0, 0.0, 1.0]
 [0.0, 1.0, 1.0]
 [0.0, 2.0, 1.0]
 [0.0, 3.0, 1.0]
 [0.0, 0.0, 2.0]
 [0.0, 1.0, 2.0]
 [0.0, 2.0, 2.0]
 [0.0, 3.0, 2.0]
 [0.0, 0.0, 3.0]
 [0.0, 1.0, 3.0]
 [0.0, 2.0, 3.0]
 [0.0, 3.0, 3.0]

In [156]:
sum(test_visual_list[6])

3.0

In [157]:
particles = 3 
place = 1

k=2
list=[0:3 for _ in 1:k]
test_visual_list = []

for i in Base.product(list...)
    total_list=zeros(particles)
    total_list[place:place+k-1]= i|>collect
    if sum(total_list) != 0
        ##print(total_list)
        push!(test_visual_list,total_list)
    end
   # print("\n")
end

ArrayA1 = []
for i in 1:length(test_visual_list)
    if test_visual_list[i][place] != test_visual_list[i][place+1] && sum(test_visual_list[i]) != 0
        push!(ArrayA1,test_visual_list[i])
    end
end
ArrayA1

12-element Vector{Any}:
 [1.0, 0.0, 0.0]
 [2.0, 0.0, 0.0]
 [3.0, 0.0, 0.0]
 [0.0, 1.0, 0.0]
 [2.0, 1.0, 0.0]
 [3.0, 1.0, 0.0]
 [0.0, 2.0, 0.0]
 [1.0, 2.0, 0.0]
 [3.0, 2.0, 0.0]
 [0.0, 3.0, 0.0]
 [1.0, 3.0, 0.0]
 [2.0, 3.0, 0.0]

In [158]:
particles = 3 
place = 2

k=2
list=[0:3 for _ in 1:k]
test_visual_list = []

for i in Base.product(list...)
    total_list=zeros(particles)
    total_list[place:place+k-1]= i|>collect
    if sum(total_list) != 0
        ##print(total_list)
        push!(test_visual_list,total_list)
    end
   # print("\n")
end

ArrayA2 = []
for i in 1:length(test_visual_list)
    if test_visual_list[i][place] != test_visual_list[i][place+1] && sum(test_visual_list[i]) != 0
        push!(ArrayA2,test_visual_list[i])
    end
end
ArrayA2

12-element Vector{Any}:
 [0.0, 1.0, 0.0]
 [0.0, 2.0, 0.0]
 [0.0, 3.0, 0.0]
 [0.0, 0.0, 1.0]
 [0.0, 2.0, 1.0]
 [0.0, 3.0, 1.0]
 [0.0, 0.0, 2.0]
 [0.0, 1.0, 2.0]
 [0.0, 3.0, 2.0]
 [0.0, 0.0, 3.0]
 [0.0, 1.0, 3.0]
 [0.0, 2.0, 3.0]

In [159]:
ArrayA1

12-element Vector{Any}:
 [1.0, 0.0, 0.0]
 [2.0, 0.0, 0.0]
 [3.0, 0.0, 0.0]
 [0.0, 1.0, 0.0]
 [2.0, 1.0, 0.0]
 [3.0, 1.0, 0.0]
 [0.0, 2.0, 0.0]
 [1.0, 2.0, 0.0]
 [3.0, 2.0, 0.0]
 [0.0, 3.0, 0.0]
 [1.0, 3.0, 0.0]
 [2.0, 3.0, 0.0]

In [160]:
ArrayA2

xaleat = rand(length(ArrayA1))*2 .-1
xaleat2 = rand(length(ArrayA2))*2 .-1

12-element Vector{Float64}:
  0.823129193482572
 -0.00897129213709702
  0.7252209007953303
  0.6065046400540102
 -0.3903552223969231
  0.33158220869199084
 -0.12974537749002457
  0.38318985289170193
  0.9959493243321633
 -0.008111024786726873
  0.10315237342271799
 -0.4391129097367059

In [161]:

xaleat = rand(length(ArrayA1))*2 .-1
xaleat2 = rand(length(ArrayA2))*2 .-1

A1= zeros(2^particles,2^particles)

for k in 1:length(ArrayA1)
    A1 += xaleat[k]*kron([Sigma[ArrayA1[k][i]] for i in eachindex(ArrayA1[1])]...)
end

A2= zeros(2^particles,2^particles)

for k in 1:length(ArrayA2)
    A2 += xaleat2[k]*kron([Sigma[ArrayA2[k][i]] for i in eachindex(ArrayA2[1])]...)
end

In [162]:
A1

8×8 Matrix{ComplexF64}:
 -0.735991+0.0im             0.0+0.0im       …       0.0+0.0im
       0.0+0.0im       -0.735991+0.0im               0.0+0.285814im
 -0.480756+1.01058im         0.0+0.0im               0.0+0.0im
       0.0+0.0im       -0.480756+1.01058im      0.550072-0.548883im
   1.03725-0.564143im        0.0+0.0im               0.0+0.0im
       0.0+0.0im         1.03725-0.564143im  …   1.42854+0.492062im
       0.0-0.285814im        0.0+0.0im               0.0+0.0im
       0.0+0.0im             0.0-0.285814im     0.735991+0.0im

In [163]:
A2

8×8 Matrix{ComplexF64}:
 0.478815+0.0im         1.34035+0.707974im  …        0.0+0.0im
  1.34035-0.707974im   -1.24241+0.0im                0.0+0.0im
 0.859461-0.115142im        0.0+1.40049im            0.0+0.0im
      0.0+0.389849im  -0.946175-0.154337im           0.0+0.0im
      0.0+0.0im             0.0+0.0im                0.0-0.389849im
      0.0+0.0im             0.0+0.0im       …  -0.946175+0.154337im
      0.0+0.0im             0.0+0.0im           0.222793-1.23543im
      0.0+0.0im             0.0+0.0im          -0.478815+0.0im

Ya tengo dos operadores locales para el caso de 3 partículas, será un problema generalizar, porque lo tendré que hacer a mano pues no veo una forma buena de hacer los Arrays, tal vez deba ver cómo hacerlo en diccionario...

$H = \sum_i C_i A_i$, aquí es donde queremos generar 1000 pares de elementos C1 y C2 para formar distintos Hamiltonianos y almacenarlos 

Necesito los promedios también de A1 y A2 con los vectores propios de H, haremos una prueba para un sólo valor 

In [164]:
c = rand(1000,2)*2 .-1 # sería conveniente generar una matriz de n x 2 

1000×2 Matrix{Float64}:
 -0.238289  -0.506801
 -0.900158  -0.641899
 -0.353871   0.29319
 -0.929936  -0.415893
  0.846465  -0.457403
 -0.525005  -0.0328501
  0.180528   0.128496
 -0.136521  -0.981029
  0.937748   0.351533
 -0.335367   0.336217
  ⋮         
 -0.433345  -0.248591
  0.649308   0.872415
 -0.209499  -0.749353
 -0.658759   0.315197
  0.402498  -0.987806
  0.058409  -0.0914151
 -0.511936  -0.539549
 -0.543001  -0.171723
  0.715052   0.389318

In [165]:
Hnew = c[1,1]A1 + c[1,2]A2 # Recordemos quiero almacenar ai y ci, ai son promedios de los operadores y ci son simplemente números aleatorios uniformes entre [-1.1]
vecs = eigen(Hnew).vectors
advecs = adjoint(vecs)

# NADA MÁS QUEREMOS USAR LA PRIMER MITAD DE LOS VALORES ESPERADOS 
# ¿Cómo entrenar la red? 
# ¿Cuál es el formato que espera para los datos de entrada y salida? El resto se tiene que automatizar 
# Que reciba los valores esperados, pero para entrenarlo, la idea es que tome varios conjuntos de valores esperados y para cada uno de ellos valorar la red para definir 
# la función que va a minimizar. 
# Lux   (y SciML)
# SimpleChains 

8×8 adjoint(::Matrix{ComplexF64}) with eltype ComplexF64:
  0.0376071-0.145957im       0.143352-0.0207628im  …   -0.281363+0.0im
   0.122282-0.37517im        0.338102-0.231257im       0.0878286-0.0im
 -0.0433209+0.38163im     0.000553374+0.101259im        -0.42886+0.0im
 -0.0311289+0.680561im     -0.0140593+0.152944im        0.448221+0.0im
 -0.0572749+0.232075im    0.000292864+0.165375im       -0.531737+0.0im
  -0.126654-0.00738936im     0.177544+0.0803154im  …    0.447758-0.0im
  0.0267408-0.181044im      -0.191807+0.406692im        0.201813+0.0im
   -0.24407-0.208877im        0.35613+0.618906im      -0.0658574+0.0im

In [166]:
ExpVal1 = zeros(ComplexF64,size(vecs)[1])
for i in 1:size(vecs)[1]
    ExpVal1[i] = transpose(advecs[i,:])*A1*vecs[:,i]
end

ExpVal2 = zeros(ComplexF64,size(vecs)[1])  # ExpVal2[1] = a21 = \bra{\phi1_}A_2\ket{\phi_1}
for i in 1:size(vecs)[1]
    ExpVal2[i] = transpose(advecs[i,:])*A2*vecs[:,i]
end
ExpVal1

8-element Vector{ComplexF64}:
    1.5500912194934657 + 2.7755575615628914e-17im
   0.23011620266558952 + 4.85722573273506e-17im
     0.321398379377449 + 8.326672684688674e-17im
  -0.43748897402539066 - 1.0408340855860843e-16im
 -0.006819342908031434 + 4.163336342344337e-17im
  -0.08554759983723718 + 1.3877787807814457e-17im
   0.04249060936851143 - 3.469446951953614e-17im
   -1.6142404941343536 - 6.938893903907228e-17im

In [167]:
c1 = Tuple(c[1,:])
dic = Dict()



Dict{Any, Any}()

In [168]:
c[1,:]

2-element Vector{Float64}:
 -0.23828876274506272
 -0.5068009618372973

In [169]:
dic[c1] = [ExpVal1,ExpVal2]

2-element Vector{Vector{ComplexF64}}:
 [1.5500912194934657 + 2.7755575615628914e-17im, 0.23011620266558952 + 4.85722573273506e-17im, 0.321398379377449 + 8.326672684688674e-17im, -0.43748897402539066 - 1.0408340855860843e-16im, -0.006819342908031434 + 4.163336342344337e-17im, -0.08554759983723718 + 1.3877787807814457e-17im, 0.04249060936851143 - 3.469446951953614e-17im, -1.6142404941343536 - 6.938893903907228e-17im]
 [3.1256527932559197 + 1.3877787807814457e-17im, 3.047003235935093 + 5.551115123125783e-17im, 0.6203453970342097 + 3.469446951953614e-17im, 0.021797938653720622 + 3.469446951953614e-18im, -0.6726195615269296 - 2.7755575615628914e-17im, -1.2921229890280586 + 2.7755575615628914e-17im, -2.3485543126644837 + 0.0im, -2.5015025016594725 - 8.326672684688674e-17im]

In [170]:
dic[c1][1] #ExpVal1 

8-element Vector{ComplexF64}:
    1.5500912194934657 + 2.7755575615628914e-17im
   0.23011620266558952 + 4.85722573273506e-17im
     0.321398379377449 + 8.326672684688674e-17im
  -0.43748897402539066 - 1.0408340855860843e-16im
 -0.006819342908031434 + 4.163336342344337e-17im
  -0.08554759983723718 + 1.3877787807814457e-17im
   0.04249060936851143 - 3.469446951953614e-17im
   -1.6142404941343536 - 6.938893903907228e-17im

In [171]:
dic[c1][2] # ExpVal2

8-element Vector{ComplexF64}:
   3.1256527932559197 + 1.3877787807814457e-17im
    3.047003235935093 + 5.551115123125783e-17im
   0.6203453970342097 + 3.469446951953614e-17im
 0.021797938653720622 + 3.469446951953614e-18im
  -0.6726195615269296 - 2.7755575615628914e-17im
  -1.2921229890280586 + 2.7755575615628914e-17im
  -2.3485543126644837 + 0.0im
  -2.5015025016594725 - 8.326672684688674e-17im

In [172]:
c1

(-0.23828876274506272, -0.5068009618372973)

In [173]:
dic[c1]

2-element Vector{Vector{ComplexF64}}:
 [1.5500912194934657 + 2.7755575615628914e-17im, 0.23011620266558952 + 4.85722573273506e-17im, 0.321398379377449 + 8.326672684688674e-17im, -0.43748897402539066 - 1.0408340855860843e-16im, -0.006819342908031434 + 4.163336342344337e-17im, -0.08554759983723718 + 1.3877787807814457e-17im, 0.04249060936851143 - 3.469446951953614e-17im, -1.6142404941343536 - 6.938893903907228e-17im]
 [3.1256527932559197 + 1.3877787807814457e-17im, 3.047003235935093 + 5.551115123125783e-17im, 0.6203453970342097 + 3.469446951953614e-17im, 0.021797938653720622 + 3.469446951953614e-18im, -0.6726195615269296 - 2.7755575615628914e-17im, -1.2921229890280586 + 2.7755575615628914e-17im, -2.3485543126644837 + 0.0im, -2.5015025016594725 - 8.326672684688674e-17im]

In [174]:
dic2 = Dict()

Dict{Any, Any}()

In [175]:
dic2[1] = c1

(-0.23828876274506272, -0.5068009618372973)

In [176]:
dic2[1]

(-0.23828876274506272, -0.5068009618372973)

In [177]:
dic2

Dict{Any, Any} with 1 entry:
  1 => (-0.238289, -0.506801)

In [178]:
dic[dic2[1]]

2-element Vector{Vector{ComplexF64}}:
 [1.5500912194934657 + 2.7755575615628914e-17im, 0.23011620266558952 + 4.85722573273506e-17im, 0.321398379377449 + 8.326672684688674e-17im, -0.43748897402539066 - 1.0408340855860843e-16im, -0.006819342908031434 + 4.163336342344337e-17im, -0.08554759983723718 + 1.3877787807814457e-17im, 0.04249060936851143 - 3.469446951953614e-17im, -1.6142404941343536 - 6.938893903907228e-17im]
 [3.1256527932559197 + 1.3877787807814457e-17im, 3.047003235935093 + 5.551115123125783e-17im, 0.6203453970342097 + 3.469446951953614e-17im, 0.021797938653720622 + 3.469446951953614e-18im, -0.6726195615269296 - 2.7755575615628914e-17im, -1.2921229890280586 + 2.7755575615628914e-17im, -2.3485543126644837 + 0.0im, -2.5015025016594725 - 8.326672684688674e-17im]

In [179]:
dic3 = Dict()
for i in 1:10
    dic3[i] = 2*i
end
dic3

Dict{Any, Any} with 10 entries:
  5  => 10
  4  => 8
  6  => 12
  7  => 14
  2  => 4
  10 => 20
  9  => 18
  8  => 16
  3  => 6
  1  => 2

In [180]:
dic3[7]

14

In [182]:
xaleatMat1 = rand(1000,length(ArrayA1)).*2 .-1
xaleatMat2 = rand(1000,length(ArrayA2)).*2 .-1

APrueba = zeros(2^particles,2^particles)
APrueba2 = ones(2^particles,2^particles)

dicPrueba = Dict()
dicPrueba[1] = APrueba
dicPrueba[2] = APrueba2
dicPrueba[1][:,:]
xaleatMat1[1,:]

12-element Vector{Float64}:
 -0.17498394822794983
  0.8380225721911656
  0.1417263704826679
 -0.7637615431260603
  0.6632700494386128
  0.2815916665005975
 -0.4316316160203617
  0.29626077372525206
  0.9563119835770846
 -0.9285458885203521
 -0.5349047698012537
  0.5613081646999114

In [183]:
# Construcción de las 1000 tuplas con dos constantes aleatorias para c1 y c2 para A1 y A2 respectivamente
Cdic = Dict()
for k in 1:1000
    Cdic[k] = Tuple(c[k,:])
end
Cdic[k]

# Construcción de los 1000 operadores locales (Aleatorios)

xaleatMat1 = rand(1000,length(ArrayA1)).*2 .-1
xaleatMat2 = rand(1000,length(ArrayA2)).*2 .-1

dicA1Total = Dict()

for i in 1:1000
    A1P = zeros(2^particles,2^particles)
    for k in 1:length(ArrayA1)
        A1P += xaleatMat1[i,k]*kron([Sigma[ArrayA1[k][i]] for i in eachindex(ArrayA1[1])]...)
    end
    dicA1Total[i] = A1P
end

dicA2Total = Dict()

for i in 1:1000
    A2P = zeros(2^particles,2^particles)
    for k in 1:length(ArrayA2)
        A2P += xaleatMat2[i,k]*kron([Sigma[ArrayA2[k][i]] for i in eachindex(ArrayA2[1])]...)
    end
    dicA2Total[i] = A2P
end

Cdic[k] # Cdic[k][1] y Cdic[k][2]

Hdic = Dict()

for i in 1:1000
    Hdic[i] = c[i,1]*dicA1Total[i] + c[i,2]*dicA2Total[i]
end
Hdic[152]

8×8 Matrix{ComplexF64}:
 -0.721096+0.0im          0.36575-0.132638im   …         0.0+0.0im
   0.36575+0.132638im   -0.593093+0.0im                  0.0+0.19821im
 -0.416749-0.386707im         0.0+1.00784im              0.0+0.0im
       0.0-0.166546im   -0.685909+0.0390603im      -0.272632-0.334006im
 0.0775721-0.0327643im        0.0+0.0im                  0.0+0.166546im
       0.0+0.0im        0.0775721-0.0327643im  …   -0.478865-0.309127im
       0.0-0.19821im          0.0+0.0im           -0.0425611-0.0233591im
       0.0+0.0im              0.0-0.19821im         0.721096+0.0im

In [184]:
# Tengo 1000 Hamiltonianos que serán los que supervisaran la red con respecto a los 1000 operadores A1 y A2, pero recordemos que sólo 
# nos interesa la mitad de los estados propios, entonces tendremos algo de la siguiente dimensión 

# 1000 x 1 x (2^N)/2 x 
# 1 x 2^N es un vector (1x8) en este ejemplo, pero queremos sólo tomar la primer mitad de valores esperados
# 1 x 4 

In [185]:
ExpVal1Dic = Dict()
ExpVal2Dic = Dict()

for k in 1:1000
    Hnew = Hdic[k]
    vecs = eigen(Hnew).vectors
    advecs = adjoint(vecs)

    ExpVal1 = zeros(ComplexF64, Int((size(vecs)[1])/2))
    for i in 1:Int((size(vecs)[1])/2)
        ExpVal1[i] = transpose(advecs[i,:])*A1*vecs[:,i]
    end

    ExpVal2 = zeros(ComplexF64,Int((size(vecs)[1])/2))  # ExpVal2[1] = a21 = \bra{\phi1_}A_2\ket{\phi_1}
    for i in 1:Int((size(vecs)[1])/2)
        ExpVal2[i] = transpose(advecs[i,:])*A2*vecs[:,i]
    end
    ExpVal1Dic[k] = ExpVal1
    ExpVal2Dic[k] = ExpVal2
end
ExpVal1Dic[1]
ExpVal2Dic[1]


4-element Vector{ComplexF64}:
     0.81645693920352 - 2.7755575615628914e-17im
   0.4786382687531084 + 0.0im
   1.0035288316363795 + 5.551115123125783e-17im
 -0.41943857186621425 + 0.0im

In [186]:
ExpVals = Dict(k => (ExpVal1Dic[k], ExpVal2Dic[k]) for k in keys(ExpVal1Dic))

Dict{Int64, Tuple{Vector{ComplexF64}, Vector{ComplexF64}}} with 1000 entries:
  719 => ([-0.857826+0.0im, -0.979221+1.17961e-16im, 1.39162-3.1225e-17im, 1.61…
  699 => ([1.36579+5.55112e-17im, 0.130641-4.16334e-17im, 0.247545+0.0im, 0.046…
  831 => ([0.156961-2.77556e-17im, 0.634845+0.0im, 0.71028+1.38778e-17im, 0.156…
  319 => ([-1.58359-8.32667e-17im, -1.59591-6.245e-17im, 0.0591072-5.55112e-17i…
  687 => ([0.618836-5.55112e-17im, -0.527569+2.77556e-17im, -0.0326773-6.93889e…
  185 => ([0.962058+5.55112e-17im, 0.996413+0.0im, -0.704789-5.55112e-17im, -0.…
  823 => ([0.2804-4.85723e-17im, 0.673015-6.59195e-17im, -0.510752+2.77556e-17i…
  420 => ([-1.19702+1.73472e-17im, 0.175241+1.38778e-17im, -1.05381-8.67362e-18…
  525 => ([0.320392-2.77556e-17im, 0.785002+0.0im, 0.519445+2.60209e-18im, 0.18…
  365 => ([-1.14223-8.32667e-17im, 1.80387+3.46945e-17im, -0.781941-2.77556e-17…
  638 => ([0.874169-1.38778e-17im, -0.463343+5.55112e-17im, 0.362708-1.21431e-1…
  263 => ([-0.3554+1.11022e-16i

Se presenta en el diccionario ExpVals 

$\bra{\varphi_k} A_1\ket{\varphi_k}$ y despues $\bra{\varphi_k} A_2\ket{\varphi_k}$

$k = 1,2,3,4$

In [187]:

ExpVals  # (4x1, 4x1) x 1000  Se presenta primero A1 y luego A2

Dict{Int64, Tuple{Vector{ComplexF64}, Vector{ComplexF64}}} with 1000 entries:
  719 => ([-0.857826+0.0im, -0.979221+1.17961e-16im, 1.39162-3.1225e-17im, 1.61…
  699 => ([1.36579+5.55112e-17im, 0.130641-4.16334e-17im, 0.247545+0.0im, 0.046…
  831 => ([0.156961-2.77556e-17im, 0.634845+0.0im, 0.71028+1.38778e-17im, 0.156…
  319 => ([-1.58359-8.32667e-17im, -1.59591-6.245e-17im, 0.0591072-5.55112e-17i…
  687 => ([0.618836-5.55112e-17im, -0.527569+2.77556e-17im, -0.0326773-6.93889e…
  185 => ([0.962058+5.55112e-17im, 0.996413+0.0im, -0.704789-5.55112e-17im, -0.…
  823 => ([0.2804-4.85723e-17im, 0.673015-6.59195e-17im, -0.510752+2.77556e-17i…
  420 => ([-1.19702+1.73472e-17im, 0.175241+1.38778e-17im, -1.05381-8.67362e-18…
  525 => ([0.320392-2.77556e-17im, 0.785002+0.0im, 0.519445+2.60209e-18im, 0.18…
  365 => ([-1.14223-8.32667e-17im, 1.80387+3.46945e-17im, -0.781941-2.77556e-17…
  638 => ([0.874169-1.38778e-17im, -0.463343+5.55112e-17im, 0.362708-1.21431e-1…
  263 => ([-0.3554+1.11022e-16i

In [188]:
ExpVals[1][2] # ExpVal1

4-element Vector{ComplexF64}:
     0.81645693920352 - 2.7755575615628914e-17im
   0.4786382687531084 + 0.0im
   1.0035288316363795 + 5.551115123125783e-17im
 -0.41943857186621425 + 0.0im

In [189]:
Hdic # (8x8) x 1000 son matrices 8x8 y 1000 matrices de esas 

Dict{Any, Any} with 1000 entries:
  719 => ComplexF64[0.795029+0.0im 0.0466598-0.0395161im … 0.0-0.183112im 0.0+0…
  699 => ComplexF64[-0.00287087+0.0im 0.255876-0.104108im … 0.0-0.654396im 0.0+…
  831 => ComplexF64[0.326074+0.0im -0.196337-0.261639im … 0.0+0.369948im 0.0+0.…
  319 => ComplexF64[-0.538858-0.0im -0.0435354-0.144934im … -0.0+0.162013im -0.…
  687 => ComplexF64[1.22952-0.0im -0.351857+0.0637743im … -0.0+0.0807993im -0.0…
  185 => ComplexF64[0.63619+0.0im 0.0147471-0.0214304im … 0.0-0.285878im 0.0+0.…
  823 => ComplexF64[-0.0307468+0.0im 0.260092+0.220926im … 0.0-0.134009im 0.0+0…
  420 => ComplexF64[-0.900201+0.0im 0.361938+0.383387im … 0.0-0.0834019im 0.0+0…
  525 => ComplexF64[0.62169+0.0im -0.244073+0.270992im … 0.0-0.0341383im 0.0+0.…
  365 => ComplexF64[0.243609+0.0im -0.563105+0.210731im … 0.0+0.00248623im 0.0+…
  638 => ComplexF64[0.824497+0.0im 0.274392+0.190374im … 0.0+0.813765im 0.0+0.0…
  263 => ComplexF64[0.116505+0.0im -0.287895+0.471799im … 0.0-0.890833im 0.

In [190]:
ABD = collect(Hdic)

1000-element Vector{Pair{Any, Any}}:
 719 => ComplexF64[0.7950292397739389 + 0.0im 0.04665977991460799 - 0.03951607776456239im … 0.0 - 0.1831124815562505im 0.0 + 0.0im; 0.04665977991460799 + 0.03951607776456239im 0.7093033967084035 + 0.0im … 0.0 + 0.0im 0.0 - 0.1831124815562505im; … ; 0.0 + 0.1831124815562505im 0.0 + 0.0im … -0.7093033967084035 + 0.0im -0.014076314715360356 - 0.0002686811982802162im; 0.0 + 0.0im 0.0 + 0.1831124815562505im … -0.014076314715360356 + 0.0002686811982802162im -0.7950292397739389 + 0.0im]
 699 => ComplexF64[-0.0028708708493840884 + 0.0im 0.25587585562170934 - 0.10410761562493571im … 0.0 - 0.6543962841111214im 0.0 + 0.0im; 0.25587585562170934 + 0.10410761562493571im -0.1712062423975502 + 0.0im … 0.0 + 0.0im 0.0 - 0.6543962841111214im; … ; 0.0 + 0.6543962841111214im 0.0 + 0.0im … 0.1712062423975502 + 0.0im 0.03030180277912756 + 0.21504993544821854im; 0.0 + 0.0im 0.0 + 0.6543962841111214im … 0.03030180277912756 - 0.21504993544821854im 0.0028708708493840884 + 0.

## Acomodando los datos de forma conveniente para meterlos a la red neuronal
 

In [ ]:
c = rand(2,1000)*2 .-1 # sería conveniente generar una matriz de n x 2 
xaleatMat1 = rand(1000,length(ArrayA1)).*2 .-1
xaleatMat2 = rand(1000,length(ArrayA2)).*2 .-1


2×1000 Matrix{Float64}:
 0.583427  0.633148  0.253117  -0.684722  …  -0.627719   0.0445553  -0.680929
 0.114642  0.757675  0.265691  -0.601739     -0.367233  -0.845615    0.527723

In [ ]:
A1P_list = []  # Un arreglo vacío para almacenar matrices
A2P_list = []

for i in 1:1000
    A1P = zeros(2^particles, 2^particles)
    for k in 1:length(ArrayA1)
        A1P += xaleatMat1[i, k] * kron([Sigma[ArrayA1[k][j]] for j in eachindex(ArrayA1[1])]...)
    end
    push!(A1P_list, A1P)  # Guardar la matriz en el arreglo
end

for i in 1:1000
    A2P = zeros(2^particles,2^particles)
    for k in 1:length(ArrayA2)
        A2P += xaleatMat2[i,k]*kron([Sigma[ArrayA2[k][i]] for i in eachindex(ArrayA2[1])]...)
    end
    push!(A2P_list, A2P)  # Guardar la matriz en el arreglo
end

A111 = A1P_list[1] 
A222 = A2P_list[1]

In [194]:
# Fijamos A1 y A2, no necesitaremos mucho, porque con cada A1 y A2 fijos podemos generar al menos 1000 Hamiltonianos distintos
# Recordemos que dependen únicamente de los coeficientes c1 y c2, que son aleatorios
A111 = A1P_list[1] 
A222 = A2P_list[1]


8×8 Matrix{ComplexF64}:
  0.224935+0.0im        0.320709+0.373529im  …        0.0+0.0im
  0.320709-0.373529im  -0.344344+0.0im                0.0+0.0im
 -0.315958-0.120488im        0.0-0.374957im           0.0+0.0im
       0.0+0.726871im   -1.52939+1.2402im             0.0+0.0im
       0.0+0.0im             0.0+0.0im                0.0-0.726871im
       0.0+0.0im             0.0+0.0im       …   -1.52939-1.2402im
       0.0+0.0im             0.0+0.0im           -1.66749+1.55855im
       0.0+0.0im             0.0+0.0im          -0.224935+0.0im

In [195]:
# Formamos el Hamiltoniano con los primeros valores de c 
H12 = c[1,1]*A111 + c[2,1]*A222

8×8 Matrix{ComplexF64}:
  0.140325+0.0im        0.0367667+0.042822im   …         0.0+0.0im
 0.0367667-0.042822im   0.0750621+0.0im                  0.0-0.882487im
  -1.01684+0.559266im         0.0-0.0429857im            0.0+0.0im
       0.0+0.0833298im   -1.15595+0.715258im        0.772992+0.927581im
  0.225957+0.170313im         0.0+0.0im                  0.0-0.0833298im
       0.0+0.0im         0.225957+0.170313im   …  -0.0466864+0.186628im
       0.0+0.882487im         0.0+0.0im            -0.191164+0.178675im
       0.0+0.0im              0.0+0.882487im       -0.140325+0.0im

In [196]:
# Tomamos los vectores propios 
vor  = eigen(H12).vectors
adjvor = adjoint(vor)

8×8 adjoint(::Matrix{ComplexF64}) with eltype ComplexF64:
 0.0519442+0.00418594im    0.183897-0.187943im  …  -0.469007+0.0im
  0.045417-0.144449im      0.182055-0.606674im      0.182329-0.0im
 -0.423358-0.437025im     0.0564523+0.258443im     -0.403396+0.0im
 -0.263795-0.352792im      0.161471-0.179786im      0.488403-0.0im
  0.094064+0.0216733im    0.0330994-0.233165im      0.251893-0.0im
   0.28863-0.0532915im   -0.0481077+0.105397im  …   -0.16157+0.0im
 -0.390586+0.22145im     -0.0422779+0.382627im       0.31367+0.0im
  0.301272-0.149185im    -0.0148229+0.428943im      0.396962+0.0im

In [221]:
n = 1000
mat = Matrix{Float64}(undef, 8, n)  # Matriz vacía 8x1000 (no inicializada)

# Haremos ahora un vector de 1000 elementos que son tuplas donde cada elemento de la tupla es un vector 
Tup = []

for k in 1 : n

    mat1a1 = zeros(2) # Colocamos un vector de ceros que se va a reiniciar en cada paso 

    # Formamos el Hamiltoniano
    H12 = c[1,k]*A111 + c[2,k]*A222

    # Tomamos los vectores propios 

    vor  = eigen(H12).vectors
    adjvor = adjoint(vor)

    vor[:,1] # Este es el primer vector propio, los vectores propios con eigen se colocan en columnas 
    adjvor[1,:] # Este es el primer vector propio para la adjunta (Recordemos es un vector izquierdo [Fila])

    # Calculamos el valor esperado de la primera mitad de vectores propios

    ExpValA = zeros(ComplexF64, Int((size(vor)[1])/2))
    for i in 1:Int((size(vecs)[1])/2)
        ExpValA[i] = transpose(adjvor[i,:])*A111*vor[:,i]
    end

    ExpValB = zeros(ComplexF64,Int((size(vor)[1])/2))  # ExpVal2[1] = a21 = \bra{\phi1_}A_2\ket{\phi_1}
    for i in 1:Int((size(vecs)[1])/2)
        ExpValB[i] = transpose(adjvor[i,:])*A222*vor[:,i]
    end

    ValsA = real(ExpValA) # Nos interesa únicamente la parte real, la parte imaginaria suele ser error 
    ValsB = real(ExpValB)
    mat1a1[1] = ValsA[1]
    mat1a1[2] = ValsA[2]

    tk = (mat1a1, c[:,k])
    push!(Tup,tk) # Agregar la tupla al vector 

    ValsCompleto = vcat(ValsA, ValsB) # Por último nuestro vector tendrá la forma de 8x1, para poder agregarlo al batch 
end 

In [222]:
Tup[100]

([-2.017791767743682, -1.7012065189594698], [0.5321518015185831, -0.27403867175531227])

In [224]:
# Extract inputs (x) and outputs (y) from the tuples
x_batch = cat(map(t -> t[1], Tup)...; dims=2)  # Stack inputs along the 4th dimension (batch)
y_batch = cat(map(t -> t[2], Tup)...; dims=2)  # Stack outputs along the 2nd dimension (batch)

# Check the shapes of the resulting batches
println("Shape of x_batch: ", size(x_batch))  # Should be (28, 28, 1, batch_size)
println("Shape of y_batch: ", size(y_batch))  # Should be (10, batch_size)

Shape of x_batch: (2, 1000)
Shape of y_batch: (2, 1000)


1-element Vector{Any}:
 ([0.5834266720957522, 0.11464171724943406], [3.5867059399377395, 2.9401657467473408])